Module driftdiffusion
{

  sources = (DriftDiffusion.cpp, DriftDiffusionProperties.cpp,
             ElectricalContact.cpp, DDInterfaceModel.cpp,
             DriftDiffusionModelInterface.cpp, ThermoelectricPower.cpp,
             MobilityModelInterface.cpp, BandProperties.cpp, DDBulkModel.cpp)
  
  
  #installpath = @ARCH/modules/@MODULE

#  Dependency strangelib
#  {
#    include = /path/to/include     
#    libs = mylib                  # -> -lmylib
#    libpath = /path/to/lib        # -> -L/path/to/lib
#    [installpath = where/to/put/it]
#  }

#  Dependency libhdf5
#  {
#    includes = /home/fsantoni/software/hdf5/include/
#    libraries = (hdf5, hdf5_hl)
#    libpath = /home/fsantoni/software/hdf5/lib/
#    install = false
#  }

  band_properties { sources = models/DefaultBandProperties.cpp }

  recombination srh { sources = models/SRHRecombination.cpp }
  recombination auger { sources = models/AugerRecombination.cpp }
  recombination direct { sources = models/DirectRecombination.cpp }
  recombination band2band { sources = models/Band2Band.cpp }
  recombination schottky_tunneling { sources = models/SchottkyTunneling.cpp }
  recombination exciton_dissociation { sources = models/ExcitonDissociation.cpp }
  recombination exciton_generation { sources = models/ExcitonGeneration.cpp }
  recombination optical { sources = models/OpticalGeneration.cpp }
  recombination langevin { sources = models/LangevinRecombination.cpp }
  
  mobility constant { sources = models/ConstantMobility.cpp }
  mobility doping_dependent { sources = models/DopingDependentMobility.cpp }
  mobility doping_dependent { sources = models/DopingDependentMobility.cpp }
  mobility field_assisted { sources = models/FieldAssistedMobility.cpp }
  mobility field_dependent { sources = models/FieldDependentMobility.cpp }
  mobility strained_Si { sources = models/SiStrainedMobility.cpp }
  mobility hopping_mobility { sources = models/HoppingMobility.cpp }
#  mobility parametric { sources = models/ParametricMobility.cpp }
#  mobility masse { sources = models/MasseMobility.cpp }
  
  ddbnd ohmic { sources = models/OhmicContact.cpp }
  ddbnd schottky { sources = models/SchottkyContact.cpp }

  ddbulk default { sources = models/SemiconductorModel.cpp }

  #creator_code = "
  #obj = DriftDiffusion::create(options);"


}

