#!/bin/bash

if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh


#REVISION=3581
REVISION=HEAD

echo "Compiling libMesh version $LIBMESHVERSION in $BUILDDIR ..."

mkdir -p $BUILDDIR
if [ ! -d $BUILDDIR ]; then
  echo "Directory $BUILDDIR does not exist."
  exit 1
fi


#ARCHIVE=v${LIBMESHVERSION}.tar.gz
ARCHIVE=libmesh-${LIBMESHVERSION}.tar.gz

PATCH=${PWD}/libmesh.patch-${LIBMESHVERSION}
WINPATCH=${PWD}/libmesh-win.patch

cd $BUILDDIR

if [ ! -e ${ARCHIVE} ]; then
  #wget -O $ARCHIVE https://github.com/libMesh/libmesh/releases/download/${ARCHIVE}
  #wget -O $ARCHIVE https://github.com/libMesh/libmesh/archive/${ARCHIVE}
  wget -O $ARCHIVE https://github.com/libMesh/libmesh/releases/download/v${LIBMESHVERSION}/${ARCHIVE}
fi

if [ ! -d libmesh-${LIBMESHVERSION}-$TCHOST ]; then
   if [ ! -e ${ARCHIVE} ]; then
     echo "Could not download libmesh."
     exit 1
   fi
  tar zxf ${ARCHIVE}
  mv libmesh-${LIBMESHVERSION} libmesh-${LIBMESHVERSION}-$TCHOST

  if [ -e ${PATCH} ]; then
    patch -p0 -d libmesh-${LIBMESHVERSION}-$TCHOST < ${PATCH}
  fi

#  if [ "$target_os" == "win32" && -e $WINPATCH ]; then
#    patch -p0 -d libmesh-${LIBMESHVERSION}-$TCHOST < $WINPATCH
#  fi
fi


#cd libmesh-${LIBMESHVERSION}-${TCHOST}/libmesh
cd libmesh-${LIBMESHVERSION}-${TCHOST}

# we have modifications to the configuration
#aclocal -I m4
#autoconf
#cp ${TOPDIR}/misc/configure.libmesh configure


#export SLEPC_DIR=${BUILDDIR}/slepc-${PETSCVERSION}${SLEPCPATCHLEVEL}
export PETSC_DIR=${BUILDDIR}/petsc-${PETSCVERSION}${PETSCPATCHLEVEL}
export PETSC_ARCH=${TCHOST}

#export CXX=${PETSC_DIR}/externalpackages/mpich2-1.0.8/bin/mpicxx
#LDFLAGS="${LDFLAGS} -L${PETSC_DIR}/${TCHOST}/lib"

SHARED=--enable-shared
if [ "${target_os}" = win32 ]
then
  # we do not need -fPIC
  SHARED=--disable-shared
fi
if [ "${target_os}" = darwin ]
then
  # we do not need -fPIC
  SHARED=--disable-shared
fi

dll_name=libmesh

if [ "${target_os}" != "win32" ]
then
  LDFLAGS="${LDFLAGS} -ldl"
fi

dll_name=${dll_name}${dll_libext}
  
export LDFLAGS

#--with-cc=${PETSC_DIR}/externalpackages/mpich2-1.0.8/bin/mpicc
#--with-cxx=${PETSC_DIR}/externalpackages/mpich2-1.0.8/bin/mpicxx 

#export METHODS=opt
#if [ $DEBUG == 'y' ]
#then
#  export METHODS=dbg
#fi

METHOD=devel

if [ "x$LINKONLY" == "x" ]
then

  ./configure --enable-petsc --disable-slepc --disable-complex \
    --enable-periodic ${SHARED} --disable-pfem --enable-static \
    --disable-second --enable-exceptions --disable-laspack --disable-sfc \
    --disable-gzstreams --disable-bzip2 --disable-vtk \
    --disable-tecplot --disable-netcdf --disable-exodus --disable-nemesis \
    --disable-libHilbert --disable-perflog  --disable-gmv \
    --disable-reference-counting --disable-legacy-using-namespace --enable-unique-ptr \
    --with-subdomain-id-bytes=2 \
    --with-fparser=none \
    --with-methods="$METHOD" \
    --host=$HOST --build=$BUILD


  make |tee make.log
fi


echo "Create shared library ${SDKDIR}/${TCHOST}/lib/${dll_name} ..."
#staticlib=`make echo | grep -m 1 libmesh.a`
#if [ $DEBUG == 'y' ]
#then
  staticlib=`find -name libmesh_${METHOD}.a`
#else
#  staticlib=`find -name libmesh_opt.a`
#fi
contriblibs=
#contriblibs=`echo $staticlib | sed -e 's/\.libs\//contrib\/\.libs\//' -e 's/libmesh_opt\.a/libcontrib_opt\.a/'`
#contribdir=${contriblibs/%\*\.a}
#rm -f ${contribdir}/libnemesis.*
#rm -f ${contribdir}/libexodusii.*
mkdir -p ${SDKDIR}/${TCHOST}/lib


ARCHIVES="-Wl,--whole-archive ${staticlib} ${contriblibs} -Wl,--no-whole-archive" 
if [ "$target_os" = darwin ]
then
  ARCHIVES="-Wl,-force_load,${staticlib}"
  for l in $(ls ${contribdir}/*.a)
  do
    #ARCHIVES="${ARCHIVES} -Wl,-reexport-l$(basename $l | sed 's/lib\(.*\)\.a/\1/')"
    ARCHIVES="${ARCHIVES} -Wl,-force_load,$l "
  done
fi 

if [ "$target_os" = darwin ]
then
  libmesh_linker_flags="-Wl,-install_name,@rpath/lib/${dll_name}"
fi


${CXX} -shared -o ${SDKDIR}/${TCHOST}/lib/${dll_name} \
  ${libmesh_linker_flags} \
  ${ARCHIVES} \
  -L${SDKDIR}/${TCHOST}/lib -Wl,-rpath,\$ORIGIN -lpetsc_real${dbg} \
  ${LDFLAGS} ${LAPACK_LIBS} ${FORTRAN_LIBS}

mkdir -p ${TOPDIR}/${TCHOST}/lib
cp ${SDKDIR}/${TCHOST}/lib/${dll_name} ${TOPDIR}/${TCHOST}/lib/${dll_name}



