#!/bin/bash
 

if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh


echo "Compiling TiberCAD ..."

cd ../

./configure \
  --with-petsc-prefix=${BUILDDIR}/petsc-${PETSCVERSION}-${PATCHLEVEL} \
  --with-petsc-arch=${ARCH}-complex \
  --with-slepc-prefix=${BUILDDIR}/slepc-${PETSCVERSION} \
  --disable-pardiso \
  --disable-modules \
  --enable-dftb \
  --enable-hetero \
  --enable-uptight \
  $OTHEROPTS \
  --with-libmesh-prefix=${BUILDDIR}/libmesh${LIBMESHVERSION}


#  --enable-license-check \


make
