#!/bin/bash


if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh


echo "Compiling SLEPc version $PETSCVERSION in $BUILDDIR ..."

mkdir -p $BUILDDIR
if [ ! -d $BUILDDIR ]; then
  echo "Directory $BUILDDIR does not exist."
  exit 1
fi

ARCHIVE=slepc-${PETSCVERSION}${SLEPCPATCHLEVEL}.tgz

cd $BUILDDIR
if [ ! -e ${ARCHIVE} ]; then
  wget http://www.grycap.upv.es/slepc/download/distrib/${ARCHIVE}
fi

if [ ! -e ${ARCHIVE} ]; then
  echo "Could not download slepc."
  exit 1
fi

if [ ! -d slepc-${PETSCVERSION}${SLEPCPATCHLEVEL} ]; then
  tar zxf ${ARCHIVE}
fi

cd slepc-${PETSCVERSION}${SLEPCPATCHLEVEL}


export PETSC_DIR=${BUILDDIR}/petsc-${PETSCVERSION}${PETSCPATCHLEVEL}
#export SLEPC_DIR=${BUILDDIR}/slepc-${PETSCVERSION}${SLEPCPATCHLEVEL}
export SLEPC_DIR=`pwd`


export PETSC_ARCH=${ARCH}
./config/configure.py $CONFIGOPTS
make


export PETSC_ARCH=${ARCH}-complex
./config/configure.py $CONFIGOPTS
make


if [ $DEBUG == 'y' ]; then
  export PETSC_ARCH=${ARCH}-dbg
  ./config/configure.py $CONFIGOPTS
  make

  export PETSC_ARCH=${ARCH}-complex-dbg
  ./config/configure.py $CONFIGOPTS
  make
fi

