#!/bin/bash

if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh


#export CXX=mpicxx

REVISION=3581

echo "Compiling libMesh version $LIBMESHVERSION in $BUILDDIR ..."

mkdir -p $BUILDDIR
if [ ! -d $BUILDDIR ]; then
  echo "Directory $BUILDDIR does not exist."
  exit 1
fi

ARCHIVE=libmesh${LIBMESHVERSION}.tar.gz
PATCH=${PWD}/libmesh.patch-${LIBMESHVERSION}
WINPATCH=${PWD}/libmesh-win.patch

cd $BUILDDIR
if [ ${LIBMESHVERSION} == "svn" ]; then
  if [ ! -d libmesh-${LIBMESHVERSION}-$TCHOST ]; then
    if [ ! -e libmesh-${LIBMESHVERSION}.tbz ]; then
      svn -r ${REVISION} co https://libmesh.svn.sourceforge.net/svnroot/libmesh/trunk/libmesh libmesh-${LIBMESHVERSION}
      tar jcf libmesh-${LIBMESHVERSION}.tbz libmesh-${LIBMESHVERSION}
      mv libmesh-${LIBMESHVERSION} libmesh-${LIBMESHVERSION}-$TCHOST
    else
      tar jxf libmesh-${LIBMESHVERSION}.tbz
      mv libmesh-${LIBMESHVERSION} libmesh-${LIBMESHVERSION}-$TCHOST
    fi

    if [ -e ${PATCH} ]; then
      patch -p0 -d libmesh-${LIBMESHVERSION}-$TCHOST < ${PATCH}
    fi

    if [ "$target_os" == "win32" ] && [ -e $WINPATCH ]; then
      patch -p0 -d libmesh-${LIBMESHVERSION}-$TCHOST < $WINPATCH

      cat > libmesh-${LIBMESHVERSION}-${TCHOST}/m4/check_file.m4 <<END
# AC_CHECK_FILE(FILE, [ACTION-IF-FOUND], [ACTION-IF-NOT-FOUND])
# -------------------------------------------------------------
#
# Check for the existence of FILE.
AC_DEFUN([AC_CHECK_FILE],
[AC_DIAGNOSE([cross],
	     [cannot check for file existence when cross compiling])dnl
AS_VAR_PUSHDEF([ac_File], [ac_cv_file_$1])dnl
AC_CACHE_CHECK([for $1], [ac_File],
[test "$cross_compiling" = yes &&
  AC_MSG_WARN([cannot check for file existence when cross compiling])
if test -r "$1"; then
  AS_VAR_SET([ac_File], [yes])
else
  AS_VAR_SET([ac_File], [no])
fi])
AS_IF([test AS_VAR_GET([ac_File]) = yes], [$2], [$3])[]dnl
AS_VAR_POPDEF([ac_File])dnl
])# AC_CHECK_FILE

END

    fi
  fi
else
  if [ ! -e ${ARCHIVE} ]; then
    wget http://dfn.dl.sourceforge.net/sourceforge/libmesh/${ARCHIVE}
  fi
fi

if [ ! -d libmesh-${LIBMESHVERSION}-$TCHOST ]; then
  if [ ! -e ${ARCHIVE} ]; then
    echo "Could not download libmesh."
    exit 1
  fi
  tar zxf ${ARCHIVE}
  mv libmesh-${LIBMESHVERSION} libmesh-${LIBMESHVERSION}-$TCHOST

  if [ -e ${PATCH} ]; then
    patch -p0 -d libmesh-${LIBMESHVERSION}-$TCHOST < ${PATCH}
  fi

  if [ "$target_os" == "win32" && -e $WINPATCH ]; then
    patch -p0 -d libmesh-${LIBMESHVERSION}-$TCHOST < $WINPATCH
  fi
fi


cd libmesh-${LIBMESHVERSION}-$TCHOST

# we have modifications to the configuration
#aclocal -I m4
#autoconf
cp ${TOPDIR}/misc/configure.libmesh configure


export PETSC_DIR=${BUILDDIR}/petsc-${PETSCVERSION}${PETSCPATCHLEVEL}
export PETSC_ARCH=${TCHOST}

# let's always compile the static version, and do the shared lib ourselves
#SHARED=--enable-shared
#if [ $shared_libs == 'n' ]
#then
#  SHARED=--disable-shared
#fi
SHARED=--enable-shared
if [ "${target_os}" = win32 ]
then
  # we do not need -fPIC
  SHARED=--disable-shared
fi
if [ "${target_os}" = darwin ]
then
  # we do not need -fPIC
  SHARED=--disable-shared
fi

dll_name=libmesh

if [ "${target_os}" != "win32" ]
then
  LDFLAGS="${LDFLAGS} -ldl"
fi

[ "$debug" = 1 ] && dll_name=${dll_name}_dbg
dll_name=${dll_name}${dll_libext}
  

./configure --enable-petsc --disable-slepc --disable-complex --disable-periodic ${SHARED} --disable-pfem --disable-second --disable-bzip2 --disable-exceptions --disable-laspack --disable-sfc --disable-gzstreams --disable-bzip2 --disable-tecplot --disable-netcdf --disable-exodus --disable-nemesis --disable-libHilbert --disable-perflog  --disable-gmv --disable-reference-counting --host=$HOST --build=$BUILD

#export libmesh_CXXFLAGS="-std=gnu++0x -g"
export libmesh_CXXFLAGS="-g -fpermissive"

# delete the -pedantic flag because it makes problems with mpi
cp Make.common Make.common.orig
sed -e 's/-pedantic//g' -e 's/-D_GLIBCXX_DEBUG_PEDANTIC//g' -e 's/-D_GLIBCXX_DEBUG//g' \
  -e "s/-ansi//g"  -e 's/^enable-shared.*/enable-shared := no/'  Make.common.orig > Make.common


make |tee make_opt.log

echo "Create shared library ${SDKDIR}/${TCHOST}/lib/${dll_name} ..."
staticlib=`make echo | grep libmesh.a`
contriblibs=`echo $staticlib | sed -e 's/lib\//contrib\/lib\//' -e 's/libmesh\.a/\*\.a/'`
contribdir=${contriblibs/%\*\.a}
rm -f ${contribdir}/libnemesis.*
rm -f ${contribdir}/libexodusii.*
mkdir -p ${SDKDIR}/${TCHOST}/lib

ARCHIVES="-Wl,--whole-archive ${staticlib} ${contriblibs} -Wl,--no-whole-archive" 
if [ "$target_os" = darwin ]
then
  ARCHIVES="-Wl,-force_load,${staticlib}"
  for l in $(ls ${contribdir}/*.a)
  do
    #ARCHIVES="${ARCHIVES} -Wl,-reexport-l$(basename $l | sed 's/lib\(.*\)\.a/\1/')"
    ARCHIVES="${ARCHIVES} -Wl,-force_load,$l "
  done
fi 

if [ "$target_os" = darwin ]
then
  libmesh_linker_flags="-Wl,-install_name,@rpath/lib/${dll_name}"
fi

${CXX} -shared -o ${SDKDIR}/${TCHOST}/lib/${dll_name} \
  ${libmesh_linker_flags} \
  ${ARCHIVES} \
  -L${SDKDIR}/${TCHOST}/lib -Wl,-rpath,\$ORIGIN -lpetsc_real${dbg} \
  ${LAPACK_LIBS} ${FORTRAN_LIBS}



if [ $DEBUG == 'y' ]; then
  export PETSC_ARCH=${TCHOST}-dbg
  make METHOD=dbg
fi

