#!/bin/bash

if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh

VERSION=1.2.5

if [ $SYSTEM == "mingw" ]; then
  ARCHIVE=zlib`echo $VERSION | sed 's/\.//g'`-dll.zip
else
  ARCHIVE=zlib-${VERSION}.tar.gz
fi

echo "Compiling zlib library"


mkdir -p $BUILDDIR
if [ ! -d $BUILDDIR ]; then
  echo "Directory $BUILDDIR does not exist."
  exit 1
fi



cd $BUILDDIR

if [ ! -e ${ARCHIVE} ]; then
  wget http://zlib.net/${ARCHIVE}
fi


if [ ! -e ${ARCHIVE} ]; then
  echo "Could not download ${ARCHIVE}."
  exit 1
fi


if [ $SYSTEM == "mingw" ]; then

  rm -rf zlib-${VERSION}-win
  mkdir -p zlib-${VERSION}-win
  unzip -d zlib-${VERSION}-win ${ARCHIVE}

  cd zlib-${VERSION}-win
  cp include/zconf.h include/zlib.h ${TOPDIR}/include/base/io/gzstream
  cp zlib1.dll ${TOPDIR}/${ARCH}/lib


else

  if [ ! -d zlib-${VERSION} ]; then
    tar zxf ${ARCHIVE}
  fi

  cd zlib-${VERSION}

  ./configure
  make

  cp zconf.h zlib.h ${TOPDIR}/include/base/io/gzstream
  cp zlib.so* ${TOPDIR}/${ARCH}/lib
fi
