#!/bin/bash


if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh


# Does the actual build
# needs at least 1 argument ('real' or 'complex')
# second argument can be 0 or 1, 1 for creating debug version
make_slepc()
{

  datatype=$1
  debug=0
  if [ $# -ge 2 ]
  then
    debug=$2
  fi

  export SLEPC_DIR=${PWD}

  export PETSC_DIR=${BUILDDIR}/petsc-${PETSCVERSION}${PETSCPATCHLEVEL}

  export PETSC_ARCH=${HOST}
  [ "$datatype" == "complex" ] && export PETSC_ARCH=${HOST}-complex

  echo "Building with PETSC_ARCH=${PETSC_ARCH} ..."

  ./config/configure.py $CONFIGOPTS
  make

  dbg=
  [ "$debug" == 1 ] && dbg=_dbg
  libname=${slepc_dll_name}_${datatype}${dbg}

  ARCHIVES="-Wl,--whole-archive ${SLEPC_DIR}/${PETSC_ARCH}/lib/*.a -Wl,--no-whole-archive"
  if [ "$target_os" = darwin ]
  then
    #ARCHIVES="-L${PETSC_DIR}/${PETSC_ARCH}/lib -Wl,-all_load"
    ARCHIVES=
    for l in $(ls ${SLEPC_DIR}/${PETSC_ARCH}/lib/*.a)
    do
      #ARCHIVES="${ARCHIVES} -Wl,-reexport-l$(basename $l | sed 's/lib\(.*\)\.a/\1/')"
      #ARCHIVES="${ARCHIVES} -l$(basename $l | sed 's/lib\(.*\)\.a/\1/')"
      ARCHIVES="${ARCHIVES} -Wl,-force_load,$l"
    done
  fi

  if [ "$target_os" = darwin ]
  then
    slepc_linker_flags="-Wl,-install_name,@rpath/lib/${libname}${dll_libext}"
  fi

  echo "Create shared library ${BUILDDIR}/${TCHOST}/lib/${libname}${dll_libext} ..."
  mkdir -p ${BUILDDIR}/${TCHOST}/lib
  ${CXX} -shared -o ${BUILDDIR}/${TCHOST}/lib/${libname}${dll_libext} \
    ${slepc_linker_flags} \
    ${ARCHIVES} \
    -L${BUILDDIR}/${TCHOST}/lib -Wl,-rpath,${BUILDDIR}/${TCHOST}/lib -lpetsc_${datatype}${dbg} \
    ${LAPACK_LIBS} ${FORTRAN_LIBS}

}



echo "Compiling SLEPc version $PETSCVERSION in $BUILDDIR ..."

mkdir -p $BUILDDIR
if [ ! -d $BUILDDIR ]; then
  echo "Directory $BUILDDIR does not exist."
  exit 1
fi

ARCHIVE=slepc-${PETSCVERSION}${SLEPCPATCHLEVEL}.tgz

cd $BUILDDIR
if [ ! -e ${ARCHIVE} ]; then
  wget http://www.grycap.upv.es/slepc/download/distrib/${ARCHIVE}
fi

if [ ! -e ${ARCHIVE} ]; then
  echo "Could not download slepc."
  exit 1
fi

if [ ! -d slepc-${PETSCVERSION}${SLEPCPATCHLEVEL} ]; then
  tar zxf ${ARCHIVE}
fi


slepc_dll_name=${dll_prefix}slepc


cd slepc-${PETSCVERSION}${SLEPCPATCHLEVEL}


make_slepc real
make_slepc complex

if [ $DEBUG == 'y' ]
then
  make_slepc real 1
  make_slepc complex 1
fi

