#!/bin/bash
 
#export CC=mpicc
#export CXX=mpicxx

if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh


echo "Compiling TiberCAD ..."

cd ../

if [ "$target_os" == "win32" ]; then
  cp contrib/dlfcn-win32-r19/dlfcn.h include/base/io
  cp contrib/dlfcn-win32-r19/dlfcn.c src/base/io
fi

if [ "x$target" != "x" ]; then
  TIBEROPTS="--host=$target $TIBEROPTS"
fi

./configure \
  --with-petsc-prefix=${BUILDDIR}/petsc-${PETSCVERSION}${PETSCPATCHLEVEL} \
  --with-petsc-arch=${HOST}-complex \
  --with-slepc-prefix=${BUILDDIR}/slepc-${PETSCVERSION}${SLEPCPATCHLEVEL} \
  $TIBEROPTS \
  --with-libmesh-prefix=${BUILDDIR}/libmesh-${LIBMESHVERSION}-${march} \
  --with-boost-prefix=${BUILDDIR}/boost --with-boost-libdir=${BUILDDIR}/boost/lib \
  --host=$HOST --build=$BUILD



make
