#!/bin/bash

if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh

VERSION=1_42_0
ARCHIVE=boost_${VERSION}.tar.bz2

echo "Compiling boost libraries"


mkdir -p $BUILDDIR
if [ ! -d $BUILDDIR ]; then
  echo "Directory $BUILDDIR does not exist."
  exit 1
fi



cd $BUILDDIR
if [ ! -e ${ARCHIVE} ]; then
  wget http://sourceforge.net/projects/boost/files/boost/`echo $VERSION | sed 's/_/\./g'`/${ARCHIVE}
fi


if [ ! -e ${ARCHIVE} ]; then
  echo "Could not download ${ARCHIVE}."
  exit 1
fi


cat <<PATCH >$BUILDDIR/boost.patch
--- libs/regex/build/Jamfile.v2.orig	2011-05-20 13:15:23.000000000 +0200
+++ libs/regex/build/Jamfile.v2	2011-05-20 13:15:47.000000000 +0200
@@ -274,9 +274,9 @@
         #<link>static:<define>BOOST_REGEX_NO_LIB=1
         #<link>static:<define>BOOST_REGEX_STATIC_LINK=1
 	     <link>shared:<define>BOOST_REGEX_DYN_LINK=1
-	     <toolset>gcc-mw:<link>static
-	     <toolset>gcc-mingw:<link>static
-	     <toolset>gcc-cygwin:<link>static
+	     #<toolset>gcc-mw:<link>static
+	     #<toolset>gcc-mingw:<link>static
+	     #<toolset>gcc-cygwin:<link>static
              <conditional>@force-shared-linking
     ;
PATCH



if [ ! -d boost_${VERSION} ]; then
  tar jxf ${ARCHIVE}
  cd boost_${VERSION}
  patch -p0 < ${BUILDDIR}/boost.patch
  cp tools/build/v2/user-config.jam tools/build/v2/user-config.jam.orig
  cd ..
fi

cd boost_${VERSION}

if [ "$target_os" == "win32" ]; then
  echo "using gcc : : $CXX : <src>${pre}windres <archiver>$AR ;" > tools/build/v2/user-config.jam
else
  echo "using gcc : : $CXX : <linkflags>-Wl,-rpath,${BUILDDIR}/boost/lib ;" > tools/build/v2/user-config.jam
fi

./bootstrap.sh --with-toolset=gcc --without-icu
if [ "$target_os" == "win32" ]; then
  bits=32
  [ "x$(echo $HOST | grep x86_64)" != "x" ] && bits=64

#  ./bjam toolset=gcc threading=multi link=shared runtime-link=shared target-os=windows threadapi=win32 --with-regex --with-filesystem --with-system --layout=tagged --prefix=${BUILDDIR}/boost install
  ./bjam toolset=gcc variant=release threading=single link=shared runtime-link=shared target-os=windows --with-regex --with-filesystem --with-system --layout=tagged --prefix=${BUILDDIR}/boost-$HOST address-model=$bits install
else
  ./bjam toolset=gcc variant=release threading=multi link=shared runtime-link=shared --with-regex --with-filesystem --with-system --layout=tagged --prefix=${BUILDDIR}/boost-$HOST install
fi


