#!/bin/bash
 

if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh

TIBEROPTS=${TIBEROPTS:-"--enable-uptight --enable-license-check --disable-hetero"}
#TIBEROPTS=${TIBEROPTS:-"--enable-uptight --disable-license-check --disable-hetero"}

if [ "$MKL" = y ]; then
TIBEROPTS="${TIBEROPTS} --with-mkl=${MKLDIR}"
fi

echo "Compiling TiberCAD ..."

cd ../

ARCH=`uname -m`
if [ $ARCH == "i686" ]
then
  sepparch=i686-debian-linux4.0
else
  sepparch=amd64-debian-linux5.0
  FCFLAGS="-fPIC ${FCFLAGS}"
fi
#if [ "$target_os" == "win32" ]; then
#  cp contrib/dlfcn-win32-r19/dlfcn.h include/base/io/dlfcn.h
#  cp contrib/dlfcn-win32-r19/dlfcn.c src/base/io/dlfcn.c
#fi

#export LD_RUN_PATH=`pwd`/SDK/${TCHOST}/lib
#export LD_LIBRARY_PATH=`pwd`/SDK/${TCHOST}/lib

echo ${BUILDDIR}/libmesh-${LIBMESHVERSION}-${TCHOST}

export CXXFLAGS="$CXXFLAGS -fopenmp"
export LDFLAGS="$LDFLAGS -fopenmp"

./configure \
  --with-cuda=${CUDADIR} \
  --with-petsc-prefix=${BUILDDIR}/petsc-${PETSCVERSION}${PETSCPATCHLEVEL} \
  --with-petsc-arch=${TCHOST} \
  --with-mpiexec=${MPIEXEC} \
  --with-thread-library=intel \
  --with-slepc-prefix=${BUILDDIR}/slepc-${SLEPCVERSION}${SLEPCPATCHLEVEL} \
  $TIBEROPTS \
  --with-libmesh-prefix=${BUILDDIR}/libmesh-${LIBMESHVERSION}-${TCHOST} \
  --with-libmesh-petsc-libdir=${SDKDIR}/${TCHOST}/lib \
  --with-boost-prefix=${SDKDIR} --with-boost-libdir=${TOPDIR}/${TCHOST}/lib \
  --host=$HOST --build=$BUILD

#  --with-mkl=${MKLDIR} \
#  --with-boost-prefix=${SDKDIR} --with-boost-libdir=${SDKDIR}/${TCHOST}/lib \

make METHOD=opt

if test "${MPIDIR}" != "${SDKDIR}"
then
  mkdir -p SDK/bin
  cp ${MPIDIR}/bin/mpiexec.hydra SDK/bin
fi
