#!/bin/bash

if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh


# Does the actual build
# needs at least 1 argument ('real' or 'complex')
# second argument can be 0 or 1, 1 for creating debug version
make_petsc()
{

  datatype=$1
  debug=0
  if [ $# -ge 2 ]
  then
    debug=$2
  fi

  export PETSC_DIR=${PWD}

  export PETSC_ARCH=${HOST}
  [ "$datatype" == "complex" ] && export PETSC_ARCH=${HOST}-complex

  if [ -e  ${TOPDIR}/misc/reconfigure-${PETSC_ARCH}.py ]
  then
    cp ${TOPDIR}/misc/reconfigure-${PETSC_ARCH}.py .
  fi

  echo "Building with PETSC_ARCH=${PETSC_ARCH} ..."

  if [ ! -e  reconfigure-${PETSC_ARCH}.py ] && [ ! -e  conftest-${PETSC_ARCH} ]; then
    ./config/configure.py ${CONFIGOPTS} --with-debugging=${debug} --with-scalar-type=${datatype} \
      --CFLAGS="${CFLAGS}" --FFLAGS="${FFLAGS}" --CXXFLAGS="${CXXFLAGS}" --LDFLAGS="${LDFLAGS}"
    cp conftest conftest-${PETSC_ARCH}
    if [ "$target_os" != "win32" ]; then
      ./conftest-${PETSC_ARCH}
      cp reconfigure.py reconfigure-${PETSC_ARCH}.py
    fi
  fi

  if [ -e  reconfigure-${PETSC_ARCH}.py ]; then
    ./reconfigure-${PETSC_ARCH}.py

    if [ "$target_os" == "win32" ]; then
      cp ${PETSC_ARCH}/include/petscconf.h ${PETSC_ARCH}/include/petscconf.h.bkp
      sed "/PETSC_HAVE_GETPAGESIZE/,+2 d" ${PETSC_ARCH}/include/petscconf.h.bkp |
      sed "/PETSC_HAVE_SLEEP/,+2 d" > ${PETSC_ARCH}/include/petscconf.h 
    fi

    make

    libname=${petsc_dll_name}_${datatype}
    [ $debug -eq 1 ] && libname=${libname}_dbg

    ARCHIVES="-Wl,--whole-archive ${PETSC_DIR}/${PETSC_ARCH}/lib/*.a -Wl,--no-whole-archive"
    if [ "$target_os" = darwin ]
    then
      #ARCHIVES="-L${PETSC_DIR}/${PETSC_ARCH}/lib -Wl,-all_load"
      ARCHIVES=
      for l in $(ls ${PETSC_DIR}/${PETSC_ARCH}/lib/*.a)
      do
        #ARCHIVES="${ARCHIVES} -Wl,-reexport-l$(basename $l | sed 's/lib\(.*\)\.a/\1/')"
        #ARCHIVES="${ARCHIVES} -l$(basename $l | sed 's/lib\(.*\)\.a/\1/')"
        ARCHIVES="${ARCHIVES} -Wl,-force_load,$l"
      done
    fi

    if [ "$target_os" = darwin ]
    then
      petsc_linker_flags="-Wl,-install_name,@rpath/lib/${libname}${dll_libext}"
    fi

    echo "Create shared library ${BUILDDIR}/${TCHOST}/lib/${libname}${dll_libext} ..."
    mkdir -p ${BUILDDIR}/${TCHOST}/lib
    ${CXX} -shared -o ${BUILDDIR}/${TCHOST}/lib/${libname}${dll_libext} \
      ${petsc_linker_flags} \
      ${ARCHIVES} \
      ${LAPACK_LIBS} ${FORTRAN_LIBS}
  fi

}



ARCHIVE="petsc-lite-${PETSCVERSION}${PETSCPATCHLEVEL}.tar.gz"
PATCH=${PWD}/petsc.patch-${PETSCVERSION}

echo "Compiling PETSc version $PETSCVERSION in $BUILDDIR ..."

mkdir -p $BUILDDIR
if [ ! -d $BUILDDIR ]; then
  echo "Directory $BUILDDIR does not exist."
  exit 1
fi

cd $BUILDDIR
if [ ! -e ${ARCHIVE} ]; then
  wget ftp://ftp.mcs.anl.gov/pub/petsc/release-snapshots/${ARCHIVE}
fi

if [ ! -e ${ARCHIVE} ]; then
  echo "Could not download petsc."
  exit 1
fi

if [ ! -d petsc-${PETSCVERSION}${PETSCPATCHLEVEL} ]; then
  tar zxf ${ARCHIVE}

  if [ -e ${PATCH} ]; then
    patch -p0 -d petsc-${PETSCVERSION}${PETSCPATCHLEVEL} < ${PATCH}
  fi
fi

cd petsc-${PETSCVERSION}${PETSCPATCHLEVEL}



# PETSc shared libraries cannot be moved around, therefore
# we compile them always statically

#SHARED="--with-shared=1 --with-dynamic=1"
#if [ $shared_libs == 'n' ]
#then
SHARED="--with-shared=0 --with-dynamic=0"
#fi
  

#COMPILERS="--with-cc=$CC --with-cxx=$CXX --with-fc=$FC --with-ranlib=$RANLIB --with-cpp=$CPP --with-shared-ld=$LD --with-ar=${AR}"
COMPILERS="--with-cc=$CC --with-cxx=$CXX --with-fc=$FC --with-ranlib=$RANLIB \
  --with-cpp=$(echo $CC | sed 's/gcc.*/cpp/') --with-shared-ld=$(echo $CC | sed 's/gcc.*/ld/') \
  --with-ar=$(echo $CC | sed 's/gcc.*/ar/')"


if [ $MPI == 'n' ]; then
  MPI="--with-mpi=0"
else
  MPI="--with-mpi-dir=${MPIDIR}"
fi

LAPACKLIBS=${LAPACKLIBS:-"--download-f-blas-lapack=1"}

petsc_host=
petsc_dll_name=${dll_prefix}petsc

if [ "${target_os}" = "win32" ]
then
  petsc_host="--with-host-vendor=w64 --with-host-os=mingw32"
fi


CONFIGOPTS="--with-matlab=0 $SHARED  $MPI $COMPILERS --with-clanguage=C++ ${LAPACKLIBS} --with-batch=1 --with-x=0 ${petsc_host}"



make_petsc real
make_petsc complex


if [ $DEBUG == 'y' ]
then
  make_petsc real 1
  make_petsc complex 1
fi


