#!/bin/bash

if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh


# Does the actual build
# needs at least 1 argument ('real' or 'complex')
# second argument can be 0 or 1, 1 for creating debug version
make_petsc()
{

  datatype=$1
  debug=0
  if [ $# -ge 2 ]
  then
    debug=$2
  fi

  if [ -e  ${TOPDIR}/misc/reconfigure-${PETSC_ARCH}.py ]
  then
    cp ${TOPDIR}/misc/reconfigure-${PETSC_ARCH}.py .
  fi

  echo "Building with PETSC_ARCH=${PETSC_ARCH} ..."

  if [ ! -e  reconfigure-${PETSC_ARCH}.py ] && [ ! -e  conftest-${PETSC_ARCH} ]; then
    #./config/configure.py ${CONFIGOPTS} --with-debugging=${debug} --with-scalar-type=${datatype} \
    #  --CFLAGS="${CFLAGS}" --FFLAGS="-fno-range-check ${FFLAGS}" --CXXFLAGS="${CXXFLAGS}" --LDFLAGS="${LDFLAGS}"
    ./configure \
    --CC="$CC" --CXX="$CXX" --FC="$FC" --F77="$F77" --CPP="$CPP" \
    --CXXFLAGS="$CXXFLAGS" --FCFLAGS="$FCFLAGS" --CFLAGS="$CFLAGS" \
    --FFLAGS="$FFLAGS" --LDFLAGS="$LDFLAGS" \
    ${CONFIGOPTS} --with-debugging=${debug} --with-scalar-type=${datatype} \
    --with-blas-lapack-lib="${LAPACK_LIBS}"
    #cp conftest conftest-${PETSC_ARCH}

    if [ "$target_os" != "win32" ]; then
      mpirun ./conftest-${PETSC_ARCH}
      #cp reconfigure.py reconfigure-${PETSC_ARCH}.py
    fi
  fi

  if [ -e  reconfigure-${PETSC_ARCH}.py ]; then
    ./reconfigure-${PETSC_ARCH}.py

    if [ "$target_os" == "win32" ]; then
      cp ${PETSC_ARCH}/include/petscconf.h ${PETSC_ARCH}/include/petscconf.h.bkp
      sed "/PETSC_HAVE_GETPAGESIZE/,+2 d" ${PETSC_ARCH}/include/petscconf.h.bkp |
      sed "/PETSC_HAVE_SLEEP/,+2 d" > ${PETSC_ARCH}/include/petscconf.h 
    fi

    make
  fi
  rm conftest* reconfigure*
}

link_library()
{
  datatype=$1

    libname=${petsc_dll_name}_${datatype}
    #[ $debug -eq 1 ] && libname=${libname}_dbg

    # need to delete mpiuni, or we get troubles
    if [ "$MPI" = y ]; then
      echo "Remove libmpiuni.a"
      rm ${PETSC_DIR}/${PETSC_ARCH}/lib/libmpiuni.a
    fi

    ARCHIVES="-Wl,--whole-archive ${PETSC_DIR}/${PETSC_ARCH}/lib/*.a -Wl,--no-whole-archive"
    if [ "$target_os" = darwin ]
    then
      #ARCHIVES="-L${PETSC_DIR}/${PETSC_ARCH}/lib -Wl,-all_load"
      ARCHIVES=
      for l in $(ls ${PETSC_DIR}/${PETSC_ARCH}/lib/*.a)
      do
        #ARCHIVES="${ARCHIVES} -Wl,-reexport-l$(basename $l | sed 's/lib\(.*\)\.a/\1/')"
        #ARCHIVES="${ARCHIVES} -l$(basename $l | sed 's/lib\(.*\)\.a/\1/')"
        ARCHIVES="${ARCHIVES} -Wl,-force_load,$l"
      done

      petsc_linker_flags="-Wl,-install_name,@rpath/lib/${libname}${dll_libext}"
    fi


    #echo "Copy shared library to ${SDKDIR}/${TCHOST}/lib/${libname}${dll_libext} ..."
    #cp ${PETSC_DIR}/${PETSC_ARCH}/lib/libpetsc.so ${SDKDIR}/${TCHOST}/lib/${libname}${dll_libext}

    echo "Create shared library ${SDKDIR}/${TCHOST}/lib/${libname}${dll_libext} ..."
    echo "${CXX} -shared -o ${SDKDIR}/${TCHOST}/lib/${libname}${dll_libext} \
      ${petsc_linker_flags} \
      ${ARCHIVES} \
      -Wl,-rpath,\$ORIGIN \
      ${LDFLAGS} ${LAPACK_LIBS} ${FORTRAN_LIBS}"

    mkdir -p ${SDKDIR}/${TCHOST}/lib
    ${CXX} -shared -o ${SDKDIR}/${TCHOST}/lib/${libname}${dll_libext} \
      ${petsc_linker_flags} \
      ${ARCHIVES} \
      -Wl,-rpath,\$ORIGIN \
       ${MPI_LIBS} ${LDFLAGS} ${LAPACK_LIBS} ${FORTRAN_LIBS}

    mkdir -p ${TOPDIR}/${TCHOST}/lib
    cp ${SDKDIR}/${TCHOST}/lib/${libname}${dll_libext} ${TOPDIR}/${TCHOST}/lib/${libname}${dll_libext}


}



ARCHIVE="petsc-${PETSCVERSION}${PETSCPATCHLEVEL}.tar.gz"
PATCH=${PWD}/petsc.patch-${PETSCVERSION}

echo "Compiling PETSc version $PETSCVERSION in $BUILDDIR ..."

mkdir -p $BUILDDIR
if [ ! -d $BUILDDIR ]; then
  echo "Directory $BUILDDIR does not exist."
  exit 1
fi

cd $BUILDDIR
if [ ! -e ${ARCHIVE} ]; then
  wget ftp://ftp.mcs.anl.gov/pub/petsc/release-snapshots/${ARCHIVE}
fi

if [ ! -e ${ARCHIVE} ]; then
  echo "Could not download petsc."
  exit 1
fi

if [ ! -d petsc-${PETSCVERSION}${PETSCPATCHLEVEL} ]; then
  tar zxf ${ARCHIVE}

  if [ -e ${PATCH} ]; then
    patch -p0 -d petsc-${PETSCVERSION}${PETSCPATCHLEVEL} < ${PATCH}
  fi
fi

cd petsc-${PETSCVERSION}${PETSCPATCHLEVEL}



# PETSc shared libraries cannot be moved around, therefore
# we compile them always statically

SHARED="--with-shared-libraries=0"
  

#COMPILERS="--with-cc=$CC --with-cxx=$CXX --with-fc=$FC --with-ranlib=$RANLIB \
#  --with-cpp=$(echo $CC | sed 's/gcc.*/cpp/') --with-shared-ld=$(echo $CC | sed 's/gcc.*/ld/') \
#  --with-ar=$(echo $CC | sed 's/gcc.*/ar/')"
#COMPILERS="--CC=$CC --CXX=$CXX --FC=$FC --F77=$F77 --CPP=$CPP --CXXFLAGS=$CXXFLAGS --FCFLAGS=$FCFLAGS --CFLAGS=$CFLAGS --FFLAGS=$FFLAGS"
#COMPILERS="--CXXFLAGS=$CXXFLAGS --FCFLAGS=$FCFLAGS --CFLAGS=$CFLAGS --FFLAGS=$FFLAGS"
#COMPILERS="--with-cc=$CC --with-cxx=$CXX --with-fc=$FC --with-ranlib=$RANLIB --with-cpp=$CPP --with-shared-ld=$LD --with-ar=${AR}"
#COMPILERS="--with-cc=$CC --with-cxx=$CXX --with-fc=$FC --with-ranlib=$RANLIB \
#  --with-cpp=$(echo $CC | sed 's/gcc.*/cpp/') --with-shared-ld=$(echo $CC | sed 's/gcc.*/ld/') --fPIC\
#  --with-ar=$(echo $CC | sed 's/gcc.*/ar/')"

if [ "${target_os}" = "win32" ]
then
  COMPILERS="--with-cc=$CC --with-cxx=$CXX --with-fc=$FC --with-ranlib=$RANLIB \
    --with-cpp=$(echo $CC | sed 's/gcc.*/cpp/') \
    --with-shared-ld=$(echo $CC | sed 's/gcc.*/ld/') \
    --with-ar=$(echo $CC | sed 's/gcc.*/ar/')"
else

#  COMPILERS="--with-cc=$CC --with-cxx=$CXX --with-fc=$FC"
#COMPILERS="--CXXFLAGS=$CXXFLAGS --FCFLAGS=$FCFLAGS --CFLAGS=$CFLAGS --FFLAGS=$FFLAGS"
#COMPILERS="--LDFLAGS=\"${LDFLAGS}\""
COMPILERS=
fi


if [ $MPI == 'n' ]; then
  MPIFLAGS="--with-mpi=0"
else
  #MPI="--with-mpi-dir=${MPIDIR}  --known-mpi-shared-libraries=1"
  MPIFLAGS="--known-mpi-shared-libraries=1"
  if [ "${target_os}" = "win32" ]
  then
    MPIFLAGS="--with-mpi-compilers=0 --with-mpi-include=[${MPIDIR}/Include,${MPIDIR}/Include/x86] --with-mpi-lib=[-L,${MPIDIR}/Lib/x86,-Xlinker,-Bstatic,msmpifec,msmpi,quirk,-Xlinker,-Bdynamic] --known-mpi-shared-libraries=1"
  fi
fi
LAPACKLIBS=${LAPACKLIBS:-"--download-f-blas-lapack=1"}

petsc_host=
petsc_dll_name=${dll_prefix}petsc

if [ "${target_os}" = "win32" ]
then
  petsc_host="--with-host-vendor=w64 --with-host-os=mingw32"
fi


CONFIGOPTS="--with-matlab=0 $SHARED  $MPIFLAGS $COMPILERS --with-clanguage=cxx --with-batch=1 --with-x=0 ${petsc_host} --with-ssl=0"
#CONFIGOPTS="--with-matlab=0 $SHARED  $MPI $COMPILERS --with-clanguage=C++ ${LAPACKLIBS} --with-batch=1 --with-x=0 \
#  ${petsc_host} --download-mumps=yes  --download-parmetis=1 --download-scalapack=1 --download-blacs=1"

export FCFLAGS="-fno-range-check $FCFLAGS"
export FFLAGS=$FCFLAGS


export PETSC_DIR=${PWD}

export PETSC_ARCH=${TCHOST}
if [ "x$LINKONLY" == 'x' ]; then
  make_petsc real
fi
link_library real

export PETSC_ARCH=${TCHOST}-complex
if [ "x$LINKONLY" == 'x' ]; then
  make_petsc complex 
fi
link_library complex

