#!/bin/bash

if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh

VERSION=3.1.1
ARCHIVE=mpich-${VERSION}.tar.gz

echo "Compiling openmpi libraries"


mkdir -p $BUILDDIR
if [ ! -d $BUILDDIR ]; then
  echo "Directory $BUILDDIR does not exist."
  exit 1
fi



cd $BUILDDIR
if [ ! -e ${ARCHIVE} ]; then
  wget http://www.mpich.org/static/downloads/${VERSION}/${ARCHIVE}
fi


if [ ! -e ${ARCHIVE} ]; then
  echo "Could not download ${ARCHIVE}."
  exit 1
fi

if [ ! -d mpich-${VERSION} ]; then
  tar zxf ${ARCHIVE}
fi



#F90=
#export F90


cd mpich-${VERSION}

./configure --prefix=${SDKDIR} --enable-shared=yes \
            --host=$HOST --build=$BUILD
            
#            --with-thread-package=none --with-pmi=none \
#            --with-pm=none --with-shared-memory=no \
#            --enable-threads=single --disable-romio

#            --with-cross=${TOPDIR}/misc/win_cross_values \
make install

