#!/bin/bash

if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh

VERSION=1_42_0
ARCHIVE=boost_${VERSION}.tar.bz2

echo "Compiling boost libraries"


mkdir -p $BUILDDIR
if [ ! -d $BUILDDIR ]; then
  echo "Directory $BUILDDIR does not exist."
  exit 1
fi



cd $BUILDDIR
if [ ! -e ${ARCHIVE} ]; then
  wget http://sourceforge.net/projects/boost/files/boost/`echo $VERSION | sed 's/_/\./g'`/${ARCHIVE}
fi


if [ ! -e ${ARCHIVE} ]; then
  echo "Could not download ${ARCHIVE}."
  exit 1
fi


cat <<PATCH >$BUILDDIR/boost.patch
--- libs/regex/build/Jamfile.v2.orig	2011-05-20 13:15:23.000000000 +0200
+++ libs/regex/build/Jamfile.v2	2011-05-20 13:15:47.000000000 +0200
@@ -274,10 +274,10 @@
         #<link>static:<define>BOOST_REGEX_NO_LIB=1
         #<link>static:<define>BOOST_REGEX_STATIC_LINK=1
 	     <link>shared:<define>BOOST_REGEX_DYN_LINK=1
-	     <toolset>gcc-mw:<link>static
-	     <toolset>gcc-mingw:<link>static
-	     <toolset>gcc-cygwin:<link>static
+	     #<toolset>gcc-mw:<link>static
+	     #<toolset>gcc-mingw:<link>static
+	     #<toolset>gcc-cygwin:<link>static
	     \$(BOOST_REGEX_ICU_OPTS)
              <conditional>@force-shared-linking
     ;
--- tools/build/v2/tools/darwin.jam.orig	2009-11-10 18:26:59.000000000 +0100
+++ tools/build/v2/tools/darwin.jam	2011-06-22 21:37:45.000000000 +0200
@@ -450,7 +450,7 @@
 flags darwin.compile OPTIONS <link>shared : -dynamic ;
  
 # Misc options.
-flags darwin.compile OPTIONS : -no-cpp-precomp -gdwarf-2 ;
+flags darwin.compile OPTIONS : -gdwarf-2 ;
   
 # Add the framework names to use.
 flags darwin.link FRAMEWORK <framework> ;
--- tools/build/v2/tools/darwin.py.orig	2009-10-28 08:47:51.000000000 +0100
+++ tools/build/v2/tools/darwin.py	2011-06-22 17:32:05.000000000 +0200
@@ -37,7 +37,7 @@
 feature.feature ('framework', [], ['free'])
      
 toolset.flags ('darwin.compile', 'OPTIONS', '<link>shared', ['-dynamic'])
-toolset.flags ('darwin.compile', 'OPTIONS', None, ['-Wno-long-double', '-no-cpp-precomp'])
+toolset.flags ('darwin.compile', 'OPTIONS', None, ['-Wno-long-double'])
 toolset.flags ('darwin.compile.c++', 'OPTIONS', None, ['-fcoalesce-templates'])
        
 toolset.flags ('darwin.link', 'FRAMEWORK', '<framework>')
PATCH



if [ ! -d boost_${VERSION} ]; then
  tar jxf ${ARCHIVE}
  cd boost_${VERSION}
  patch -p0 < ${BUILDDIR}/boost.patch
  cp tools/build/v2/user-config.jam tools/build/v2/user-config.jam.orig
  cd ..
fi

cd boost_${VERSION}
toolset=gcc
if [ "$target_os" = darwin ]
then
  toolset=darwin
fi

if [ "$target_os" = win32 ]; then
  echo "using gcc : : $CXX : <src>$(echo $CC | sed 's/gcc/windres/') <archiver>$AR ;" > tools/build/v2/user-config.jam
else
  echo "using $toolset : : $CXX : <linkflags>-Wl,-rpath,${BUILDDIR}/boost/lib ;" > tools/build/v2/user-config.jam
fi

./bootstrap.sh --with-toolset=$toolset --without-icu
if [ "$target_os" = win32 ]; then
  bits=32
  [ "x$(echo $HOST | grep x86_64)" != "x" ] && bits=64

  ./bjam toolset=gcc variant=release threading=single link=shared runtime-link=shared target-os=windows --with-regex --with-filesystem --with-system --layout=tagged --prefix=${BUILDDIR}/$TCHOST address-model=$bits install
else
  ./bjam toolset=$toolset variant=release threading=multi link=shared runtime-link=shared --with-regex --with-filesystem --with-system --layout=tagged --prefix=${BUILDDIR}/$TCHOST install
fi

if [ "$target_os" = darwin ]
then
  cd ${BUILDDIR}/$TCHOST/lib
  for lib in libboost_*.dylib
  do
    install_name_tool -id "@rpath/lib/$lib" "$lib"
    if [[ "$lib" =~ filesystem ]]
    then
      deplib="$(echo "$lib" | sed 's/file//')"
      install_name_tool -change "$deplib" "@rpath/lib/$deplib" "$lib"
    fi
  done
fi

