Module negf
{

  sources = (Negf.C, NegfModel.C)
  
  
  #installpath = @ARCH/modules/@MODULE

  Dependency libnegf
  {
    includes = libnegf
    libraries = negf             # -> -lmylib
    libpath = libnegf           # -> -L/path/to/lib
  }

  
  hamiltonian single_band { sources = models/SingleBand.C }
  hamiltonian etb { sources = models/EtbModel.C }


}

