Module negf
{

  sources = (Negf.C, NegfModel.C)
  
  
  #installpath = @ARCH/modules/@MODULE

  Dependency libnegf
  {
    include = libnegf
    libs = negf             # -> -lmylib
    #libpath = libnegf        # -> -L/path/to/lib
    #[installpath = where/to/put/it]
  }

  
  hamiltonian single_band { sources = models/HamiltonianModel.C }


}

