Module common
{

  installpath = @ROOT/@ARCH/modules

  polarization pyro { sources = Pyropolarization.C }
  polarization piezo { sources = Piezopolarization.C }
  polarization nonlinear { sources = NonlinearPolarization.C }

  heat_source constant { sources = ConstantHeatSource.C }
  heat_source joule { sources = DDHeatSource.C }

  permittivity constant { sources = ConstantPermittivity.C }
  
  thermal_conductivity constant { sources = ConstantThermalConductivity.C }
  thermal_conductivity linear { sources = LinearThermalConductivity.C }
  
  density_of_states exponential { sources = ExponentialDOS.C }
  density_of_states gauss { sources = GaussDOS.C }
  density_of_states bulk_kp { sources = KPBulkDOS.C }
  density_of_states bulk { sources = BulkDOS.C }
  density_of_states delta { sources = DeltaDOS.C }
  density_of_states constant { sources = ConstantDOS.C }
  density_of_states exciton_gauss { sources = ExcitonGaussDOS.C }
  density_of_states quantum { sources = QuantumDOS.C }

}

