Module common
{

  installpath = @ROOT/@ARCH/modules

  polarization pyro { sources = Pyropolarization.cpp }
  polarization piezo { sources = Piezopolarization.cpp }
  polarization nonlinear { sources = NonlinearPolarization.cpp }

  heat_source constant { sources = ConstantHeatSource.cpp }
  heat_source joule { sources = DDHeatSource.cpp }

  permittivity constant { sources = ConstantPermittivity.cpp }
  
  thermal_conductivity constant { sources = ConstantThermalConductivity.cpp }
  thermal_conductivity linear { sources = LinearThermalConductivity.cpp }
  
  density_of_states exponential { sources = ExponentialDOS.cpp }
  density_of_states gauss { sources = GaussDOS.cpp }
  density_of_states bulk_kp { sources = KPBulkDOS.cpp }
  density_of_states bulk { sources = BulkDOS.cpp }
  density_of_states delta { sources = DeltaDOS.cpp }
  density_of_states constant { sources = ConstantDOS.cpp }
  density_of_states exciton_gauss { sources = ExcitonGaussDOS.cpp }
  density_of_states quantum { sources = QuantumDOS.cpp }

}

