Module common
{

  installpath = @ARCH/modules

  polarization pyro { sources = Pyropolarization.C }
  polarization piezo { sources = Piezopolarization.C }

  heat_source constant { sources = ConstantHeatSource.C }
  heat_source joule { sources = DDHeatSource.C }

  permittivity constant { sources = ConstantPermittivity.C }
  
  thermal_conductivity constant { sources = ConstantThermalConductivity.C }
  thermal_conductivity linear { sources = LinearThermalConductivity.C }
  
  density_of_states exponential { sources = ExponentialDOS.C }

}

