// $Id$

#ifndef _DRIFTDIFFUSION_H_
#define _DRIFTDIFFUSION_H_

#include "SimulationInterface.h"
#include "SimulationOptions.h"
#include "DriftDiffusionDefs.h"
#include "Device.h"
#include "SolverException.h"

// Libmesh includes
#include "libmesh_common.h"
#include "enum_order.h"
#include "enum_quadrature_type.h"
#include "linear_implicit_system.h"


// C++ includes
#include <vector>
#include <set>
#include <map>


// forward declarations
//class Device;
class Boundary;
class MeshBase;
class Elem;
class Point;
class Node;
class EquationSystems;
class TiberLinearSolver;


template<typename T> class DenseMatrix;
template<typename T> class NumericVector;
template<typename T> class SparseMatrix;


//! The main class to perform standard drift-diffusion calculations
/*!
 * We solve the following system of equations:
 * \f{eqnarray*}
 * -\nabla(\epsilon_r\nabla\varphi -\mathrm{P})& = & \frac{e}{\epsilon_0}
 *     \left(-n + p + N_D^+ - N_A^-\right) \\
 * -\nabla(\mu_n n\nabla\phi_n) & = & R \\
 * -\nabla(\mu_p p\nabla\phi_p) & = & R
 * \f}
 * using appropriate models for the ionization of dopants, polarization,
 * mobilities and recombinations.
 *
 *
 * The get_solution() methods can provide the following variables:
 * \li \c ElPotential electric potential (V)
 * \li \c Ec conduction band edge (eV)
 * \li \c Ev valence band edge (eV)
 * \li \c Ec0 "intrinsic" conduction band edge (without electric potential, eV)
 * \li \c Ev0 "intrinsic" valence band edge (without electric potential, eV)
 * \li \c Eg band gap (eV)
 * \li \c eDensity electron density (cm^-3)
 * \li \c hDensity hole density (cm^-3)
 * \li \c eMob electron mobility (cm^2/Vs)
 * \li \c hMob hole mobility (cm^2/Vs)
 * \li \c eCond electron conductivity (S/cm)
 * \li \c hCond hole conductivity (S/cm)
 * \li \c QFermi_e electron electro-chemical potential (V)
 * \li \c QFermi_h hole electro-chemical potential (V)
 * \li \c E modulus of electric field (V/cm)
 * \li \c Ex electric field, x-component
 * \li \c Ey electric field, y-component
 * \li \c Ez electric field, z-component
 * \li \c J modulus of total current density
 * \li \c Jn modulus of electron current density
 * \li \c Jp modulus of hole current density
 * \li \c Jn_x electron current density, x-component
 * \li \c Jn_y electron current density, y-component
 * \li \c Jn_z electron current density, z-component
 * \li \c Jp_x hole current density, x-component
 * \li \c Jp_y hole current density, y-component
 * \li \c Jp_z hole current density, z-component
 * \li \c Pn electron thermoelectric power
 * \li \c Pp hole thermoelectric power
 * \li \c Hrecombination.some_name power density (\f$s^{-1} \cdot cm^{-3}\f$)
 *   generated by the non radiative recombination of model of model \c some_name
 * \li \c recombination.some_name the net recombination rate
 *   (\f$s^{-1} \cdot cm^{-3}\f$) of model \c some_name
 * \li \c recombination.total the total net recombination rate
 *
 */
class TBDLLOCAL DriftDiffusion : public SimulationInterface
{
  public:

    //! The variables that can be provided
    enum Solutions
    {
      Ec,               /*!< conduction band edge */
      Ev,               /*!< valence band edge */
      eQFermi,          /*!< electron electro-chemical potential */
      hQFermi,          /*!< hole electro-chemical potential */
      ElPotential,      /*!< electric potential */
      Ec0,              /*!< bare conduction band edge */
      Ev0,              /*!< bare valence band edge */
      //CBANDEDGEINTR,    /*!< intrinsic conduction band edge */
      //VBANDEDGEINTR,    /*!< intrinsic valence band edge */
      Eg,               /*!< band gap */
      ConductionBands,  /*!< the conduction band energies */
      ValenceBands,     /*!< the valence band energies */
      eDensity,         /*!< electron density */
      hDensity,         /*!< hole density */
      IntrinsicDensity, /*!< the intrinsic density */
      eMobility,        /*!< electron mobility */
      hMobility,        /*!< hole mobility */
      eConductivity,    /*!< electron conductivity */
      hConductivity,    /*!< hole conductivity */
      ElField,          /*!< electric field vector */
      Polarization,     /*!< total electric polarization */
      CurrentDensity,   /*!< total electric current density */
      //eFlux,            /*!< electron flux */
      //hFlux,            /*!< hole flux */
      eCurrentDensity,  /*!< electron current density */
      hCurrentDensity,  /*!< hole current density */
      IonizedDonors,    /*!< ionized donor density */
      IonizedAcceptors, /*!< ionized acceptor density */
      IonizedElectronTraps, /*!< trapped electron density */
      IonizedHoleTraps, /*!< trapped hole density */
      eThElPower,       /*!< electron thermoelectric power */
      hThElPower,       /*!< hole thermoelectric power */
      eJoule,           /*!< electron Joule heat */
      hJoule,           /*!< hole Joule heat */
      ePowerFlux,       /*!< electron power flux */
      hPowerFlux,       /*!< hole power flux */
      ePeltier,         /*!< Electron Peltier-Thomson heat source */
      hPeltier,         /*!< Electron Peltier-Thomson heat source */
      RecombHeat,       /*!< Recombination heat  */
      IQE,              /*!< Internal quantum efficiency */
      NetRecombination = 100,  /*!< base number for recombination models */
      ContactCurrent   = 200,  /*!< base number for contact currents */
      ContactVoltage   = 300   /*!< base number for contact voltages */

    };


    //! The solver methods that can be used
    enum SolverMethod
    {
      NEWTON,
      GUMMEL
    };


    //! How to calculate currents
    enum CurrentCalculation
    {
      /*!
       * Use Ramo-Shockley test functions
       * (cf. calculate_current_rstf_global() )
       */
      RSTF,

      /*!
       * Use Ramo-Shockley test functions
       * with compact (local) support
       * (cf. calculate_current_rstf_compact() )
       */
      RSTF_COMPACT,

      /*!
       * Do a naive surface integration
       * (cf. calculate_current_surfint() )
       */
      SURFINT
    };

    //! The default BC for Poisson
    enum DefaultBC
    {
        //! Zero electric field
        ZEROFIELD,

        //! Zero displacement
        ZERODISPLACEMENT
    };



    /**
     * This class defines various parameters that control a
     * drift-diffusion calculation
     */
    class Options
    {
      public:

        Options(void);

        /**
         * Enable or disable mesh refinement
         */
        bool mesh_refinement;

        /**
         * Maximum number of refinement steps
         */
        int max_refinement_steps;

        /**
         * Maximum allowable refinement level
         *
         * The refinement hierarchy will not get deeper than this
         * value, i.e. an element will not be refined more than
         * @c max_refinement_level times.
         */
        int max_refinement_level;

        /**
         * The error fraction for refinement
         *
         * All elements with percentual error bigger than @c refine_fraction
         * will get refined.
         */
        float refine_fraction;

        /**
         * The error fraction for coarsening
         *
         * All elements with percentual error lower than @c coarsen_fraction
         * will get coarsened.
         */
        float coarsen_fraction;

        /**
         * The tolerance at which mesh refinement will stop
         */
        double refinement_tolerance;

        //! The quadrature rule to be used
        libMeshEnums::QuadratureType quadrature_type;

        /**
         * The order of gauss integration
         */
        libMeshEnums::Order integration_order;

        /**
         * The solver method
         *
         * Can be @c NEWTON or @c GUMMEL
         */
        SolverMethod solver_method;

        /**
         * The maximum number of iteration steps for
         * the Gummel method
         */
        int max_gummel_iterations;

        //! The type of scaling to be applied
        /*!
         * Can be one of \c NONE, \c UNITS or \c DEMARI
         */
        Scaling::ScalingType scaling_type;

        //! The type of coupling to be used
        /*!
         * We safe it as int, because we want to assign values by
         * using logic operators, e.g. \code ELECTRONS | POISSON \endcode
         */
        int coupling;


        //! How to calculate currents
        CurrentCalculation current_calculation;

        //! Use exact jacobian or not
        bool exact_newton;

        //! Reference contact for the potential
        std::string reference_contact;


        //! Integrate polarization along the boundary
        DefaultBC default_boundary_condition;

        //! Whether or not to enforce local charge neutrality
        bool local_neutrality;


        private:


          friend class DriftDiffusion;
    };



    //! Destructor
    virtual ~DriftDiffusion(void);


    //! Create an DriftDiffusion object
    static DriftDiffusion* create(const ModelOptions& options);


    //! Create the bulk model
    virtual PhysicalModel*
      create_bulk_model(const ModelOptions& options,
          const Material* mat) const;


    //! Create the boundary model
    virtual PhysicalModel* create_boundary_model(const ModelOptions& options,
        const MaterialBoundary* boundary) const;



    /**
     * Enables adaptive mesh refinement.
     */
    void enable_mesh_refinement(void);


    /**
     * Disables adaptive mesh refinement.
     */
    void disable_mesh_refinement(void);


    //! Set the electron quasi Fermi level to \c Ef_n
    /*!
     * \c Ef_n has to be given as electron energy in units of eV
     *
     * \note {Put some figure her for illustration. }
     */
    void set_electron_fermi_level(double Ef_n);


    //! Set the hole quasi Fermi level to \c Ef_p
    /*!
     * \c Ef_p has to be given as electron energy in units of eV
     *
     * \note {Put some figure her for illustration. }
     */
    void set_hole_fermi_level(double Ef_p);


    //! Set the electric potential everywhere to \c pot
    void set_electric_potential(double pot);


    //! Makes a first guess of the equilibrium potential
    /**
     * It sets every node to its equilibrium potential.
     */
    void guess_equilibrium(void);


    //! Get the number of nonlinear iterations needed for the solution
    unsigned int get_n_nonlinear_iterations(void) const;


    //! Get the final residual norm of the solution
    double get_final_residual(void) const;





  protected:

    //! Constructor
    DriftDiffusion(const ModelOptions& options);


    //! Initialize the equation system
    /*!
     * This has to be called before any call to methods which access the
     * equation system object. So do it early.
     */
    virtual void do_init(void);


    //! Reinit the simulation
    virtual void do_reinit(void);


    //! Setup the available variables
    virtual void do_setup_solution_variables(void);


    /*! \copydoc SimulationInterface::do_equilibrium() */
    virtual void do_equilibrium(void);


    //! Solve the drift-diffusion problem.
    /*!
     * If adaptive mesh refinement was enabled for this solver
     * run, it will be deactivated afterwards and has to be re-enabled
     * explicitly.
     */
    virtual void do_solve(void);


    /*! \copydoc SimulationInterface::do_print_info() */
    virtual void do_print_info(void);


    /*! \copydoc SimulationInterface::parse_options() */
    virtual void parse_options(void);


    /*! \copydoc SimulationInterface::do_maximum_norm_of_difference() */
    virtual double do_maximum_norm_of_difference(ID id);


    /*!
     * \copydoc SimulationInterface::get_solution_secure(const Elem*,
     *  std::map<ID, std::vector<double> >&, const std::vector<Point>&)
     */
    virtual void get_solution_secure(const Elem* elem,
        std::map<ID, std::vector<double> >& values,
        const std::vector<Point>& p);


    /*!
     * \copydoc SimulationInterface::get_solution_secure(
     *  std::map<ID, std::vector<double> >&)
     */
    virtual void get_solution_secure(
        std::map<ID, std::vector<double> >& values);


    //! We override this to not produce too many files ...
    virtual void plot_globaldata(void) {};


    //! We need to reimplement this
    virtual void do_set_to_remembered_solution(ID id);


    //! Reload the current state
    virtual void do_load_data(std::istream& is);



  private:

  
    // for nicer code
    typedef std::map<const Boundary*, double> ContactData;
    typedef std::set<unsigned int> DofList;


    //! Internal class for the RSTF test functions
    class RSTFSys : public LinearImplicitSystem
    {
      public:
        RSTFSys(EquationSystems& es,
            const std::string& name,
            const unsigned int number)
        : LinearImplicitSystem(es, name, number), _dd(NULL)
        {}

        static RSTFSys* create(DriftDiffusion* dd);

        void user_assembly(void);

        void solve(void);

        NumericVector<double>* get_testfunction(int i);

        NumericVector<double>* get_testfunction(const Boundary* bd);

      private:
        DriftDiffusion* _dd;

        std::map<const Boundary*, int> _boundaries;

        void plot(void);
        void build_nodal_results(std::vector<double>& results,
            std::vector<std::string>& legend);
    };

    friend class RSTFSys;

    //! The penalty value for Dirichlet BCs
#ifdef HAVE_CONSTEXPR
    constexpr static double _penalty_value = 1e56;
#else
    const static double _penalty_value = 1e56;
#endif


    //! A static reference to \c this
    /*!
     * This is needed during matrix assembly, which is a static method.
     */
    static DriftDiffusion* _this;


    //! An internal pointer to the device
    Device* _device;


    /*!
     * \brief A list of nodes which lie on an inner boundary between
     * a dielectric and a semiconductor
     */
    std::set<const Node*> _dielectric_boundary_nodes;

    //! A set of all recombination model IDs (for variables)
    std::set<ID> _recombination_ids;


    /*!
     * If @c true, the equation system needs to be rebuilt
     */
    bool _rebuild_eq_system;


    /*!
     * The @c Options to be used
     */
    Options _options;


    //! The particles to be solved for
    /*!
     * 'e' -> electrons
     * 'h' -> holes
     * 'b' -> both
     */
    char _useparticle;


    //! The boundary currents
    /*!
     * Currents are calculated after each solve step.
     */
    ContactData _boundary_currents;


    //! The voltages of the former solve step
    ContactData _voltages;


    //! The IQE
    double _iqe;


    //! Reference potential
    double _reference_potential;


    //! If true, local density scaling should be applied
    bool _do_local_scaling;

    //! Calculate the local density scaling on each node
    void build_local_scaling(void);

    /**
     * The number of nonlinear iterations needed
     */
    unsigned int _n_nonlinear_iterations;

    /**
     * The final residual norm
     */
    double _final_residual;


    //! A guess for the electron fermi level
    double _el_qfermi_guess;


    //! A guess for the hole fermi level
    double _hl_qfermi_guess;


    //! The RSTFSys object
    RSTFSys* _rstf;


    //! disable the copy constructor
    DriftDiffusion(const DriftDiffusion& rhs);

    //! disable the copy assignment operator
    DriftDiffusion& operator=(const DriftDiffusion& rhs);


    //! Do a number of Gummel iterations
    /*!
     * \return the final residual
     * \param the maximum number of iterations
     */
    //double do_gummel_iterations(int max_it) throw (SolverException);


    //! Parse the options which will not change between calls to solve()
    void parse_const_options(void);


    /**
     * @returns a reference to the simulation options
     */
    Options& get_my_options(void);


    //! Rebuild the equation system if needed
    void rebuild_equation_system(void);


    /*!
     * \brief Computes the scaling parameters according to the
     * scaling type \p type
     */
    void compute_scaling(Scaling::ScalingType type = Scaling::UNITS);


    //! Find the reference potential, if needed
    void compute_reference_potential(void);


    //! Find nodes on boundary between dielectric/semiconductor
    void find_dielectric_boundary_nodes(void);


    //! Tells if node lies on an inner dielectric/semiconductor boundary
    bool is_dielectric_boundary_node(const Node* node) const;


    //! Find elements that touch a real contact
    void find_contact_elements(void);


    //! Reset solver environment.
    /*!
     * Deletes only the \p EquationSystems object, without
     * touching simulation voltages and solutions.
     */
    void reset_solver(void);



    //! Cleanup solver environment.
    /*!
     * Deletes the \p EquationSystems object, the simulation voltages
     * vector and the solution and variable vectors.
     */
    void cleanup_solver(void);


    //! Do a Newton type iteration
    void do_newton(void);


    //! Calculate field emission currents
    void calculate_field_emission(void);


    //! Calculate the rstf test functions
    void prepare_rstf(void);


    //! Calculate the terminal currents
    /*!
     * Calls \c calculate_currents_surfint() or
     * calculate_currents_rstf()
     */
    void calculate_currents(void);


    //! Calculate terminal currents
    /*!
     * Integrates numerically over the boundary elements.
     * The current on the l'th contact is then:
     *
     * \f[I_l = -e \int_{\Gamma_l}\left(\mu_n n \nabla\phi_n +
     * \mu_p p \nabla\phi_p \right) \mathrm{d}\Gamma \f]
     */
    void calculate_currents_surfint(void);


    //! Calculate terminal currents
    /*!
     * Uses the Ramo-Shockley test functions and integrates over the
     * volume.
     *
     * Assuming electron and hole generation-recombination terms to be
     * equal, one can write:
     * \f[\left(-\nabla(\mathbf{j}_n + \mathbf{j}_p), hl\right) =
     * -\int_\Omega h_l \nabla (\mathbf{j}_n + \mathbf{j}_p)\mathrm{d}V = 0\f]
     * where \f$h_l|_{\Gamma_j} = \delta_{lj}, h_l \in H^1\f$ is the test
     * function for the contact \it l
     *
     * Using Gauss in the scalar product, one gets
     * \f[ 0 = - \int_{\partial\Omega}h_l(\mathbf{j}_n +
     * \mathbf{j}_p)\mathrm{\mathbf{S}}
     * + \int_\Omega \nabla h_l (\mathbf{j}_n +
     * \mathbf{j}_p)\mathrm{d}V\f]
     * The first term of the left hand side is exactly the terminal current
     * of contact \it l due to our choice of the testfunction, therefore
     * \f[ I_l = \int_\Omega \nabla h_l (\mathbf{j}_n +
     * \mathbf{j}_p)\mathrm{d}V\f]
     *
     * In this implementation we choose the test function to be (where \it i
     * is a node index and \f$\psi_i\f$ the FEM basis function associated with
     * node \it i):
     * \f[h_l = \sum_{i \in \Gamma_l}\psi_i\f]
     */
    void calculate_currents_rstf_global(void);

    //! Compact (local) version of RSTF
    void calculate_currents_rstf_compact(void);


    //! Calculates internal quantum efficiency
    void calculate_iqe(void);

    //! Calculates total surface recombination
    void calculate_surface_recombination(void);


    //! Create a weight for the l2 norm
    void calculate_weights(void);


    //! Assemble the residual vector or the jacobian matrix
    /*!
     * This method gets called from the underlying nonlinear solver
     * library. It calls the real assembly routines.
     */
    static void assemble_system(const NumericVector<Number>& x,
        NumericVector<Number>* residual,
        SparseMatrix<Number>* jacobian);


    //! Assembles the residual vector or the jacobian matrix
    /*!
     * Assembles the residual vector or the jacobian matrix for
     * the equation system with @c Coupling T.
     *
     * This implementation uses standard FEM.
     */
    template <int T>
    void do_assembly(const NumericVector<Number>& x,
        NumericVector<Number>* residual,
        SparseMatrix<Number>* jacobian);


    //! Write out a vector (e.g. residual)
    void write_nodal_vector(const std::string& filename,
        const NumericVector<double>& vec);


 

};


//
// inline member functions
//

inline
DriftDiffusion*
DriftDiffusion::create(const ModelOptions& options)
{
  return new DriftDiffusion(options);
}


inline
DriftDiffusion::Options&
DriftDiffusion::get_my_options(void)
{
  return _options;
}


inline
void
DriftDiffusion::enable_mesh_refinement(void)
{
  _options.mesh_refinement = true;
}

inline
void
DriftDiffusion::disable_mesh_refinement(void)
{
  _options.mesh_refinement = false;
}



inline
unsigned int
DriftDiffusion::get_n_nonlinear_iterations(void) const
{
  return _n_nonlinear_iterations;
}

inline
double
DriftDiffusion::get_final_residual(void) const
{
  return _final_residual;
}




inline
bool
DriftDiffusion::is_dielectric_boundary_node(const Node* node) const
{
  bool result = false;
  if (_dielectric_boundary_nodes.find(node) != _dielectric_boundary_nodes.end())
    result = true;

  return result;
}





#endif //_DRIFTDIFFUSION_H_
