Module driftdiffusion
{

  sources = (DriftDiffusion.C, DriftDiffusionProperties.C,
             ElectricalContact.C, BandProperties.C, DDInterfaceModel.C,
             DriftDiffusionModelInterface.C, ThermoelectricPower.C)
  
  createable = DriftDiffusion

  Dependency strangelib
  {
    include = /path/to/include
    libs = mylib                  # -> -lmylib
    libpath = /path/to/lib        # -> -L/path/to/lib
    [installpath = where/to/put/it]
  }

  recombination srh   # -> recombination_srh.so | .dll
  {
    sources = SRHRecombination.C
    createable = SRHRecombination
  }

  ddbnd ohmic         # -> ddbnd_ohmic.so | .dll
  {
    sources = OhmicContact.C
    createable = OhmicContact
  }

}

