Module driftdiffusion
{

  sources = (DriftDiffusion.C, DriftDiffusionProperties.C,
             ElectricalContact.C, BandProperties.C, DDInterfaceModel.C,
             DriftDiffusionModelInterface.C, ThermoelectricPower.C,
             MobilityModelInterface.C, DDBulkModel.C)
  
  
  #installpath = @ARCH/modules/@MODULE

  Dependency strangelib
  {
    include = /path/to/include
    libs = mylib                  # -> -lmylib
    libpath = /path/to/lib        # -> -L/path/to/lib
    [installpath = where/to/put/it]
  }
  
  band_properties kp { sources = models/KPBand.C }
  band_properties simple { sources = models/SimpleBand.C }

  recombination srh { sources = models/SRHRecombination.C }
  recombination auger { sources = models/AugerRecombination.C }
  recombination direct { sources = models/DirectRecombination.C }
  recombination band2band { sources = models/Band2Band.C }
  recombination schottky_tunneling { sources = models/SchottkyTunneling.C }
  recombination exciton_dissociation { sources = models/ExcitonDissociation.C }
  recombination exciton_generation { sources = models/ExcitonGeneration.C }
  recombination optical { sources = models/OpticalGeneration.C }
  
  mobility constant { sources = models/ConstantMobility.C }
  mobility doping_dependent { sources = models/DopingDependentMobility.C }
  mobility doping_dependent { sources = models/DopingDependentMobility.C }
  mobility field_assisted { sources = models/FieldAssistedMobility.C }
  mobility field_dependent { sources = models/FieldDependentMobility.C }

  ddbnd ohmic { sources = models/OhmicContact.C }
  ddbnd schottky { sources = models/SchottkyContact.C }
  
  ddbulk default { sources = models/SemiconductorModel.C }

  #creator_code = "
  #obj = DriftDiffusion::create(options);"


}

