Module tmm
{
  sources = (Tmm.cpp, TmmBulkModel.cpp, TmmBoundaryModel.cpp, TmmDipoleSource.cpp,matrix2by2.cpp)
  tmm_bnd mirror { sources = models/Mirror.cpp }
  tmm_bnd incident_wave { sources = models/Incident_wave.cpp }
  tmm_bnd dipole_source { sources = models/Dipole_source.cpp }

  bulk_model Incoherency{ sources = models/IncoherentModel.cpp }
  
  dipole_source radiative_recombination{ sources = models/OpticalRecombination.cpp }
}
