#!/bin/bash

topdir=`pwd`

ARCH=`${topdir}/share/arch.sh`
PETSC=petsc-3.0.0-p12
SLEPC=slepc-3.0.0-p7

mkdir -p SDK/include/libmesh
cd SDK/include

cp -r ${topdir}/extern/libmesh-svn-${ARCH}/include/* libmesh
mkdir -p libmesh/${ARCH}
mv libmesh/base/libmesh_config.h libmesh/${ARCH}
mv libmesh/base/libmesh_contrib_config.h libmesh/${ARCH}
rm libmesh/base/libmesh_contrib_config.h.in

mkdir -p ${SLEPC}
cp -r ${topdir}/extern/${SLEPC}/include/* ${SLEPC}
find ${SLEPC} -name "*.html" -exec rm -f {} \;

mkdir -p ${PETSC}/${ARCH}/
cp -r ${topdir}/extern/${PETSC}/include/* ${PETSC}/
cp -r ${topdir}/extern/${PETSC}/${ARCH}/include/* ${PETSC}/${ARCH}
#rm ${PETSC}/${ARCH}/*.mod
find ${PETSC} -name "makefile" -exec rm -f {} \;

mkdir -p tibercad/$ARCH
awk ' {system("mkdir -p $(dirname tibercad/"$1") ; cp -r '${topdir}'/include/"$1" tibercad/"$1); }' ${topdir}/share/sdk_headers
mv tibercad/base/common/tiber_config.h tibercad/$ARCH
rm tibercad/base/common/*.in

find . -type d -name .svn -exec rm -rf {} \;
find . -name .cvsignore -exec rm {} \;

