#!/bin/bash

topdir=`pwd`

ARCH=i686-mingw32
PETSC=petsc-3.0.0-p12
SLEPC=slepc-3.0.0-p7

mkdir -p SDK/include/libmesh
cd SDK/include

cp -r ${topdir}/extern/libmesh-svn-${ARCH}/include/* libmesh
find . -type d -name .svn -exec rm -rf {} \;
find . -name .cvsignore -exec rm {} \;
mkdir -p libmesh/${ARCH}
mv libmesh/base/libmesh_config.h libmesh/${ARCH}
mv libmesh/base/libmesh_contrib_config.h libmesh/${ARCH}
rm libmesh/base/libmesh_contrib_config.h.in

mkdir -p ${SLEPC}
cp -r ${topdir}/extern/${SLEPC}/include/* ${SLEPC}
find ${SLEPC} -name "*.html" -exec rm -f {} \;

mkdir -p ${PETSC}/${ARCH}/
cp -r ${topdir}/extern/${PETSC}/include/* ${PETSC}/
cp -r ${topdir}/extern/${PETSC}/${ARCH}/include/* ${PETSC}/${ARCH}
#rm ${PETSC}/${ARCH}/*.mod
find ${PETSC} -name "makefile" -exec rm -f {} \;

mkdir -p tibercad/$ARCH
mkdir  tibercad/core
mkdir  tibercad/io
mkdir  tibercad/solvers
