#!/bin/bash

topdir=`pwd`
#builddir=/usr/pack/tibercad_dev-2.5-ma/build
builddir=${topdir}/extern
libmesh=libmesh-1.0.0-x86_64-linux

ARCH=`${topdir}/share/arch.sh`
PETSC=petsc-3.6.2
SLEPC=slepc-3.6.2

mkdir -p SDK/include
cd SDK/include

cp -L -r ${builddir}/${libmesh}/include/libmesh .
mkdir -p libmesh/${ARCH}
mv libmesh/libmesh_config.h libmesh/${ARCH}
#mv libmesh/base/libmesh_contrib_config.h libmesh/${ARCH}
rm libmesh/*.h.in libmesh/Makefile*

mkdir -p ${SLEPC}
cp -r ${builddir}/${SLEPC}/include/* ${SLEPC}
find ${SLEPC} -name "*.html" -exec rm -f {} \;

mkdir -p ${PETSC}/${ARCH}/
cp -r ${builddir}/${PETSC}/include/* ${PETSC}/
cp -r ${builddir}/${PETSC}/${ARCH}/include/* ${PETSC}/${ARCH}
rm ${PETSC}/${ARCH}/*.mod
find ${PETSC} -name "makefile" -exec rm -f {} \;

mkdir -p tibercad/$ARCH
awk ' {system("mkdir -p $(dirname tibercad/"$1") ; cp -r '${topdir}'/include/"$1" tibercad/"$1); }' ${topdir}/share/sdk_headers
mv tibercad/base/common/tiber_config.h tibercad/$ARCH
rm tibercad/base/common/*.in
#find tibercad -path "tibercad/utils/Tensor/*" -prune -o -name "*.h" -execdir echo {} \;
find tibercad -path "tibercad/utils/Tensor/*" -prune -o -name "*.h" -execdir sh -c "cat ${topdir}/share/Copyright_sdk.txt {} > {}.tmp && mv {}.tmp {}" \;

find . -type d -name .svn -exec rm -rf {} \;
find . -name .cvsignore -exec rm {} \;

cd ..
patchelf --set-rpath '$ORIGIN:$ORIGIN/../lib:$ORIGIN/../../../x86_64-linux/lib' x86_64-linux/bin/build_module
