# $Id$


# the definitions and rules needed to compile modules
module := yes

# include common Makefile
include $(topdir)/Make.common

ifeq ($(build_modules), yes)


# reset the target
target := 


CPPFLAGS += -DMODULE_NAME=$(MODULE_NAME) $(MODULE_INCLUDES)
CXXFLAGS += $(MODULE_CXXFLAGS)


modulelib = $(shell grep TIBER_MODULE $(1) | sed "s/MODULE_NAME/$(MODULE_NAME)/" \
	| sed -e "s/[[:space:]]//g" -e 's/.*TIBER_MODULE([a-zA-Z]*,\([-a-zA-Z_,]*\))/\1/' -e "s/,/_/g")$(shared_libext)


#
# arguments:
#  1. list of source files
#  2. additional compiler / linker flags
#
define MODULE


target += $(module_dir)/$(MODULE_NAME)/$$(call modulelib, $(1))


$(module_dir)/$(MODULE_NAME)/$$(call modulelib, $(1)) : $$(patsubst %.C,.$$(ARCH)/%$$(obj-suffix),$(1))
	@echo "Linking module $$(notdir $$@) ..."
	@[ -d $$(dir $$@) ] || mkdir -p  $$(dir $$@)
	@$$(CXX) -shared $$(CXXFLAGS) $$^ $(2) -Wl,--as-needed $$(MODULE_LDFLAGS) $$(DEPENDENCY_LIBS) -o $$@

endef


else

define MODULE
endef


endif # ($(build_modules), yes)
