# $Id$

# the definitions and rules needed to compile modules

# include common Makefile
include $(topdir)/Make.common

ifeq ($(build_modules), yes)

# reset the target
target :=


CPPFLAGS += -DMODULE_NAME=$(MODULE_NAME)
MODULE_CXXFLAGS := -fvisibility=hidden
MODULE_LDFLAGS += -L$(topdir)/lib -ltibercad


modulelib = $(shell echo `grep TIBER_MODULE $(1) | sed 's/MODULE_NAME/$(MODULE_NAME)/' \
		| sed -e 's/[[:space:]]//g' -e 's/TIBER_MODULE([a-zA-Z]\+,\([a-zA-Z_,]\+\))/\1/' -e 's/,/_/g'`$(shared_libext))


define MODULE

target += $(libdir)/modules/$(MODULE_NAME)/$$(call modulelib, $(1))

$(libdir)/modules/$(MODULE_NAME)/$$(call modulelib, $(1)) : $$(patsubst %.C,%$$(obj-suffix),$(1)) $$(patsubst %.C,%$$(obj-suffix),$(2))
	@echo "Linking module $$(notdir $$@) ..."
	@[ -d $$(dir $$@) ] || mkdir -p  $$(dir $$@)
	@$$(CXX) -shared  $$(CPPFLAGS) $$(CXXFLAGS) $$(MODULE_CXXFLAGS) $$(MODULE_LDFLAGS) \
			-Wl,-soname,$$(notdir $$@) -o $$@ $$^

endef


else

define MODULE
endef


endif # ($(build_modules), yes)
