Module maxwell
{

  sources = (MaxwellEquations.C, CubicEigenSystem.C, EdgeDofMap.C, EigenSystem.C,
             VectorSystem.C, ScalarFEBase2D.C, ScalarFEBase3D.C, VectorFEBase2D.C,
             VectorFEBase3D.C, OpticPropsModel.C)  

  Dependency eigensolver
  {
    libraries = eigen_solver
  }
  
  #installpath = @ARCH/modules/@MODULE

  opticmodel metal { sources = MetalOpticProps.C }
}


Module maxwell_boundary
{

  sources = (MaxwellBoundaryEquations.C, EdgeDofMap.C, VectorLinearSystem.C,
             VectorSystem.C, ScalarFEBase2D.C, ScalarFEBase3D.C, VectorFEBase2D.C,
             VectorFEBase3D.C, OpticPropsModel.C)
  
  opticmodel w_dependant { sources = OpticPropsWDependant.C }
  
  #installpath = @ARCH/modules/@MODULE

}


