Module maxwell
{

  sources = (MaxwellEquations.C, CubicEigenSystem.C, EdgeDofMap.C,
             EigenSystem.C, ScalarFEBase2D.C, ScalarFEBase3D.C,
             VectorFEBase2D.C, VectorFEBase3D.C)
  
  
  #installpath = @ARCH/modules/@MODULE

}


Module maxwell_boundary
{

  sources = (MaxwellBoundaryEquations.C)
  
  
  #installpath = @ARCH/modules/@MODULE

}

