#ifndef _READISEGRID_H_
#define _READISEGRID_H_

#include <iomanip>

#include <iostream> //for I/O interaction
#include <fstream>  //for file streaming
#include <string>   //for strings
//#include <stdio>   //for exit() function
#include <set>
#include <map>

#include "ISE_Vertex.h"
#include "ISE_Edge.h"
#include "ISE_Element_2D.h"
#include "ISE_Element_1D.h"

//  LibMesh  include files
#include "mesh_data_elements.h"
#include "mesh_data.h"
#include "libmesh.h"
#include "mesh.h"
#include "mesh_generation.h"


//! Interface to .grd mesh files  created by ISE TCAD (v 9.5) .
/*!   
 * Reads and parsers the  mesh file .grd generated by ISE TCAD.
 * Elements with dimension dim = simulation dimension in ISE TCAD are extracted
 * and used (together with all the  nodes) to generate  .xda  file  (\c write_xda) and .xta file (\c write_xta) 
 *  for mesh and  meshdata in Libmesh, respectively.
 *  IDs  of  Physical Regions (excluded "Contacts") as  defined in ISE TCAD are associated to the  
 *  corresponding elements  and saved in Meshdata object through   the auxiliary file .xta.
 * Physical regions with elements with a dimension lower than the  simulation dimension ("Contacts") are  treated
 *  separately:
 * they  are  extracted from the  elements  list and  a list of  nodes for  each of  such "boundary regions"
 * (1D lines for 2D  problems and  2D surfaces for 3D problems) is  created.
 * This  list can be accessed through   \c get_BC_data , which returns a map between 
 * Boundary Condition Region number (BC id) and a vector of node id.
 *  
 */
class ReadISEGrid
{
		
           
 public:

  //! Constructor
  /*!
   * Reads ISE  grid  file , writes two  DEAL  mesh files for  Libmesh 
   * and from these load data in objects \c Mesh and \c MeshData_elements
   */
 // 
  ReadISEGrid(const char* file_name , Mesh& mesh, MeshData_elements&  mesh_data );
  //! Destructor
  /*!
   * Deletes all \c ReadISEGrid objects (to do...)
   */
  virtual ~ReadISEGrid();
	
  //! Returns map <phys reg. , vector<BC_nodes> >
  /*!
   * 
   * 
   */
  void  get_BC_data (map<unsigned int, vector<unsigned int> >& BoundCond_map );
	
 private:


  //! Scan ISE  grid  file    
  /*!
   * Reads in  ISE  grid  file, creates objects \c ISE_Element_2D ISE_Element_1D 
   * ISE_Vertex and ISE_Edge and fill them with  relevant  data.
   */
  void scan_grid_file();
	
		
  //! Writes  mesh file for  Libmesh in  DEAL  format  (in.xda ) 
  /*!
   * Writes .xda file with a  DEAL header, a  list  of  all (simulation-dimension) elements  
   * in the  mesh and  a  list  of all  nodes.
   */
  void  write_xda ();

  //! Writes  data file for  meshdata (elem_data.xta ) 
  /*!
   * Writes .xta file with a  list  of  all  (simulation-dimension) elements 
   * associated to  related physical  region ID
   */
  void  write_xta();
	
	
  //! Utlility    to  eliminate  repetitions  in  node  list
  /*!
   * 
   * 
   */
  //void  unique2(vector<unsigned int> & v1);
  void  unique_nodes(vector<unsigned int>& v1);
	 
  //  check if orientation  of  nodes  is  positive,  otherwise swap  nodes  of  element
  // void   Read_MSH::check_orientation( vector<unsigned int>&  node_id_list , unsigned  int type );


  //!  Writes map which associates  nodes belonging to Boundary regions
  // [ (dimension-1) elements] and relative regions
  /*!
   * 
   * 
   */
  void set_BC_data();
	
  //!  write  mesh  and  meshdata from  .xda and  .xta  files 
  // 
  /*!
   * 
   * 
   */
	void  read_mesh_and_data(Mesh& mesh, MeshData_elements&  mesh_data );

  // **************** private  member  data:
	
  const char* ISE_file_name;
	
  unsigned int dimension, nb_vertices, nb_edges, nb_faces, nb_elements, nb_regions;
	
	
	
  //ISE_Vertex*  vertices[nb_vertices];
	
  ISE_Vertex* vertex_point;
  vector<ISE_Vertex*> vertices;
		
  //	ISE_Edge* edges[nb_edges];
	
  ISE_Edge* edge_point;
  vector<ISE_Edge*> edges;
	
  //	ISE_Element* elements_list[nb_elements];
	
  ISE_Element* elements_list_point;
  vector<ISE_Element*> elements_list;
	
	
  unsigned int num_of_elem; // number of  nD  elements  nor  a  nD  simulation
	
  vector<unsigned int> ISE_element_type_list;
	
  vector<ISE_Element*> xda_list_elements;
	
  // lists of ISE physical region IDs, respectively of 1D,  2D
  vector<unsigned int> regions_1D;
  vector<unsigned int> regions_2D;
	
  //  maps <ISE phis reg ID, region_elements_nD>
  map <unsigned int , vector<ISE_Element*> >  map_1D_region_elements;
  map <unsigned int , vector<ISE_Element*> >  map_2D_region_elements ;
	
  //map <unsigned int tiber_BC_region, vector<unsigned int> region_nodes )
  map <unsigned int , vector<unsigned int>  > map_BC_region_nodes;
	
	
	
	
};

#endif /*_READISEGRID_H_*/
