
# export TIBERCADROOT=/usr/local/tibercad-2.5.1
# export ARCH=x86_64-linux
# export LD_LIBRARY_PATH=$TIBERCADROOT/SDK/lib
# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TIBERCADROOT/SDK/$ARCH/lib
# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TIBERCADROOT/$ARCH/lib

# ln -s $TIBERCADROOT/SDK/$ARCH/bin/build_module

# run ./build_module

Module kmc 
{

  installpath = .

  
  sources = (KmcTUM.C, KmcInterface.C)

  compiler_flags = "-I/home/pecchia/projects "     
  # possibly need the library dependence 
   
}

