#$Id$
#

topdir := ../..

# we have to compile each module

subdirs := semiconductormodels
subdirs += tightbinding
subdirs += optics 
subdirs += schroedinger
subdirs += misc
#subdirs += phonondispersion

include $(topdir)/Make.common


include $(topdir)/Make.rules

