inputfile = Example_9.tib
outputdir = output

check = tmm_study_msh.dat : x Internal_Source_ElectricField Internal_Poynting Internal_Power Internal_Absorption 
check = tmm_study_msh.dat : ratio  kr  Emission_angle  Power_back  Power_front
