# $Id$

topdir := ../../../..

MODULE_NAME := exciton


include $(topdir)/Make.module


$(eval $(call MODULE, ExcitonTransport.C, ExcitonTransport.C))
$(eval $(call MODULE, ExcitonModel.C))


include $(topdir)/Make.rules
