Module vff
{
  sources = (Vff.cpp, VffModel.cpp, OptGpl.cpp, Keating.cpp)
  
  #installpath = @ARCH/modules/@MODULE

  keating user { sources = models/UserKeating.cpp }
  keating automatic { sources = models/AutomaticKeating.cpp  }

#  Dependency FADBAD++
#  {
#    includes = FADBAD++
#  }
}

