#ifndef _NEGF_H
#define _NEGF_H

//*************************************************************************** 
//*
//*  C++ bindings for LibNEGF 
//*
//*  Generated by bind_fortran (DO NOT EDIT MANUALLY)
//*
//***************************************************************************
//* Notes:
//*   o) these bindings need the "fortran.h" header file
//*   o) you should call only the f77_* functions from C++ in order to make
//*      sure, that your code does not depend on the naming convention of
//*      the different compilers (e.g. trailing underscores)
//***************************************************************************

#include "fortran.h"

// Some defintions for constants used by Uptight
const int NEGF_SC = 100;
const int NEGF_MC = 200;
const int NEGF_LC = 500;
const int NEGF_HSIZE = 4;
const char NEGF_PADCHAR = ' ';



extern "C" void negf_gethandlersize_ (f77_int&);

// Corresponding F77 arguments for f77_negf_gethandlersize:
// integer, intent(out) :: handlerSize
inline void f77_negf_gethandlersize (f77_int& handlerSize)
{
  negf_gethandlersize_ (handlerSize);
}


extern "C" void negf_init_session_ (f77_int*);

// Corresponding F77 arguments for f77_negf_init_session:
// integer, intent(out) :: handler(DAC_handlerSize)
inline void f77_negf_init_session (f77_int* handler)
{
  negf_init_session_ (handler);
}


extern "C" void negf_getversion_ (f77_int*);

// Corresponding F77 arguments for f77_negf_getversion:
// integer, intent(inout) :: handler(DAC_handlerSize)
inline void f77_negf_getversion (f77_int* handler)
{
  negf_getversion_ (handler);
}


extern "C" void negf_init_ (f77_int*);

// Corresponding F77 arguments for f77_negf_init:
// integer, intent(inout) :: handler(DAC_handlerSize)
inline void f77_negf_init (f77_int* handler)
{
  negf_init_ (handler);
}


extern "C" void negf_fillparameters_ (f77_int const*, f77_int const&);

// Corresponding F77 arguments for f77_negf_fillparameters:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: infile
inline void f77_negf_fillparameters (f77_int const* handler, f77_int const& 
    infile)
{
  negf_fillparameters_ (handler, infile);
}


extern "C" void negf_destruct_session_ (f77_int const*);

// Corresponding F77 arguments for f77_negf_destruct_session:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_negf_destruct_session (f77_int const* handler)
{
  negf_destruct_session_ (handler);
}


extern "C" void negf_destruct_libnegf_ (f77_int const*);

// Corresponding F77 arguments for f77_negf_destruct_libnegf:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_negf_destruct_libnegf (f77_int const* handler)
{
  negf_destruct_libnegf_ (handler);
}


extern "C" void negf_set_verbosity_ (f77_int const*, f77_int const&);

// Corresponding F77 arguments for f77_negf_set_verbosity:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: verbose_lev
inline void f77_negf_set_verbosity (f77_int const* handler, f77_int const& 
    verbose_lev)
{
  negf_set_verbosity_ (handler, verbose_lev);
}


extern "C" void negf_current_ (f77_int const*, f77_double&);

// Corresponding F77 arguments for f77_negf_current:
// integer, intent(in) :: handler(DAC_handlerSize)
// real(dp), intent(inout) :: current
inline void f77_negf_current (f77_int const* handler, f77_double& current)
{
  negf_current_ (handler, current);
}


extern "C" void negf_density_ (f77_int const*, f77_int const&, f77_double 
    const*);

// Corresponding F77 arguments for f77_negf_density:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: ndofs
// real(dp), intent(in) :: density(ndofs)
inline void f77_negf_density (f77_int const* handler, f77_int const& ndofs, 
    f77_double const* density)
{
  negf_density_ (handler, ndofs, density);
}


extern "C" void negf_set_iteration_ (f77_int const*, f77_int const&);

// Corresponding F77 arguments for f77_negf_set_iteration:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: iter
inline void f77_negf_set_iteration (f77_int const* handler, f77_int const& iter)
{
  negf_set_iteration_ (handler, iter);
}


extern "C" void negf_set_output_ (f77_int const*, f77_char const*);

// Corresponding F77 arguments for f77_negf_set_output:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(LST), intent(in) :: out_path(1)
inline void f77_negf_set_output (f77_int const* handler, f77_char const* 
    out_path)
{
  negf_set_output_ (handler, out_path);
}


extern "C" void negf_set_scratch_ (f77_int const*, f77_char const*);

// Corresponding F77 arguments for f77_negf_set_scratch:
// integer, intent(in) :: handler(DAC_handlerSize)
// character(LST), intent(in) :: scratch_path(1)
inline void f77_negf_set_scratch (f77_int const* handler, f77_char const* 
    scratch_path)
{
  negf_set_scratch_ (handler, scratch_path);
}


extern "C" void negf_set_outer_ (f77_int const*, f77_int const&);

// Corresponding F77 arguments for f77_negf_set_outer:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: outer
inline void f77_negf_set_outer (f77_int const* handler, f77_int const& outer)
{
  negf_set_outer_ (handler, outer);
}


extern "C" void negf_set_kpoint_ (f77_int const*, f77_int const&);

// Corresponding F77 arguments for f77_negf_set_kpoint:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: kpoint
inline void f77_negf_set_kpoint (f77_int const* handler, f77_int const& kpoint)
{
  negf_set_kpoint_ (handler, kpoint);
}


extern "C" void negf_set_reference_ (f77_int const*, f77_int const&);

// Corresponding F77 arguments for f77_negf_set_reference:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: minmax
inline void f77_negf_set_reference (f77_int const* handler, f77_int const& 
    minmax)
{
  negf_set_reference_ (handler, minmax);
}


extern "C" void negf_set_writeldos_ (f77_int const*, f77_int const&);

// Corresponding F77 arguments for f77_negf_set_writeldos:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: flag
inline void f77_negf_set_writeldos (f77_int const* handler, f77_int const& flag)
{
  negf_set_writeldos_ (handler, flag);
}


extern "C" void negf_write_partition_ (f77_int const*);

// Corresponding F77 arguments for f77_negf_write_partition:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_negf_write_partition (f77_int const* handler)
{
  negf_write_partition_ (handler);
}


#endif

