#ifndef _NEGF_H
#define _NEGF_H

//*************************************************************************** 
//*
//*  C++ bindings for LibNEGF 
//*
//*  Generated by bind_fortran (DO NOT EDIT MANUALLY)
//*
//***************************************************************************
//* Notes:
//*   o) these bindings need the "fortran.h" header file
//*   o) you should call only the f77_* functions from C++ in order to make
//*      sure, that your code does not depend on the naming convention of
//*      the different compilers (e.g. trailing underscores)
//***************************************************************************

#include "fortran.h"

// Some defintions for constants used by Uptight
const int NEGF_SC = 100;
const int NEGF_MC = 200;
const int NEGF_LC = 500;
const int NEGF_HSIZE = 4;
const char NEGF_PADCHAR = ' ';



extern "C" void negf_gethandlersize_ (f77_int&);

// Corresponding F77 arguments for f77_negf_gethandlersize:
// integer, intent(out) :: handlerSize
inline void f77_negf_gethandlersize (f77_int& handlerSize)
{
  negf_gethandlersize_ (handlerSize);
}


extern "C" void negf_init_session_ (f77_int*);

// Corresponding F77 arguments for f77_negf_init_session:
// integer, intent(out) :: handler(DAC_handlerSize)
inline void f77_negf_init_session (f77_int* handler)
{
  negf_init_session_ (handler);
}


extern "C" void negf_getversion_ (f77_int*);

// Corresponding F77 arguments for f77_negf_getversion:
// integer, intent(inout) :: handler(DAC_handlerSize)
inline void f77_negf_getversion (f77_int* handler)
{
  negf_getversion_ (handler);
}


extern "C" void negf_init_ (f77_int*);

// Corresponding F77 arguments for f77_negf_init:
// integer, intent(inout) :: handler(DAC_handlerSize)
inline void f77_negf_init (f77_int* handler)
{
  negf_init_ (handler);
}


extern "C" void negf_fillparameters_ (f77_int const*, f77_int const&);

// Corresponding F77 arguments for f77_negf_fillparameters:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: infile
inline void f77_negf_fillparameters (f77_int const* handler, f77_int const& 
    infile)
{
  negf_fillparameters_ (handler, infile);
}


extern "C" void negf_destruct_session_ (f77_int const*);

// Corresponding F77 arguments for f77_negf_destruct_session:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_negf_destruct_session (f77_int const* handler)
{
  negf_destruct_session_ (handler);
}


extern "C" void negf_destruct_libnegf_ (f77_int const*);

// Corresponding F77 arguments for f77_negf_destruct_libnegf:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_negf_destruct_libnegf (f77_int const* handler)
{
  negf_destruct_libnegf_ (handler);
}


extern "C" void negf_set_verbosity_ (f77_int const*, f77_int const&);

// Corresponding F77 arguments for f77_negf_set_verbosity:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: verbose_lev
inline void f77_negf_set_verbosity (f77_int const* handler, f77_int const& 
    verbose_lev)
{
  negf_set_verbosity_ (handler, verbose_lev);
}


#endif

