# $Id: Makefile 2399 2011-02-23 15:43:57Z maufder $

topdir := ../../../..

include $(topdir)/Make.common

target := modules

modules: module.conf
	@$(BUILDMODULE) module.conf

include $(topdir)/Make.rules
