Module elasticity
{

  sources = (Elasticity.cpp, ElasticityModel.cpp, ElasticityBoundaryModel.cpp)
  
  stiffness anisotropic { sources = models/AnisotropicStiffness.cpp }
  stiffness isotropic { sources = models/IsotropicStiffness.cpp }
  
  body_force constant { sources = models/ConstantBodyForce.cpp }
  body_force converse_piezo { sources = models/ConversePiezo.cpp }
  body_force lattice_mismatch { sources = models/LatticeMismatch.cpp }
  body_force thermal_stress { sources = models/ThermalStress.cpp }
  body_force built_in_strain { sources = models/BuiltInStrain.cpp }
  
  ebnd clamp { sources = models/Clamp.cpp }
  ebnd custom { sources = models/Custom.cpp }
  ebnd extended { sources = models/Extended.cpp }
  ebnd plane { sources = models/Plane.cpp }
  ebnd surface_force { sources = models/SurfaceForce.cpp }


}

