Module wateringress
{
  # install here (default is in the tibercad installation's
  # module directory
  #installpath = .

  # the sources for the main module library (the first one provides
  # the creatable object)
  sources = (WaterIngress.cpp, WIModel.cpp, WIBoundaryModel.cpp, WIUtils.cpp)

  # 'contact' is the keyword used to build the library.
  contact pressure  { sources = models/BCPressure.cpp }

}

