#!/bin/bash

if [ ! -e common.sh ]; then
  echo "need configuration file (common.sh)."
  exit 1
fi

. common.sh


echo "compiling GMSH version $GMSHVERSION in $BUILDDIR ..."


mkdir -p $BUILDDIR
if [ ! -d $BUILDDIR ]; then
  echo "directory $BUILDDIR does not exist."
  exit 1
fi

ARCHIVE=gmsh-${GMSHVERSION}-source.tgz

cd $BUILDDIR
if [ ! -e ${ARCHIVE} ]; then
  wget http://geuz.org/gmsh/src/${ARCHIVE}
fi

if [ ! -e ${ARCHIVE} ]; then
  echo "Could not download gmsh."
  exit 1
fi

if [ ! -e fltk-1.1.9-source.tar.bz2 ]; then
  wget http://ftp.rz.tu-bs.de/pub/mirror/ftp.easysw.com/ftp/pub/fltk/1.1.9/fltk-1.1.9-source.tar.bz2
fi
tar jxf fltk-1.1.9-source.tar.bz2
cd fltk-1.1.9
./configure --enable-localjpeg --enable-localzlib --enable-localpng --prefix=`pwd`
make
cd ..


tar zxf ${ARCHIVE}

cd gmsh-${GMSHVERSION}

export LDFLAGS="-Wl,-rpath,/usr/pack/gsl-1.6-ma/lib"


./configure --with-gsl-prefix=/usr/pack/gsl-1.6-ma --with-fltk-prefix=${BUILDDIR}/fltk-1.1.9 

make
make package-unix

cp -r gmsh-${GMSHVERSION} ${BUILDDIR}/../contrib
