# $Id$
#

topdir := ../../..

# we have to compile each module
subdirs += dssc common signals
subdirs += thermal drift-diffusion elasticity
subdirs += vff etb 
subdirs += dd_generic
#subdirs += interpolation
subdirs += quantumespresso
subdirs += data_importer
subdirs += imagereader
subdirs += polarizationgrid 
#subdirs += negf 
#subdirs += maxwell maxwellabsorption 

include $(topdir)/Make.common

#modules: all

include $(topdir)/Make.rules

