# $Id$
#

topdir := ../../..

# we have to compile each module
subdirs := excitons dssc common boltzmann
subdirs += thermal drift-diffusion elasticity
subdirs += vff negf etb 
subdirs += polarizationgrid 
subdirs += imagereader
subdirs += drift-diffusion_hostguest
subdirs += excitons_ST
subdirs += dd_generic
#subdirs += excitons2
#subdirs += maxwell maxwellabsorption 

include $(topdir)/Make.common

#modules: all

include $(topdir)/Make.rules

