Module negf
{

  sources = (Negf.cpp, NegfModel.cpp)
  
  

  Dependency libnegf
  {
    includes = libnegf
    libraries = negf             # -> -lmylib
    libpath = libnegf           # -> -L/path/to/lib
    install = true
    #installpath = @ARCH/modules/@MODULE
  }

  
  #hamiltonian single_band { sources = models/SingleBand.cpp }
  hamiltonian etb { sources = models/EtbModel.cpp }
  hamiltonian efa { sources = models/EfaModel.cpp }


}

