#!/bin/bash

if test -e site_config.sh
then
  . site_config.sh
fi




if test -e ${MPIEXEC}
then 
  MPIBINDIR=$(dirname $MPIEXEC)

  export CC=${MPIBINDIR}/mpicc
  export CXX=${MPIBINDIR}/mpicxx
  export FC=${MPIBINDIR}/mpifort
  export F77=${MPIBINDIR}/mpifort

else
  MAKE_MPI=1
fi

export CC CXX FC F77 MPIEXEC
export FFLAGS FCFLAGS CXXFLAGS CFLAGS

#export LINKONLY=1

./configure

if test "${MAKE_MPI}x" != "x"
then 
  echo "MPI not yet present, I will now compile MPI"
  echo "Re-run build_all after this has finished"
  #./build_mpich
#  ./build_mpi

  echo "Finished installing MPI. Now re-run build_all."
else
  if test ! -e "${SDKDIR}/x86_64-linux/lib/libpetsc_real.so"
  then
    echo "Build PETSc"
#  ./build_petsc
  fi
  if test ! -e "${SDKDIR}/x86_64-linux/lib/libslepc_complex.so"
  then
    echo "Build SLEPc"
#  ./build_slepc
  fi
  if test ! -e "${SDKDIR}/x86_64-linux/lib/libboost_system-mt-x64.so"
  then
    echo "Build BOOST"
#  ./build_boost
  fi
  if test ! -e "${SDKDIR}/x86_64-linux/lib/libmesh_devel.so"
  then
    echo "Build BOOST"
#  ./build_libmesh
  fi

  ./build_tibercad
fi

