#!/bin/bash
 

if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh

MKLOPTS=
if [ "$MKL" = y ]; then
  MKLOPTS="--with-mkl=${MKLDIR}"
fi

CUDAOPTS=
if [ "${CUDADIR}x" != "x" ]; then
  CUDAOPTS="--with-cuda=${CUDADIR}"
fi


echo "Compiling TiberCAD ..."

cd ../

ARCH=`uname -m`
if [ $ARCH == "i686" ]
then
  sepparch=i686-debian-linux4.0
else
  sepparch=amd64-debian-linux5.0
  FCFLAGS="-fPIC ${FCFLAGS}"
fi
#if [ "$target_os" == "win32" ]; then
#  cp contrib/dlfcn-win32-r19/dlfcn.h include/base/io/dlfcn.h
#  cp contrib/dlfcn-win32-r19/dlfcn.c src/base/io/dlfcn.c
#fi

#export LD_RUN_PATH=`pwd`/SDK/${TCHOST}/lib
#export LD_LIBRARY_PATH=`pwd`/SDK/${TCHOST}/lib

threadlib="intel"
if [ "$GNUFORTRAN" = "1" ]; then
  threadlib="gnu"
fi

echo ${BUILDDIR}/libmesh-${LIBMESHVERSION}-${TCHOST}

export CXXFLAGS="$CXXFLAGS -fopenmp"
export LDFLAGS="$LDFLAGS -fopenmp"

./configure \
  --with-petsc-prefix=${BUILDDIR}/petsc-${PETSCVERSION}${PETSCPATCHLEVEL} \
  --with-petsc-arch=${TCHOST} \
  --with-mpiexec=${MPIEXEC} \
  --with-thread-library=${threadlib} \
  --with-slepc-prefix=${BUILDDIR}/slepc-${SLEPCVERSION}${SLEPCPATCHLEVEL} \
  $MKLOPTS $CUDAOPTS \
  --enable-uptight \
  --with-libmesh-prefix=${BUILDDIR}/libmesh-${LIBMESHVERSION}-${TCHOST} \
  --with-libmesh-petsc-libdir=${SDKDIR}/${TCHOST}/lib \
  --with-boost-prefix=${SDKDIR} --with-boost-libdir=${TOPDIR}/${TCHOST}/lib \
  --host=$HOST --build=$BUILD


make -j 4 METHOD=opt

if test "${MPIDIR}" != "${SDKDIR}"
then
  mkdir -p SDK/bin
  cp ${MPIEXEC} SDK/bin
fi
