#!/bin/bash

if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh

VERSION=4.1.4
ARCHIVE=openmpi-${VERSION}.tar.bz2

echo "Compiling openmpi libraries"


mkdir -p $BUILDDIR
if [ ! -d $BUILDDIR ]; then
  echo "Directory $BUILDDIR does not exist."
  exit 1
fi



cd $BUILDDIR
if [ ! -e ${ARCHIVE} ]; then
  wget --no-check-certificate  https://download.open-mpi.org/release/open-mpi/v4.1/${ARCHIVE}
fi

if [ ! -e ${ARCHIVE} ]; then
  echo "Could not download ${ARCHIVE}."
  exit  
fi

if [ ! -d openmpi-${VERSION} ]; then
  tar jxf ${ARCHIVE}
fi




cd openmpi-${VERSION}

./configure --prefix=${SDKDIR} --exec-prefix=${SDKDIR}/${TCHOST} --enable-shared=yes \
            --enable-static=no --host=$HOST --build=$BUILD \
            --with-pmix

make
make install

