#!/usr/bin/python

configure_options = [
  '--known-level1-dcache-size=32768',
  '--known-level1-dcache-linesize=32',
  '--known-level1-dcache-assoc=2',
  '--known-memcmp-ok=1',
 '--known-endian=little',
  '--known-sizeof-char=1',
  '--known-sizeof-void-p=4',
  '--known-sizeof-short=2',
  '--known-sizeof-int=4',
  '--known-sizeof-long=4',
  '--known-sizeof-long-long=8',
  '--known-sizeof-float=4',
  '--known-sizeof-double=8',
  '--known-sizeof-size_t=4',
  '--known-bits-per-byte=8',
  '--CFLAGS= -fexceptions',
  '--CXXFLAGS=',
  '--FFLAGS= -fexceptions',
  '--LDFLAGS=',
  '--bits-per-byte=8',
  '--download-f-blas-lapack=1',
  '--sizeof-char=1',
  '--sizeof-double=8',
  '--sizeof-float=4',
  '--sizeof-int=4',
  '--sizeof-long-long=8',
  '--sizeof-long=4',
  '--sizeof-short=2',
  '--sizeof-size-t=4',
  '--sizeof-void-p=4',
  '--with-ar=i686-w64-mingw32-ar',
  '--with-batch=1',
  '--with-cc=i686-w64-mingw32-gcc',
  '--with-clanguage=C++',
  '--with-cpp=i686-w64-mingw32-cpp',
  '--with-cxx=i686-w64-mingw32-g++',
  '--with-debugging=0',
  '--with-endian=little',
  '--with-fc=i686-w64-mingw32-gfortran',
  '--with-host-os=mingw32',
  '--with-host-vendor=w64',
  '--with-matlab=0',
  '--with-memcmp-ok',
  '--with-mpi=0',
  '--with-ranlib=i686-w64-mingw32-ranlib',
  '--with-scalar-type=real',
  '--with-shared-ld=i686-w64-mingw32-ld',
  '--with-shared-libraries=0',
  '--with-x=0',
  'PETSC_ARCH=i686-w64-mingw32',
]
if __name__ == '__main__':
  import os
  import sys
  sys.path.insert(0, os.path.abspath('config'))
  import configure
  configure.petsc_configure(configure_options)
