Module elasticity
{

  sources = (Elasticity.C, ElasticityModel.C, ElasticityBoundaryModel.C)
  
  stiffness anisotropic { sources = models/AnisotropicStiffness.C }
  stiffness isotropic { sources = models/IsotropicStiffness.C }
  
  body_force constant { sources = models/ConstantBodyForce.C }
  body_force converse_piezo { sources = models/ConversePiezo.C }
  body_force lattice_mismatch { sources = models/LatticeMismatch.C }
  body_force thermal_stress { sources = models/ThermalStress.C }
  body_force built_in_strain { sources = models/BuiltInStrain.C }
  
  ebnd clamp { sources = models/Clamp.C }
  ebnd custom { sources = models/Custom.C }
  ebnd extended { sources = models/Extended.C }
  ebnd plane { sources = models/Plane.C }
  ebnd surface_force { sources = models/SurfaceForce.C }


}

