# $Id: Makefile 2399 2011-02-23 15:43:57Z maufder $

topdir := ../../../..

include $(topdir)/Make.module

MODULE_NAME := maxwellabsorption
$(eval $(call MODULE, MaxwellAbsorption.C))

include $(topdir)/Make.rules
