Module data_import
{
  # install here (default is in the tibercad installation's
  # module directory
  # installpath = .

  # the sources for the main module library (the first one provides
  # the creatable object)
  sources = (DataImporter.C)

#  Dependency libhdf5
#  {
#    includes = /home/mermes/software/hdf5/include
#    libraries = (hdf5,hdf5_hl)
#    libpath = /home/mermes/software/hdf5/lib
#    install = false
#  }
}

