
#ifndef _MBSELFCONSISTENT_H_
#define _MBSELFCONSISTENT_H_
#include "newmat.h"
#include "newmatap.h"

#include "SelfconsistentSolver.h"

//! Based on the paper Journal of Chemical Physics v.108 p.4426
class ModifiedBroyden:  public SelfconsistentSolver
{

 public:

  //! The constructor
  ModifiedBroyden(void) {};
  
  //! The destructor
  virtual ~ModifiedBroyden(void) {};

  //! Create a Sweep object
  static ModifiedBroyden* create(void);


 protected:

  /*! \copydoc SimulationInterface::do_init() */
  virtual void do_init(void);


  /*! \copydoc SimulationInterface::do_solve() */
  virtual void do_solve(void);

  
  /*! \copydoc SimulationInterface::parse_options() */
  virtual void parse_options(void);
  
  

  
 private:

  
  
  //! Initializes solution
  virtual void init_X(void);



 
  //!calculates \f$ X_2 \f$  
  /*!
    \f$ X_2 = X_1 - \alpha F(X_1) \f$ 
  */
  void calculate_new_first_iteraion_solution(void);

  

  //! \f$ F(x) = x - x' \f$  */
  void evaluate_and_save_F(void);


  //! \f$ \kappa_{in} = \kappa_{ni} =  F(x_n)^T \cdot F(x_i) \f$ */
  void calculate_kappa_matrix(void); 


  //! Modified Broden step: \f$ x_{n+1} = x_{n} + \alpha * (p_{nn} - 1)F(x_n) + \alpha \sum_{i=2}^{n-1} p_{ni}F(X_i) \f$ */
  void calculate_new_solution();

  //! Calculation of \f$ \kappa \f$ and \f$ \mu \f$. I think that in the paper there is a missprint (see bellow) 
  /*! 
    \f$ 

  \mu_{i,n-1} = \mu_{n-1,i} = 0 (i = 1,...,n-2), \\
  \\   
  \mbox{in the paper:}\mu_{n-1, n-1} = (\kappa_{nn} - 2\kappa_{n,n-1} + k_{n-1, n -1 })^{-1/2} \\
  \\  
  \mbox{I think:}\mu_{n-1, n-1} = (\kappa_{nn} - 2\kappa_{n,n-1} + k_{n-1, n -1 })^{-1/4}  \\
  \\
  w_{ij} = \omega_{i}\delta_{ij}.

   \f$ 
  */
  void calculate_mu_and_w_diag(void);

  //!calculation of \f$ \tilde a \f$ (see below)
  /*!
    \f$
    \tilde a_{n-1,i} = \lambda_i (i = 1,...,n-2)
    \tilde a_{n-1,n-1} = 1
    \f$
  */
  void calculate_tilde_a(void);

  //!recalculation of \f$ \tilde a \f$ (see below)
  /*!
    \f$
    \tilde a_{n-1, i} = \mu_{n-1, n-1}(\lambda_i - \tilde a_{n-1,i})  (i = 1,...,n-2)
    \f$
   */
  void update_tilde_a(void);

  
  //! Calculate \f$ \lambda \f$: \f$ \lambda_i = \mu_{ii} (\kappa_{n,i+1} -\kappa_{ni} ) (i = 1,...,n-1) \f$
  void calculate_lambda(void);

  
  //!calculate \f$ a \f$ matrix  \f$ a_{ij} = a_{ji} = w_{ii} w_{jj} \tilde a_{ij} (i \ge j = 1,...,n-1) \f$
  void calculate_a(void);


  
  //!calculate \f$ {\mathbf \beta} \f$  matrix  \f$ {\mathbf \beta} = (\omega_0^2 I + {\bf a})^{-1}  \f$
  void calcvulate_beta_matrix(void);

  //!calculation of \f$ {\mathbf \zeta}^{(n)} \f$ (in the paper the formula is a bit unclear, see below)
  /*!
    The paper says:
    \f$ {\mathbf \zeta}^{(n)} = {\bf \beta} \cdot {\bf w} \cdot {\bf \mu} + \omega_0^2 {\bf \beta'} \cdot {\bf \zeta}^{(n-1)} \f$
    \\
    But \f$ {\bf \beta} \cdot {\bf w} \cdot {\bf \mu} \f$ is \f$ (n-1) \times (n-1) \f$ matrix and 
    \f$ {\bf \beta'} \cdot {\bf \zeta}^{(n-1)} \f$ is \f$ (n-1) \times (n-2) \f$ matrix. 
    So, I add  to  the \f$ (n-1) \times (n-2) \f$ submatrix of \f$ {\bf \beta} \cdot {\bf w} \cdot {\bf \mu} \f$
  */
  void calculate_zeta_matrix(void);

  
  //! calculation of \f${\mathbf \eta  } \f$: \f$ {\bf \eta } = {\bf w} \cdot {\bf \zeta}^{(n)} \cdot {\bf \lambda} \f$
  
  void calculate_eta_vector(void);

  //! calculation of \f$ p \f$ matrix:   \f$ p_{ni} = \eta_{ni} - \sum_{j=1}^{n-1} \eta_j p_{ji} (i = 2,...,n)\f$
  void calculate_p_matrix(void);
  

  //! Definition of \f$ \omega_i \f$ weights (see below)
  /*!
    \f$
    \omega_i = \left\{ \begin{array}{rcl}
                          0, i &=& 1, \ldots, n-m \\ 
                          1, i &=& n-m+1,\ldots ,n
                       \end{array}
                   \right. 
            
    \f$
    where \f$ m \f$ is the history length.
  */
  void update_omega_vector(void);
  
  //! estimates error
  double estimate_step();


  

  NEWMAT::SymmetricMatrix _kappa, _a, _beta;
  
  NEWMAT::DiagonalMatrix  _w, _mu; 

  NEWMAT::Matrix    _p, _zeta, _a_tilde;

  NEWMAT::ColumnVector  _lambda, _omega, _eta;


  //! \f$  F = X - X'  \f$
  //std::map<unsigned int, std::vector <double> > _F;
  std::map<unsigned int,  NumericVector<double>* > _F;
  
  //!adds vector to _F map
  NumericVector< Number >& add_F_vector(unsigned int number);


  //! clears memory in _F map
  void clear_F(void);



  //! current solution 
  AutoPtr <  NumericVector<double> > _X;
 


  //! coorection generated by the method
   AutoPtr <  NumericVector<double> > _X_correction;

  //! current iteration number
  unsigned int  _it_number;

 
  //! size of _X
  unsigned int _vector_size;


  //!how many solutions to consider
  unsigned int _number_of_x_to_use;

  //! \f$ \omega_0  \f$ from the paper 
  double _omega_0;

  //! \f$ \alpha \f$ from the paper (relaxation parameter)
  double _alpha; 


  //!if the solution is converged, i.e. \f$ \frac{(F^T \cdot F)^{1/2}} { {(X^T \cdot X)^{1/2} } } < \varepsilon \f$
  bool _converged;

  //!relative error \f$ \frac{(F^T \cdot F)^{1/2}} {{(X^T \cdot X)^{1/2}}}  \f$
  double _rel_error;

 


}; 


inline 
ModifiedBroyden* ModifiedBroyden::create(void)
{
  return new ModifiedBroyden();
}

inline 
NumericVector< Number >& ModifiedBroyden::add_F_vector(unsigned int number)
{
  NumericVector<Number>* buf = NumericVector<Number>::build().release();

  _F.insert (std::make_pair (number, buf));

  return *buf;
}


inline 
void  ModifiedBroyden::clear_F(void)
{
  std::map<unsigned int,  NumericVector<double>* >::iterator it  =  _F.begin();
  for ( ; it != _F.end(); ++it)
    delete it->second;
  

  _F.clear();
}

#endif //_MBSELFCONSISTENT_H_
