# $Id$

topdir := ../../../..

# subdirectories
subdirs		:= 


include $(topdir)/Make.module


$(eval $(call MODULE, DSSC.C, DSSCContact.C))
$(eval $(call SUBMODEL, DSSCModel.C))


include $(topdir)/Make.rules
