Module pvmodule
{
  # install here (default is in the tibercad installation's
  # module directory
  #installpath = .

  # the sources for the main module library (the first one provides
  # the creatable object)
  #sources = (PVModule.C, PVModuleModel.C, PVBoundaryModel.C)
  sources = (PVModule.C)

#  active_area { sources = models/ElementaryCell.C }

  # 'contact' is the keyword used to build the library.
  # (It does not appear in the input file)
#  contact { sources = models/VoltageControl.C }

}

