; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "tiberCAD"
#define MyAppPublisher "TiberLAB s.r.l"
#define MyAppURL "http://www.tiberlab.com/"
#define MyAppExeName "tibercad.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{2F49A58A-88A6-11E0-B49B-0021865288C1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\TiberLAB\tiberCAD
DefaultGroupName=TiberLAB\tiberCAD
AllowNoIcons=yes
LicenseFile={#MySrcPath}\Copyright.txt
InfoAfterFile={#MySrcPath}\Readme.txt
OutputDir={#MySrcPath}\..
OutputBaseFilename={#MyAppName}-{#MyAppVersion}-{#MyArch}_setup
;SetupIconFile={#MySrcPath}\tibercad.ico
Compression=lzma
SolidCompression=yes
ChangesAssociations=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "{#MySrcPath}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
;Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Dirs]
Name: "{app}\license"

[Registry]
Root: HKCR; Subkey: ".tib"; ValueType: string; ValueName: ""; ValueData: "TiberLABtiberCAD"; Flags: uninsdeletevalue
Root: HKCR; Subkey: "TiberLABtiberCAD"; ValueType: string; ValueName: ""; ValueData: "tiberCAD input file"; Flags: uninsdeletekey
Root: HKCR; Subkey: "TiberLABtiberCAD\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\tiberCAD.exe,0" 
Root: HKCR; Subkey: "TiberLABtiberCAD\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\tiberCAD.exe"" ""%1"""
Root: HKCR; Subkey: ".geo"; ValueType: string; ValueName: ""; ValueData: "TiberLABGMSH"; Flags: uninsdeletevalue
Root: HKCR; Subkey: "TiberLABGMSH"; ValueType: string; ValueName: ""; ValueData: "GMSH script"; Flags: uninsdeletekey
Root: HKCR; Subkey: "TiberLABGMSH\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\tools\gmsh\gmsh.exe,0" 
Root: HKCR; Subkey: "TiberLABGMSH\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\tools\gmsh\gmsh.exe"" ""%1"""
