#ifndef _DFTBP_H
#define _DFTBP_H

//*************************************************************************** 
//*
//*  C++ bindings for DFTB+
//*
//*  Generated by bind_fortran (DO NOT EDIT MANUALLY)
//*
//***************************************************************************
//* Notes:
//*   o) these bindings need the "fortran.h" header file
//*   o) you should call only the f77_* functions from C++ in order to make
//*      sure, that your code does not depend on the naming convention of
//*      the different compilers (e.g. trailing underscores)
//***************************************************************************

#include "fortran.h"

// Some defintions for constants used by DFTB+
const int DFTBP_MC = 50;
const int DFTBP_LC = 200;
const int DFTBP_HSIZE = 4;
const char DFTBP_PADCHAR = ' ';



extern "C" void dftbp_gethandlersize_ (f77_int&);

// Corresponding F77 arguments for f77_dftbp_gethandlersize:
// integer, intent(out) :: handlerSize
inline void f77_dftbp_gethandlersize (f77_int& handlerSize)
{
  dftbp_gethandlersize_ (handlerSize);
}


extern "C" void dftbp_init_ (f77_int*);

// Corresponding F77 arguments for f77_dftbp_init:
// integer, intent(out) :: handler(DAC_handlerSize)
inline void f77_dftbp_init (f77_int* handler)
{
  dftbp_init_ (handler);
}


extern "C" void dftbp_destruct_ (f77_int*);

// Corresponding F77 arguments for f77_dftbp_destruct:
// integer, intent(inout) :: handler(DAC_handlerSize)
inline void f77_dftbp_destruct (f77_int* handler)
{
  dftbp_destruct_ (handler);
}


extern "C" void dftbp_fillbasicparameters_ (f77_int const*, f77_int const&, 
    f77_int const&, f77_char const*, f77_int const*, f77_int const&, f77_double 
    const&);

// Corresponding F77 arguments for f77_dftbp_fillbasicparameters:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nAtom
// integer, intent(in) :: nType
// character(mc), intent(in) :: speciesNames(nType)
// integer, intent(in) :: species(nAtom)
// integer, intent(in) :: iPeriodic
// real(dp), intent(in) :: eTemp
inline void f77_dftbp_fillbasicparameters (f77_int const* handler, f77_int 
    const& nAtom, f77_int const& nType, f77_char const* speciesNames, f77_int 
    const* species, f77_int const& iPeriodic, f77_double const& eTemp)
{
  dftbp_fillbasicparameters_ (handler, nAtom, nType, speciesNames, species, 
      iPeriodic, eTemp);
}


extern "C" void dftbp_addskdatafromfile_ (f77_int const*, f77_int const&, 
    f77_char const*, f77_int const*, f77_int const&, f77_int const&);

// Corresponding F77 arguments for f77_dftbp_addskdatafromfile:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nType
// character(lc), intent(in) :: skNames(nType, nType)
// integer, intent(in) :: mAngs(nType)
// integer, intent(in) :: orbResolved
// integer, intent(in) :: skInterp
inline void f77_dftbp_addskdatafromfile (f77_int const* handler, f77_int const& 
    nType, f77_char const* skNames, f77_int const* mAngs, f77_int const& 
    orbResolved, f77_int const& skInterp)
{
  dftbp_addskdatafromfile_ (handler, nType, skNames, mAngs, orbResolved, 
      skInterp);
}


extern "C" void dftbp_gethubbards_ (f77_int const*, f77_int const&, f77_int 
    const&, f77_double*);

// Corresponding F77 arguments for f77_dftbp_gethubbards:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nType
// integer, intent(in) :: mShell
// real(dp), intent(out) :: hubbU(mShell, nType)
inline void f77_dftbp_gethubbards (f77_int const* handler, f77_int const& 
    nType, f77_int const& mShell, f77_double* hubbU)
{
  dftbp_gethubbards_ (handler, nType, mShell, hubbU);
}


extern "C" void dftbp_addlattice_ (f77_int const*, f77_double const*);

// Corresponding F77 arguments for f77_dftbp_addlattice:
// integer, intent(in) :: handler(DAC_handlerSize)
// real(dp), intent(in) :: latVecs(3, 3)
inline void f77_dftbp_addlattice (f77_int const* handler, f77_double const* 
    latVecs)
{
  dftbp_addlattice_ (handler, latVecs);
}


extern "C" void dftbp_addkpoints_ (f77_int const*, f77_int const&, f77_double 
    const*, f77_double const*);

// Corresponding F77 arguments for f77_dftbp_addkpoints:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nKPoint
// real(dp), intent(in) :: kPoints(3, nKPoint)
// real(dp), intent(in) :: kWeights(nKPoint)
inline void f77_dftbp_addkpoints (f77_int const* handler, f77_int const& 
    nKPoint, f77_double const* kPoints, f77_double const* kWeights)
{
  dftbp_addkpoints_ (handler, nKPoint, kPoints, kWeights);
}


extern "C" void dftbp_addsupersampling_ (f77_int const*, f77_double const*, 
    f77_double const*, f77_int const&);

// Corresponding F77 arguments for f77_dftbp_addsupersampling:
// integer, intent(in) :: handler(DAC_handlerSize)
// real(dp), intent(in) :: coeffs(3, 3)
// real(dp), intent(in) :: shifts(3)
// integer, intent(in) :: noinv
inline void f77_dftbp_addsupersampling (f77_int const* handler, f77_double 
    const* coeffs, f77_double const* shifts, f77_int const& noinv)
{
  dftbp_addsupersampling_ (handler, coeffs, shifts, noinv);
}


extern "C" void dftbp_initdftb_ (f77_int const*);

// Corresponding F77 arguments for f77_dftbp_initdftb:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_dftbp_initdftb (f77_int const* handler)
{
  dftbp_initdftb_ (handler);
}


extern "C" void dftbp_destructdftb_ (f77_int const*);

// Corresponding F77 arguments for f77_dftbp_destructdftb:
// integer, intent(in) :: handler(DAC_handlerSize)
inline void f77_dftbp_destructdftb (f77_int const* handler)
{
  dftbp_destructdftb_ (handler);
}


extern "C" void dftbp_updatecoords_ (f77_int const*, f77_int const&, f77_double 
    const*);

// Corresponding F77 arguments for f77_dftbp_updatecoords:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nAtom
// real(dp), intent(in) :: newCoords(3, nAtom)
inline void f77_dftbp_updatecoords (f77_int const* handler, f77_int const& 
    nAtom, f77_double const* newCoords)
{
  dftbp_updatecoords_ (handler, nAtom, newCoords);
}


extern "C" void dftbp_setexternalshift_ (f77_int const*, f77_int const&, 
    f77_double const*);

// Corresponding F77 arguments for f77_dftbp_setexternalshift:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nAtom
// real(dp), intent(in) :: shift(nAtom)
inline void f77_dftbp_setexternalshift (f77_int const* handler, f77_int const& 
    nAtom, f77_double const* shift)
{
  dftbp_setexternalshift_ (handler, nAtom, shift);
}


extern "C" void dftbp_gettotalenergy_ (f77_int const*, f77_double&);

// Corresponding F77 arguments for f77_dftbp_gettotalenergy:
// integer, intent(in) :: handler(DAC_handlerSize)
// real(dp), intent(out) :: energy
inline void f77_dftbp_gettotalenergy (f77_int const* handler, f77_double& 
    energy)
{
  dftbp_gettotalenergy_ (handler, energy);
}


extern "C" void dftbp_getchargesperatom_ (f77_int const*, f77_int const&, 
    f77_double*);

// Corresponding F77 arguments for f77_dftbp_getchargesperatom:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nAtom
// real(dp), intent(out) :: charges(nAtom)
inline void f77_dftbp_getchargesperatom (f77_int const* handler, f77_int const& 
    nAtom, f77_double* charges)
{
  dftbp_getchargesperatom_ (handler, nAtom, charges);
}


extern "C" void dftbp_getnetchargesperatom_ (f77_int const*, f77_int const&, 
    f77_double*);

// Corresponding F77 arguments for f77_dftbp_getnetchargesperatom:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nAtom
// real(dp), intent(out) :: charges(nAtom)
inline void f77_dftbp_getnetchargesperatom (f77_int const* handler, f77_int 
    const& nAtom, f77_double* charges)
{
  dftbp_getnetchargesperatom_ (handler, nAtom, charges);
}


extern "C" void dftbp_recreatecsrbuffer_ (f77_int const*, f77_int&, f77_int&, 
    f77_int&, f77_int&);

// Corresponding F77 arguments for f77_dftbp_recreatecsrbuffer:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(out) :: nRow
// integer, intent(out) :: nCol
// integer, intent(out) :: nVal
// integer, intent(out) :: isReal
inline void f77_dftbp_recreatecsrbuffer (f77_int const* handler, f77_int& nRow, 
    f77_int& nCol, f77_int& nVal, f77_int& isReal)
{
  dftbp_recreatecsrbuffer_ (handler, nRow, nCol, nVal, isReal);
}


extern "C" void dftbp_getrcsrhamiltonian_ (f77_int const*, f77_int const&, 
    f77_int const&, f77_int*, f77_int*, f77_double*);

// Corresponding F77 arguments for f77_dftbp_getrcsrhamiltonian:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nRow1
// integer, intent(in) :: nVal
// integer, intent(out) :: colInd(nVal)
// integer, intent(out) :: rowPtr(nRow1)
// real(dp), intent(out) :: val(nVal)
inline void f77_dftbp_getrcsrhamiltonian (f77_int const* handler, f77_int 
    const& nRow1, f77_int const& nVal, f77_int* colInd, f77_int* rowPtr, 
    f77_double* val)
{
  dftbp_getrcsrhamiltonian_ (handler, nRow1, nVal, colInd, rowPtr, val);
}


extern "C" void dftbp_getzcsrhamiltonian_ (f77_int const*, f77_double const*, 
    f77_int const&, f77_int const&, f77_int*, f77_int*, f77_double*);

// Corresponding F77 arguments for f77_dftbp_getzcsrhamiltonian:
// integer, intent(in) :: handler(DAC_handlerSize)
// real(dp), intent(in) :: kPoint(3)
// integer, intent(in) :: nRow1
// integer, intent(in) :: nVal
// integer, intent(out) :: colInd(nVal)
// integer, intent(out) :: rowPtr(nRow1)
// complex(dp), intent(out) :: val(nVal)
inline void f77_dftbp_getzcsrhamiltonian (f77_int const* handler, f77_double 
    const* kPoint, f77_int const& nRow1, f77_int const& nVal, f77_int* colInd, 
    f77_int* rowPtr, f77_double* val)
{
  dftbp_getzcsrhamiltonian_ (handler, kPoint, nRow1, nVal, colInd, rowPtr, val);
}


extern "C" void dftbp_getrcsroverlap_ (f77_int const*, f77_int const&, f77_int 
    const&, f77_int*, f77_int*, f77_double*);

// Corresponding F77 arguments for f77_dftbp_getrcsroverlap:
// integer, intent(in) :: handler(DAC_handlerSize)
// integer, intent(in) :: nRow1
// integer, intent(in) :: nVal
// integer, intent(out) :: colInd(nVal)
// integer, intent(out) :: rowPtr(nRow1)
// real(dp), intent(out) :: val(nVal)
inline void f77_dftbp_getrcsroverlap (f77_int const* handler, f77_int const& 
    nRow1, f77_int const& nVal, f77_int* colInd, f77_int* rowPtr, f77_double* 
    val)
{
  dftbp_getrcsroverlap_ (handler, nRow1, nVal, colInd, rowPtr, val);
}


extern "C" void dftbp_getzcsroverlap_ (f77_int const*, f77_double const*, 
    f77_int const&, f77_int const&, f77_int*, f77_int*, f77_double*);

// Corresponding F77 arguments for f77_dftbp_getzcsroverlap:
// integer, intent(in) :: handler(DAC_handlerSize)
// real(dp), intent(in) :: kPoint(3)
// integer, intent(in) :: nRow1
// integer, intent(in) :: nVal
// integer, intent(out) :: colInd(nVal)
// integer, intent(out) :: rowPtr(nRow1)
// complex(dp), intent(out) :: val(nVal)
inline void f77_dftbp_getzcsroverlap (f77_int const* handler, f77_double const* 
    kPoint, f77_int const& nRow1, f77_int const& nVal, f77_int* colInd, 
    f77_int* rowPtr, f77_double* val)
{
  dftbp_getzcsroverlap_ (handler, kPoint, nRow1, nVal, colInd, rowPtr, val);
}


#endif

