Module tmm
{
  sources = (Tmm.C, TmmBulkModel.C, TmmBoundaryModel.C, TmmDipoleSource.C,matrix2by2.C)
  tmm_bnd mirror { sources = models/Mirror.C }
  tmm_bnd incident_wave { sources = models/Incident_wave.C }
  tmm_bnd dipole_source { sources = models/Dipole_source.C }

  bulk_model Incoherency{ sources = models/IncoherentModel.C }
  
  dipole_source radiative_recombination{ sources = models/OpticalRecombination.C }
}
