Module tmm
{
  sources = (Tmm.C, TmmBulkModel.C, TmmBoundaryModel.C)
  tmm_bnd mirror { sources = models/Mirror.C }
  tmm_bnd incident_wave { sources = models/Incident_wave.C }
  bulk_model Incoherency{ sources = models/IncoherentModel.C }

  
}
