Module empirical_tb 
{

  sources = (EmpiricalTightBinding.cpp)
  
  createable = ETB 
  

  Dependency libuptight
  {
    includes = libuptight
    libraries = uptight             # -> -lmylib
    libpath = libuptight           # -> -L/path/to/lib
    install = true
    #installpath = @ARCH/modules/@MODULE
  }

  
}

