Module vff
{
  sources = (Vff.C, VffModel.C, OptGpl.C, Keating.C)
  
  #installpath = @ARCH/modules/@MODULE

  keating user { sources = models/UserKeating.C }
  keating automatic { sources = models/AutomaticKeating.C  }
}

