Compiler
{

  path = @ROOT/SDK/@ARCH/bin
  linker_flags = "-pthread -shared -Wl,-rpath,'$ORIGIN' -Wl,-rpath,'$ORIGIN/../lib'"

  C++
  {
    executable = g++
    compiler_flags = "-g -O3 -std=gnu++0x -pthread -fPIC -c"
    # -fvisibility=hidden
  }

  C
  {
    executable = gcc
  }

  Fortran
  {
    executable = gfortran
  }
}

Library tibercad
{
  includes = (
    tibercad/base/atomistic,
    tibercad/base/common,
    tibercad/base/database,
    tibercad/base/io,
    tibercad/base/math,
    tibercad/base/simulations,
    tibercad/pmi,
    tibercad/core/models,
    tibercad/core/embracing,
    tibercad/core/solver-interfaces,
    tibercad/core/solver-interfaces/petsc,
    tibercad/core/optics,
    tibercad/core/kintegrations,
    tibercad/core/eigenvalue,
    tibercad/utils/Tensor,
    tibercad/utils/SLEPC,
    tibercad/@ARCH
  )
  libpath = @ARCH/lib
  linker_flags = -ltibercad
}


Library boost
{
  #includes = @ROOT/SDK/include
}


Library libmesh
{
  includes = (libmesh/base, libmesh/error_estimation,
              libmesh/geom, libmesh/numerics, libmesh/partitioning,
              libmesh/solvers, libmesh/utils, libmesh/enums,
              libmesh/fe, libmesh/mesh, libmesh/parallel,
              libmesh/quadrature, libmesh/systems, libmesh/@ARCH)
  linker_flags = -lmesh
}


Library petsc
{ 
  includes = (petsc-3.0.0-p12, petsc-3.0.0-p12/mpiuni, petsc-3.0.0-p12/@ARCH)
  linker_flags = -lpetsc_real
}

Library slepc
{
  includes = (slepc-3.0.0-p7)
  linker_flags = -lslepc_real
}

		
