Compiler
{

  linker_flags = "-pthread -shared -Wl,-rpath,'$ORIGIN' -Wl,-rpath,'$ORIGIN/../lib'"

  C++
  {
    #executable = SDK/compiler/@ARCH/bin/g++
    executable = /usr/bin/g++
    compiler_flags = "-O3 -std=gnu++0x -pthread -fPIC -c"
  }

  C
  {
    executable = SDK/compiler/@ARCH/bin/gcc
  }

  Fortran
  {
    executable = SDK/compiler/@ARCH/bin/gfortran
  }
}

Library tibercad
{
  # path relative to TIBERCADROOT,
  includes = (
    include/base/common,
    include/base/atomistic,
    include/base/common,
    include/base/database,
    include/base/io,
    include/base/math,
    include/base/simulations,
    include/pmi,
    include/core/models,
    include/core/tightbinding,
    include/core/semiconductormodels,
    include/core/macrostrain,
    include/core/embracing,
    include/core/solver-interfaces,
    include/core/quantumEFAmodels,
    include/core/optics,
    include/core/maxwell,
    include/core/kintegrations,
    include/core/eigenvalue,
    include/utils/Tensor
  )
  libpath = @ARCH/lib
  linker_flags = -ltibercad
}


Library libmesh
{
  #path = extern/libmesh-svn-@ARCH
  path = extern/libmesh-svn-i686
  includes = (include/base, include/error_estimation,
              include/geom, include/numerics, include/partitioning,
              include/solvers, include/utils, include/enums,
              include/fe, include/mesh, include/parallel,
              include/quadrature, include/systems)
  #libpath = lib
}


Library petsc
{ 
  path = extern/petsc-3.0.0-p10
  #includes = (include, include/mpiuni, @ARCH/include)
  includes = (include, include/mpiuni, linux-gnu-i686/include)
}

Library slepc
{
  path = SDK/slepc-3.0.0-p7
  includes = (include, @ARCH/include)
}

		