Compiler
{
  # path relative to TIBERCADROOT,
  includes = (
    include/base/common,
    include/base/atomistic,
    include/base/common,
    include/base/database,
    include/base/io,
    include/base/math,
    include/base/simulations,
    include/pmi,
    include/core/models,
    include/core/tightbinding,
    include/core/semiconductormodels,
    include/core/macrostrain,
    include/core/embracing,
    include/core/solver-interfaces,
    include/core/quantumEFAmodels,
    include/core/optics,
    include/core/maxwell,maxwell
    include/core/kintegrations,
    include/core/eigenvalue
  )

  ldflags = "-shared -Wl,-rpath,'$ORIGIN' -Wl,-rpath,'$ORIGIN/../lib'"

  C++
  {
    executable = SDK/compiler/i686-linux/bin/g++
    cxxflags = "-std=gnu++0x -pthread -fPIC"
  }

  C
  {
    executable = SDK/compiler/bin/gcc
  }

  Fortran
  {
    executable = SDK/compiler/bin/gfortran
  }
}




Library petsc
{ 
  path = SDK/petsc-3.0.0-p12
  includes = (include, @ARCH/include)
}

Library slepc
{
  path = SDK/slepc-3.0.0-p7
  includes = (include, @ARCH/include)
}
