Module boltzmann
{

  sources = (Boltzmann.C, BoltzmannModel.C, BoltzmannBoundaryModel.C)
  
  boltzmann_bnd flux { sources = models/FluxBoundary.C }
  boltzmann_bnd heat_reservoir { sources = models/HeatReservoir.C }
  boltzmann_bnd periodic { sources = models/Periodic.C }
  boltzmann_bnd surface_resistance { sources = models/ThermalBoundaryResistance.C }
  
  heat_transport fourier { sources = models/FourierModel.C }
  heat_transport gray { sources = models/GrayModel.C }
  
}

