#!/bin/bash

if [ ! -e common.sh ]; then
  echo "Need configuration file (common.sh)."
  exit 1
fi

. common.sh


echo "Compiling libMesh version $LIBMESHVERSION in $BUILDDIR ..."

mkdir -p $BUILDDIR
if [ ! -d $BUILDDIR ]; then
  echo "Directory $BUILDDIR does not exist."
  exit 1
fi

ARCHIVE=libmesh-${LIBMESHVERSION}.tgz
PATCH=${PWD}/../libmesh.patch

cd $BUILDDIR
if [ ! -e ${ARCHIVE} ]; then
  wget http://dfn.dl.sourceforge.net/sourceforge/libmesh/${ARCHIVE}
fi

if [ ! -e ${ARCHIVE} ]; then
  echo "Could not download slepc."
  exit 1
fi

tar zxf ${ARCHIVE}

cd libmesh-${LIBMESHVERSION}

if [ -e ${PATCH} ]; then
  patch -p0 < ${PATCH}
fi


export PETSC_DIR=${BUILDDIR}/petsc-${PETSCVERSION}-${PATCHLEVEL}

  
./configure --enable-petsc --disable-slepc --disable-complex --disable-periodic --disable-shared


# delete the -pedantic flag because it makes problems with mpi
cp Make.common Make.common.orig
sed 's/-pedantic//g' Make.common.orig | sed 's/-D_GLIBCXX_DEBUG_PEDANTIC//g' | sed 's/-D_GLIBCXX_DEBUG//g' > Make.common


make |tee make_opt.log

if [ $DEBUG == 'y' ]; then
  make METHOD=dbg |tee make_dbg.log
fi

