#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Need directory name as argument"
  exit 1
fi

if [ -e common.sh ]; then
  . common.sh
fi

VERSION="2.3.3"
PLEVEL="p13"
DIR="$1"
ARCHIVE="petsc-lite-${VERSION}-${PLEVEL}.tar.gz"

echo "Compiling PETSc version $VERSION in $DIR ..."

mkdir -p $DIR
if [ ! -d $DIR ]; then
  echo "Directory $DIR does not exist."
  exit 1
fi

cd $DIR
wget ftp://ftp.mcs.anl.gov/pub/petsc/release-snapshots/${ARCHIVE}

if [ ! -e ${ARCHIVE} ]; then
  echo "Could not download petsc."
  exit 1
fi

tar zxf ${ARCHIVE}

cd petsc-${VERSION}-${PLEVEL}

#v=4.1.1
#export CC=gcc-$v CXX=g++-$v F77=gfortran-$v F90=$F77 FC=$F77
#export CC=gcc-$v CXX=g++-$v F77=g95-0.50 F90=g95-0.50
#export F77=g95-0.91 F90=g95-0.91 FC=g95-0.91

#export MPICH_F90=$F90
#export MPICH_F77=$F77
#export MPIDIR=/usr/pack/mpich-1.2.7p1-ma
#export LAPACK=/scratch/maufder/TiberCAD/ARPACK
#LAPACKLIBS="[${LAPACK}/libarpack.a]"

#CONFIGOPTS="--with-matlab=0 --with-shared=0 --with-dynamic=0 --with-cc=$CC --with-cxx=$CXX  --with-fc=$F90 --with-fortran=1 --CFLAGS=-fexceptions --with-mpi=0 --download-f-blas-lapack"

CONFIGOPTS="--with-matlab=0 --with-shared=0 --with-dynamic=0 --with-fortran=0 --CFLAGS=-fexceptions --with-mpi=0 "


export PETSC_DIR=${PWD}

export PETSC_ARCH=linux-gnu-opt
./config/configure.py ${CONFIGOPTS} --with-debugging=0
make |tee ${PETSC_ARCH}.log

export PETSC_ARCH=linux-gnu-complex-opt
./config/configure.py ${CONFIGOPTS} --with-scalar-type=complex  --with-clanguage=c++ --with-debugging=0
make |tee ${PETSC_ARCH}.log

if [ $DEBUG == 'y' ]; then
  export PETSC_ARCH=linux-gnu
  ./config/configure.py ${CONFIGOPTS} --with-debugging=1
  make |tee ${PETSC_ARCH}.log

  export PETSC_ARCH=linux-gnu-complex
  ./config/configure.py ${CONFIGOPTS} --with-scalar-type=complex  --with-clanguage=c++ --with-debugging=1
  make |tee ${PETSC_ARCH}.log
fi


