#!/bin/sh

#CC=gcc-4.1.1
#CXX=g++-4.1.1
F77=g95-0.91
#F77=gfortran-4.1.1
FC=$F77

LDFLAGS="-Wl,-rpath,/usr/pack/gsl-1.6-ma/lib"

#export CC CXX
export F77 FC LDFLAGS


./configure --with-gsl-prefix=/usr/pack/gsl-1.6-ma --with-fltk-prefix=`pwd`/../fltk-1.1.9 

make
make package-unix

cp -r gmsh-2.2.0 `pwd`/../trunk/contrib
