Module imagereader
{

  sources = (ImageReader.cpp)
  
  
  #installpath = @ARCH/modules/@MODULE

  Dependency paintlib
  {
    includes = paintlib-2.6.2/common
    libraries = paintlib                  # -> -lmylib
    libpath =  paintlib-2.6.2/lib/.libs       # -> -L/path/to/lib
    #installpath = @ROOT/@ARCH/modules/@MODULE
  }
  
  #creator_code = "
  #obj = DriftDiffusion::create(options);"


}

