# $Id$
#

topdir := ../..

# we have to compile each module

subdirs := classical-transport macrostrain semiconductormodels
subdirs += solver-interfaces macroheatbalance quantumEFAmodels tightbinding
subdirs += poisson


include $(topdir)/Make.common


include $(topdir)/Make.rules

