# $Id$
#

topdir := ../..

# we have to compile each module

subdirs := classical-transport macrostrain semiconductormodels solver-interfaces macroheatbalance


subdirs += solver-interfaces  quantumEFAmodels


include $(topdir)/Make.common


include $(topdir)/Make.rules

