# $Id: Makefile 3542 2013-03-01 09:31:59Z maufder $

topdir := ../..

include $(topdir)/Make.common

target := modules

modules: module.conf
	@$(BUILDMODULE) module.conf




include $(topdir)/Make.rules
