// $Id$

#ifndef _MESHINPUT_H_
#define _MESHINPUT_H_

#include <string>
#include <map>
#include <vector>



class MeshData_elements;
class Mesh;


//! General Class for mesh file  reading.
/*!
 *  Calls the  appropriate mesh reading class.  
 */
class MeshInput
{


 public:

 
  //! Static  method to  read  the  mesh  file.
  /*! 
   * Reads the  mesh file with appropriate method:
   * file_name is a .msh file (generated by GMSH) or  .grd file (generated by ISE TCAD).
   *  Needs simulation dimension (1, 2, 3), reference to Mesh and MeshData_elements objects.
   * Returns reference to  a map associating boundary condition regions to grid nodes 
   * belonging  to  the BC  region.
   */
  static  void read_mesh(const std::string& file_name, unsigned int sim_dim,
                         Mesh& mesh, MeshData_elements& mesh_data,
                         std::map<unsigned int,
                         std::vector<unsigned int> >& BoundCond  );


 private:

  //!Constructor.
  MeshInput(void);


  //! Virtual Destructor.
  virtual ~MeshInput();


};


#endif // _MESHINPUT_H_





