#ifndef _MESHINPUT_H_
#define _MESHINPUT_H_





#include <iomanip>

#include <iostream> //for I/O interaction
#include <fstream>  //for file streaming
#include <string>   //for strings
#include <set>
#include <map>
#include <vector>


//  LibMesh  include files
#include "mesh_data_elements.h"
#include "mesh_data.h"
#include "libmesh.h"
#include "mesh.h"
#include "mesh_generation.h"

using namespace std;


//! General Class for mesh file  reading.
/*!
 *  Calls the  appropriate mesh reading class.  
 */
class MeshInput
{

 public:

  //!Constructor.
  /*! 
    
  */
  MeshInput(void);

  //! Virtual Destructor.
  /*! 
    
  */
  virtual ~MeshInput();
	

 
  //! Static  method to  read  the  mesh  file.
  /*! 
   * Reads the  mesh file with appropriate method:
   * file_name is a .msh file (generated by GMSH) or  .grd file (generated by ISE TCAD).
   *  Needs simulation dimension (1, 2, 3), reference to Mesh and MeshData_elements objects.
   * Returns reference to  a map associating boundary condition regions to grid nodes 
   * belonging  to  the BC  region.
   */
  static  void read_mesh(const std::string& file_name,unsigned int sim_dim,
                         Mesh& mesh, MeshData_elements& mesh_data,
                         map<unsigned int, vector<unsigned int> >& BoundCond  );


 private:

};


#endif // _MESHINPUT_H_





