// $Id$

#ifndef _MESHINPUT_H_
#define _MESHINPUT_H_

/* #include <string> */
/* #include <map> */
#include "TypeDefs.h"

#include <vector>

class MeshData_elements;
class Mesh;


//! General Class for mesh file  reading.
/*!
 *  Calls the  appropriate mesh reading class.  
 */
class MeshInput
{


 public:

 
  //! Static  method to  read  the  mesh  file.
  /*! 
   * Reads the  mesh file with appropriate method:
   * file_name is a .msh file (generated by GMSH) or  .grd file (generated by ISE TCAD).
   * Needs simulation dimension (1, 2, 3), reference to Mesh and MeshData_elements objects.
   * Returns: a  reference to  a map (/c BoundCond) associating boundary condition regions to grid nodes 
   * belonging  to  the BC  region; a reference to a map (/c region_names_map) which associates internal 
   * mesh IDs to user-defined physical region names; a reference to a map (/c BC_region_names_map) which 
   * associates internal mesh BC IDs to user-defined BC region names.
   * NOTE: If the mesh file is not a .grd ISE grid type, these last two maps are  empty.
   */

/*   static  void read_mesh(const std::string& file_name, unsigned int sim_dim, */
/*                           Mesh& mesh, MeshData_elements& mesh_data, */
/*                           std::map<unsigned int, */
/*                           std::vector<unsigned int> >& BoundCond  ); */

  static  void read_mesh(const std::string& file_name,unsigned int sim_dim,
                         Mesh& mesh, MeshData_elements& mesh_data,
                         std::map<unsigned int, std::vector<unsigned int> >& BoundCond ,
                         std::map<ID, std::string >& region_names_map,
                         std::map<ID, std::string >& BC_region_names_map);


 private:

  //!Constructor.
  MeshInput(void);


  //! Virtual Destructor.
  virtual ~MeshInput();


};


#endif // _MESHINPUT_H_





