// $Id$

#ifndef _MESHREADER_H_
#define _MESHREADER_H_

#include "TypeDefs.h"

#include <string>
#include <vector>

class MeshData_elements;
class MeshBase;


//! General Class for mesh file  reading.
/*!
 *  Calls the  appropriate mesh reading class.  
 */
class MeshReader
{


 public:

   //! Static  method to  read  the  mesh  file.
   /*! 
    * Reads the  mesh file with appropriate method:
    * 
    * \param file_name name of a .msh file (generated by GMSH) or
    *   .grd file (generated by ISE TCAD)
    * \param sim_dim simulation dimension (1, 2, 3) from input file (-1 means none)
    * \param reference to pointer to Mesh
    * \param reference to pointer to MeshData_elements
    * \param BoundCond reference to a map associating boundary
    *   condition regions to grid nodes belonging  to  the BC  region
    * \param region_names_map reference to a map which associates internal 
    *    mesh IDs to user-defined physical region names
    * \param BC_region_names_map a reference to a map which associates internal
    *   mesh BC IDs to user-defined BC region names.
    *
    * \note If the mesh file is not a .grd ISE grid type, these last two maps are empty.
    */
   static void read_mesh(const std::string& file_name, int sim_dim,
       MeshBase*& mesh, MeshData_elements*& mesh_data,
       std::map<unsigned int, std::vector<unsigned int> >& BoundCond ,
       std::map<ID, std::string >& region_names_map,
       std::map<ID, std::string >& BC_region_names_map);


 private:

  //!Constructor.
  MeshReader(void);


  //! Virtual Destructor.
  virtual ~MeshReader();


};


#endif // _MESHREADER_H_





