/*=============================================================================
  Copyright (c) 2002-2003 Joel de Guzman
  http://spirit.sourceforge.net/


  Use, modification and distribution is subject to the Boost Software
  License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
  http://www.boost.org/LICENSE_1_0.txt)
  =============================================================================*/
///////////////////////////////////////////////////////////////////////////////
//
// 
//
//  
//
//
///////////////////////////////////////////////////////////////////////////////

#include <vector>
#include <string>

#include "mesh_data_elements.h"
#include "mesh_data.h"
#include "libmesh.h"
#include "mesh.h"


#include <InitFailedException.h>

///////////////////////////////////////////////////////////////////////////////
using namespace std;

///////////////////////////////////////////////////////////////////////////////
//
//  
//
///////////////////////////////////////////////////////////////////////////////
//! Interface to .msh mesh files (v. 1.0 and 2.0) created by GMSH .
/*!
 *  Reads and parsers the  mesh file .msh generated by GMSH code.
 * Elements with dimension dim = simulation dimension in Libmesh are extracted
 * and used (together with all the  nodes) to generate  
 *  .xda  file  (\c write_xda) and .xta file (\c write_xta)  for mesh and  meshdata in Libmesh, respectively.
 *  IDs  of  Physical Regions as  defined in GMSH  are associated to the  corresponding elements and, 
 *  with \c read_mesh_and_data, saved in Meshdata object through   the auxiliary file .xta.
 * Physical regions with elements with a dimension lower than the  simulation dimension are  treated
 *  separately:
 * they  are  extracted from the  elements  list and  a list of  nodes for  each of  such "boundary regions"
 * (1D lines for 2D  problems and  2D surfaces for 3D problems) is  created.
 * This  list can be accessed through   \c get_BC_data , which returns a map between 
 * Boundary Condition Region number (BC id) and a vector of node id.
 */

class Read_MSH
{

 public:

  //  MSH_parser(string filename , vector<int>& BC_reg_ID, int sim_dim );
  
  //  Read_MSH(string filename, vector<int>& phys_reg_ID, vector<int>& BC_reg_ID, int sim_dim  );


  //! Constructor. 
  /*!
   * Scans  GMSH .msh  file (v. 1.0 and 2.0),  parses it, gets nodes 
   * belonging to Boundary Condition regions ,
   *  writes .xda and  .xta  file for  Libmesh.
   *  needs :
   * \param filename name of  the  GMSH  .msh file (v. 1.0)
   * \param  phys_reg_ID  vector of physical region IDs,  
   * \param BC_reg_ID vector of   bound. conditions region  ID (2D or 1D)
   * \param  sim_dim dimension  of the   simulation
   * \param  mesh  reference to  \c Mesh
   * \param  mesh_data   reference to  \c MeshData_elements
   * 
   */
  //  Read_MSH(string filename, vector<unsigned int>& phys_reg_ID,
  //           vector<unsigned int>& BC_reg_ID, unsigned int sim_dim, 
  //           Mesh& mesh, MeshData_elements&  mesh_data);

  Read_MSH(string filename, unsigned int sim_dim, 
           Mesh& mesh, MeshData_elements&  mesh_data);

  //! Destructor
  ~Read_MSH();


  // void  MSH_parser::get_data ( vector< vector<double> >& glob_reg_values,
  // vector<int>& glob_reg_id,  vector<string>& glob_mat);

  void  get_data ( vector< vector<unsigned int> >& glob_elem_values);


  //! Gets  map  between  Boundary condition Regions and their nodes   
  /*!
   * Used to get the nodes belonging to the user-defined BC regions 
   * \param BoundCond_map map between BC region ID and vector of its nodes 
   * 
   */
  void  get_BC_data (   map<unsigned int, vector<unsigned int> >&  BoundCond_map);


  //! Gets  map  between  Boundary condition Regions and their nodes and elements 
  /*!
   * Used to get the nodes and the elements (case of 3D simulation)  belonging 
   * to the user-defined BC regions. 
   * \param BoundCond_map map between BC region ID and vector of its nodes 
   * \param BoundCond_el_map  map between BC region ID and vector of its elements
   */
  void  get_BC_data (   map<unsigned int, vector<unsigned int> >&  BoundCond_map,
                        map<unsigned int, vector<unsigned int> >&  BoundCond_el_map);



  void  get_elem_data (map<unsigned int, vector<unsigned int> >& PhysReg_elements_map);

  void  get_elem_phys_map (map<unsigned int,unsigned int> &elem_phys  );




 private:

 
  // Private member data

  /*!
   *  Version of  GMSH .msh file (1 or 2).
   */
  int version;

  unsigned int dim;

  map<unsigned int, vector<unsigned int> >  BoundCond;

  map<unsigned int, vector<unsigned int> >  BoundCond_elements;
  
  map<unsigned int, vector<unsigned int> > PhysReg_elements;

  map<unsigned int, unsigned int >   elem_region_map;



  vector< vector<unsigned int> > elem_values  ;

  vector< vector<double> > node_entry  ;

  vector< vector<double> >  node_coord ;



  vector< vector<unsigned int> > elem_nodes  ;

  vector<double> node_label;


  unsigned int  el_weight, num_of_elem, num_of_nodes,  num_bc, 
    num_mesh_block ; //, num_elem_per_type;

  vector<unsigned int> gmsh_elem_type;

  vector<unsigned int> elem_type;

  vector<unsigned int> num_elem_per_type ;



  struct Element {

    vector<unsigned int> nodes;
    unsigned int type;
    unsigned int phys_id  ;

  };


  vector<Element> All_elements;

  vector<Element>  list_elements;  //  list for   .xta  file  



  // Private methods

  //! Vector initialization. 
  void initialize_vectors();

  /*!
   *  Parse the element section of  GMSH .msh file (1 or 2).
   */
  void parse_elem_section(ifstream& in_stream );


  void find_elem_section(char const* str, ifstream& in_stream);


  //! call parser of  .msh  file  
  void scan_input(string file_name);



  //  unsigned int  Read_MSH::find_pos( unsigned int  reg_id ,   vector<unsigned int>& BC_reg_ID );

  unsigned int  find_pos( unsigned int  reg_id , 
                          vector<unsigned int>& user_reg_ID );


  //  void get_BC_info( vector<unsigned int>& BC_reg_ID );

  //!  Extracts nodes which  belong to  bound cond reg. (DIM-1 phys.reg.)  
  /*! 
   * Extract nodes which  belong to  bound cond reg. (DIM-1 phys.reg.) and 
   *  associate them with user defined BC regions
   */   
  void get_BC_info();



  // get  physical  regions
  //  void get_physical_elem(vector<unsigned int>& phys_reg_ID);
  //! Associate elements to corrispondent physical region
  /*! 
   * Associate elements to corrispondent physical region
   * as defined in user's phys region settings
   *  
   */  
  void get_physical_elem();



  //! write  .xda  file
  void  write_xda ( );

   
  //! get  element data  for  each  element
  void get_elem_nodes();


  //!  parser of  NODES  section of  .msh  file  (version 1)
  void parse_node_section(ifstream& in_stream );

  //  check if  $NOD  header  is  found   OBSOLETE ????
  void find_node_section(char const* str, ifstream& in_stream);

  //!  get  node  data  for  each  node
  void get_nodes_coord();

  //! Read a block in  mesh  file
  void read_data_section(char const* str,ifstream& in_stream );

  //!  write  .xta file (data file for  meshdata (elem_data.xta )  
  void  write_xta();

  //!  write  mesh  and  meshdata from  .xda and  .xta  files
  void   read_mesh_and_data(Mesh& mesh, MeshData_elements&  mesh_data );

  //  check if orientation  of  nodes  is  positive,  otherwise swap  nodes  of  element
  void  check_orientation( vector<unsigned int>&  node_id_list,  unsigned  int type );

  ////  cross check between physic_id_vec and phys_reg_ID
  void  cross_check_regions( vector<unsigned int>&  user_reg_list 
                             ,vector<unsigned int>&  gmsh_reg_list, string type );

  //! Parse  MeshFormat section (version 2)
  void parse_meshformat_section(ifstream&  in_stream);


};



