

#include <vector>
#include <string>

#include "mesh_data_elements.h"
#include "mesh_data.h"
#include "libmesh.h"
#include "mesh.h"


#include <InitFailedException.h>


///////////////////////////////////////////////////////////////////////////////
//
//  
//
///////////////////////////////////////////////////////////////////////////////
//! Interface to .msh mesh files ( format v. 1.0 and 2.0) created by GMSH .
/*!
 *  Reads and parsers the  mesh file .msh generated by GMSH code.
 * Elements with dimension dim = simulation dimension in Libmesh are extracted
 * and used (together with all the  nodes) to generate  
 *  .xda  file  (\c write_xda) and .xta file (\c write_xta)  for mesh and  meshdata in Libmesh, respectively.
 *  IDs  of  Physical Regions as  defined in GMSH  are associated to the  corresponding elements and, 
 *  with \c read_mesh_and_data, saved in Meshdata object through   the auxiliary file .xta.
 * Physical regions with elements with a dimension lower than the  simulation dimension are  treated
 *  separately:
 * they  are  extracted from the  elements  list and  a list of  nodes for  each of  such "boundary regions"
 * (0D points for 1D simulation, 0D points and 1D lines for 2D  simulation, 0D points, 1D lines and 2D surfaces 
 * for 3D problems) is  created.
 * This  list can be accessed through   \c get_BC_data , which returns a map between 
 * Boundary Condition Region number (BC id) and a vector of node id.
 */

class Read_MSH
{

 public:

  //  MSH_parser(std::string filename , std::vector<int>& BC_reg_ID, int sim_dim );
  
  //  Read_MSH(std::string filename, std::vector<int>& phys_reg_ID, std::vector<int>& BC_reg_ID, int sim_dim  );


  //! Constructor. 
  /*!
   * Scans  GMSH .msh  file (v. 1.0 and 2.0),  parses it, gets nodes 
   * belonging to Boundary  regions,
   *  writes .xda and  .xta  file for  Libmesh.
   *  needs :
   * \param filename name of  the  GMSH  .msh file 
   * \param  sim_dim dimension  of the   simulation
   * \param  mesh  reference to  \c Mesh
   * \param  mesh_data   reference to  \c MeshData_elements
   * 
   */
  //  Read_MSH(std::string filename, std::vector<unsigned int>& phys_reg_ID,
  //           std::vector<unsigned int>& BC_reg_ID, unsigned int sim_dim, 
  //           Mesh& mesh, MeshData_elements&  mesh_data);

  Read_MSH(std::string filename, unsigned int sim_dim, 
           Mesh& mesh, MeshData_elements&  mesh_data);

  //! Destructor
  ~Read_MSH();


  // void  MSH_parser::get_data ( std::vector< std::vector<double> >& glob_reg_values,
  // std::vector<int>& glob_reg_id,  std::vector<std::string>& glob_mat);

  void  get_data ( std::vector< std::vector<unsigned int> >& glob_elem_values);


  //! Gets map  between  Boundary  Regions and their nodes   
  /*!
   * Used to get the nodes belonging to the user-defined BC regions 
   * \param BoundCond_map std::map between BC region ID and std::vector of its nodes 
   * 
   */
  void  get_BC_data (  std::map<unsigned int, std::vector<unsigned int> >&  BoundCond_map);


  //! Gets map  between  Boundary condition Regions and their nodes and elements 
  /*!
   * Used to get the nodes and the elements (case of 3D simulation)  belonging 
   * to the user-defined BC regions. 
   * \param BoundCond_mapstd::map between BC region ID and std::vector of its nodes 
   * \param BoundCond_el_map std::map between BC region ID and std::vector of its elements
   */
  void  get_BC_data (  std::map<unsigned int, std::vector<unsigned int> >&  BoundCond_map,
                       std::map<unsigned int, std::vector<unsigned int> >&  BoundCond_el_map);



  //! Gets map  between  Boundary Regions and their dimension (0,1,2)
  /*!
   * Used to get the dimension of  the user-defined Boundary regions. 
   */
  void  get_BC_dimension (std::map<unsigned int, unsigned int>& BoundCond_dimension);



  void  get_elem_data (std::map<unsigned int, std::vector<unsigned int> >& PhysReg_elements_map);

  void  get_elem_phys_map (std::map<unsigned int,unsigned int> &elem_phys  );


  //! gets  map of GMSH  physical names for physical regions  and  BC  regions
  void get_physical_names_map(std::map<unsigned int, std::string >& phys_names_map);



 private:

 
  // Private member data

  /*!
   *  Version of  GMSH .msh file (1 or 2).
   */
  int version;

  unsigned int dim;


  /*!
   *  map  <BC_id, vector of  nodes>
   */
  std::map<unsigned int, std::vector<unsigned int> >  BoundCond;


  /*!
   *  map  <BC_id, BC_dim>
   */
  std::map<unsigned int, unsigned int> BoundCond_dimension;



  std::map<unsigned int, std::vector<unsigned int> >  BoundCond_elements;
  
  std::map<unsigned int, std::vector<unsigned int> > PhysReg_elements;

  std::map<unsigned int, unsigned int >   elem_region_map;



  std::vector< std::vector<unsigned int> > elem_values  ;

  std::vector< std::vector<double> > node_entry  ;

  std::vector< std::vector<double> >  node_coord ;



  std::vector< std::vector<unsigned int> > elem_nodes  ;

  std::vector<double> node_label;


  unsigned int  el_weight, num_of_elem, num_of_nodes,  num_bc, 
    num_mesh_block ; //, num_elem_per_type;

  std::vector<unsigned int> gmsh_elem_type;

  std::vector<unsigned int> elem_type;

  std::vector<unsigned int> num_elem_per_type ;



  struct Element {

    std::vector<unsigned int> nodes;
    unsigned int type;
    unsigned int phys_id  ;

  };


  std::vector<Element> All_elements;

  std::vector<Element>  list_elements;  //  list for   .xta  file  

 
  //!std::map of  GMSH  physical names for physical regions  and  BC  regions 
  std::map<unsigned int, std::string>  physical_names_map;



  // --------------------- Private methods

  //! Vector initialization. 
  void initialize_vectors();

  /*!
   *  Parse the element section of  GMSH .msh file (1 or 2).
   */
  void parse_elem_section(std::ifstream& in_stream );


  void find_elem_section(char const* str, std::ifstream& in_stream);


  //! call parser of  .msh  file  
  void scan_input(std::string file_name);



  //  unsigned int  Read_MSH::find_pos( unsigned int  reg_id ,   std::vector<unsigned int>& BC_reg_ID );

  unsigned int  find_pos( unsigned int  reg_id , 
                          std::vector<unsigned int>& user_reg_ID );


  //  void get_BC_info( std::vector<unsigned int>& BC_reg_ID );

  //!  Extracts nodes which  belong to  bound cond reg. (DIM-1 phys.reg.)  
  /*! 
   * Extract nodes which  belong to  bound cond reg. (DIM-1 phys.reg.) and 
   *  associate them with user defined BC regions
   */   
  void get_BC_info();

  //  void NEW_get_BC_info();



  // get  physical  regions
  //  void get_physical_elem(std::vector<unsigned int>& phys_reg_ID);
  //! Associate elements to corrispondent physical region
  /*! 
   * Associate elements to corrispondent physical region
   * as defined in user's phys region settings
   *  
   */  
  void get_physical_elem();



  //! write  .xda  file
  void  write_xda ( );

   
  //! get  element data  for  each  element
  void get_elem_nodes();


  //!  parser of  NODES  section of  .msh  file  (version 1)
  void parse_node_section(std::ifstream& in_stream );

  //  check if  $NOD  header  is  found   OBSOLETE ????
  void find_node_section(char const* str, std::ifstream& in_stream);

  //!  get  node  data  for  each  node
  void get_nodes_coord();

  //! Read a block in  mesh  file
  void read_data_section(char const* str,std::ifstream& in_stream );

  //!  write  .xta file (data file for  meshdata (elem_data.xta )  
  void  write_xta();

  //!  write  mesh  and  meshdata from  .xda and  .xta  files
  void   read_mesh_and_data(Mesh& mesh, MeshData_elements&  mesh_data );

  //  check if orientation  of  nodes  is  positive,  otherwise swap  nodes  of  element
  void  check_orientation( std::vector<unsigned int>&  node_id_list,  unsigned  int type );

  ////  cross check between physic_id_vec and phys_reg_ID
  void  cross_check_regions( std::vector<unsigned int>&  user_reg_list 
                             ,std::vector<unsigned int>&  gmsh_reg_list, std::string type );

  //! Parse  MeshFormat section (version 2)
  void parse_meshformat_section(std::ifstream&  in_stream);


  //! Utility to eliminate dos line  terminations
  void cut_off_CR(std::string& label,  std::ifstream& in_stream);



  //! std::map <elem_type,nodes_number> with  the number of nodes for  each  GMSH element type
  std::map<unsigned int,unsigned int > eletypes_imp;

  //! Initializes the  eletypes_imp std::map
  void init_element_types();

  //! Parse Physical Names  section
  void parse_physicalnames_section(std::ifstream&  in_stream);


};



