Module dd_generic
{

  sources = (DriftDiffusion.cpp, DriftDiffusionProperties.cpp,
             ElectricalContact.cpp, DDInterfaceModel.cpp,
             DriftDiffusionModelInterface.cpp, ThermoelectricPower.cpp,
             MobilityModelInterface.cpp, RecombinationModelInterface.cpp, CarrierProperties.cpp, DDBulkModel.cpp)
  
  
  #installpath = @ARCH/modules/@MODULE

  carrier { sources = models/DefaultBandProperties.cpp }

  recombination srh { sources = models/SRHRecombination.cpp }
  recombination auger { sources = models/AugerRecombination.cpp }
  recombination bare_auger { sources = models/AugerBare.cpp }
  recombination direct { sources = models/DirectRecombination.cpp }
  recombination band2band { sources = models/Band2Band.cpp }
  recombination avalanche_generation { sources = models/AvalancheGeneration.cpp }
  recombination schottky_tunneling { sources = models/SchottkyTunneling.cpp }
  recombination exciton_generation { sources = models/ExcitonGeneration.cpp }
  recombination exciton_decay { sources = models/ExcitonDecay.cpp }
  recombination exciton_energy_transfer { sources = models/ExcitonEnergyTransfer.cpp }
  recombination exciton_tta { sources = models/TTARecombination.cpp }
  recombination exciton_polaron_quenching { sources = models/EPQuenching.cpp }
  recombination exciton_isc { sources = models/ExcitonISC.cpp }
  recombination optical { sources = models/OpticalGeneration.cpp }
  #recombination langevin { sources = models/LangevinRecombination.cpp }
  
  mobility constant { sources = models/ConstantMobility.cpp }
  mobility doping_dependent { sources = models/DopingDependentMobility.cpp }
  mobility field_assisted { sources = models/FieldAssistedMobility.cpp }
  mobility field_dependent { sources = models/FieldDependentMobility.cpp }
  #mobility strained_Si { sources = models/SiStrainedMobility.cpp }
  mobility hopping_mobility { sources = models/HoppingMobility.cpp }
  mobility variable_range_hopping { sources = models/VariableRangeHopping.cpp } 
  
  ddbnd ohmic { sources = models/OhmicContact.cpp }
  ddbnd schottky { sources = models/SchottkyContact.cpp }

  ddbulk default { sources = models/SemiconductorModel.cpp }

  #creator_code = "
  #obj = DriftDiffusion::create(options);"


}

