Module boltzmann
{

  sources = (Boltzmann.cpp, BoltzmannModel.cpp, BoltzmannBoundaryModel.cpp)
  
  boltzmann_bnd flux { sources = models/FluxBoundary.cpp }
  boltzmann_bnd heat_reservoir { sources = models/HeatReservoir.cpp }
  boltzmann_bnd periodic { sources = models/Periodic.cpp }
  boltzmann_bnd diffusive { sources = models/Diffusive.cpp }
  boltzmann_bnd surface_resistance { sources = models/ThermalBoundaryResistance.cpp }
  
  heat_transport fourier { sources = models/FourierModel.cpp }
  heat_transport gray { sources = models/GrayModel.cpp }
  
}

