Module thermal
{

  sources = (Thermal.C, ThermalModel.C, ThermalBoundaryModel.C)
  
  thermal_bnd thermal_flux { sources = models/FluxBoundary.C }
  thermal_bnd heat_reservoir { sources = models/HeatReservoir.C }
  thermal_bnd surface_resistance { sources = models/ThermalSurfaceResistance.C }
  
}

