Module thermal
{

  sources = (Thermal.cpp, ThermalModel.cpp, ThermalBoundaryModel.cpp)
  
  thermal_bnd thermal_flux { sources = models/FluxBoundary.cpp }
  thermal_bnd heat_reservoir { sources = models/HeatReservoir.cpp }
  thermal_bnd surface_resistance { sources = models/ThermalSurfaceResistance.cpp }
  
}

