# $Id$
#

topdir := ../

# we have to compile each module
subdirs := atomistic base control embracing geom io kintegration math module physics profiles utils solver 

include $(topdir)/Make.common


include $(topdir)/Make.rules

