// $Id$

#ifndef _MESHREADER_H_
#define _MESHREADER_H_

#include "tibercad/base/tiber_dll.h"

#include <string>

class MeshRegionInfo;
class BoundaryRegions;

namespace libMesh
{
class MeshBase;
}


//! General Class for mesh file  reading.
/*!
 *  Calls the  appropriate mesh reading class.  
 */
class TBDLLOCAL MeshReader
{


 public:

   //! Static  method to  read  the  mesh  file.
   /*! 
    * Reads the  mesh file with appropriate method:
    * 
    * \param file_name name of a .msh file (generated by GMSH) or
    *   .grd file (generated by ISE TCAD)
    * \param reference to the Mesh
    * \param region_info container to hold info about the mesh regions
    * \param bd_regions container to hold info about lower dimensional regions
    *
    * \note If the mesh file is not a .grd ISE grid type, these last two maps are empty.
    */
   static void read_mesh(const std::string& filename, libMesh::MeshBase& mesh,
       MeshRegionInfo& region_info, BoundaryRegions& bd_regions);


 private:

  //!Constructor.
  MeshReader(void);


};


#endif // _MESHREADER_H_





