/*
 * This file is part of tiberCAD.
 *
 * tiberCAD is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * tiberCAD is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with tiberCAD. If not, see <https://www.gnu.org/licenses/>.
 */

/*!
 * \file MeshReader.h
 * \brief Public tiberCAD API header.
 *
 * \note This header is part of the public tiberCAD API.
 *       API version: 3.5
 */


#ifndef TC_MESHREADER_H
#define TC_MESHREADER_H

#include "tibercad/base/tiber_dll.h"

#include <string>

class MeshRegionInfo;
class BoundaryRegions;

namespace libMesh
{
class MeshBase;
}


//! General Class for mesh file  reading.
/*!
 *  Calls the  appropriate mesh reading class.  
 */
class TBDLLOCAL MeshReader
{


 public:

   //! Static  method to  read  the  mesh  file.
   /*! 
    * Reads the  mesh file with appropriate method:
    * 
    * \param file_name name of a .msh file (generated by GMSH) or
    *   .grd file (generated by ISE TCAD)
    * \param reference to the Mesh
    * \param region_info container to hold info about the mesh regions
    * \param bd_regions container to hold info about lower dimensional regions
    *
    * \note If the mesh file is not a .grd ISE grid type, these last two maps are empty.
    */
   static void read_mesh(const std::string& filename, libMesh::MeshBase& mesh,
       MeshRegionInfo& region_info, BoundaryRegions& bd_regions);


 private:

  //!Constructor.
  MeshReader(void);


};


#endif // TC_MESHREADER_H





