// $Id$

#include "GraceIO.h"

#include "elem.h"
#include "mesh_base.h"

// C++ includes
#include <fstream>
#include <sstream>
#include <map>
#include <stdexcept>

GraceIO::GraceIO(const MeshBase& mesh)
  : MeshOutput<MeshBase>(mesh)
{
}


void GraceIO::write_nodal_data(const std::string& fname,
    const std::vector<Number>& soln,
    const std::vector<std::string>& names)
{

  if(libMesh::processor_id() != 0)
    return;

  if (names.size() == 0)
    return;

  const MeshBase& mesh = MeshOutput<MeshBase>::mesh();

  // This class is designed only for use with 1D meshes
  if (mesh.mesh_dimension() > 1)
    return;


  // Create an output stream for script file
  std::ofstream out(fname.c_str());

  if (!out.good())
    throw std::runtime_error("Could not open " + fname);

  // The number of variables in the equation system
  const unsigned int n_vars = names.size();
  
  // Write header to stream
  out << "# This file was generated by TiberCAD (GraceIO.C)\n"
      << "# Stores 1D nodal data in format suitable for Grace\n"
      << "# x";
  for (unsigned int i = 0; i < names.size(); i++)
    out << "\t" << names[i];
  out << std::endl;
      
  // get ordered nodal data using a map
  typedef std::pair<Real, std::vector<Number> > key_value_pair;
  typedef std::map<Real, std::vector<Number> > map_type;
  typedef map_type::iterator map_iterator;

  map_type node_map;


  MeshBase::const_element_iterator       it  = mesh.active_elements_begin();
  const MeshBase::const_element_iterator end = mesh.active_elements_end(); 

  for ( ; it != end; ++it)
  {
    const Elem* elem = *it;

    for(unsigned int i = 0; i < elem->n_nodes(); i++)
    {
      std::vector<Number> values;

      // Get the global id of the node
      unsigned int global_id = elem->node(i);

      for(unsigned int c=0; c<n_vars; c++)
      {
        values.push_back(soln[global_id*n_vars + c]);
      }

      node_map[mesh.point(global_id)(0)] = values;
    }
  }

  out << std::setprecision(10);
    
  map_iterator map_it = node_map.begin();
  const map_iterator end_map_it = node_map.end();

  for( ; map_it != end_map_it; ++map_it)
  {
    key_value_pair kvp = *map_it;
    std::vector<Number> values = kvp.second;

    out << kvp.first << "\t";

    for(unsigned int i = 0; i < values.size(); i++)
    {
      out << values[i] << "\t";
    }

    out << "\n";
  }

  out.close();
}




void GraceIO::write_elemental_data(const std::string& fname,
    const std::vector<Number>& soln,
    const std::vector<std::string>& names)
{

  if(libMesh::processor_id() != 0)
    return;

  if (names.size() == 0)
    return;

  const MeshBase& mesh = MeshOutput<MeshBase>::mesh();

  // This class is designed only for use with 1D meshes
  if (mesh.mesh_dimension() > 1)
    return;


  // Create an output stream for script file
  std::ofstream out(fname.c_str());

  if (!out.good())
    throw std::runtime_error("Could not open " + fname);

  // The number of variables in the equation system
  const unsigned int n_vars = names.size();
  
  // Write header to stream
  out << "# This file was generated by TiberCAD (GraceIO.C)\n"
      << "# Stores 1D elemental data in format suitable for Grace\n"
      << "# x";
  for (unsigned int i = 0; i < names.size(); i++)
    out << "\t" << names[i];
  out << std::endl;
      
  // get ordered nodal data using a map
  typedef std::pair<Real, std::vector<Number> > key_value_pair;
  typedef std::map<Real, std::vector<Number> > map_type;
  typedef map_type::iterator map_iterator;

  map_type node_map;


  MeshBase::const_element_iterator       it  = mesh.active_elements_begin();
  const MeshBase::const_element_iterator end = mesh.active_elements_end(); 

  unsigned int elem_number = 0;
  for ( ; it != end; ++it)
  {
    const Elem* elem = *it;

    std::vector<Number> values;

    // Get the global id of 
    unsigned int global_id = elem_number * n_vars;

    for(unsigned int c = 0; c < n_vars; c++)
    {
      values.push_back(soln[global_id + c] );
    }

    node_map[elem->centroid()(0)] = values;

    elem_number++;
  }

  out << std::setprecision(10);
    
  map_iterator map_it = node_map.begin();
  const map_iterator end_map_it = node_map.end();

  for( ; map_it != end_map_it; ++map_it)
  {
    key_value_pair kvp = *map_it;
    std::vector<Number> values = kvp.second;

    out << kvp.first << "\t";

    for(unsigned int i = 0; i < values.size(); i++)
    {
      out << values[i] << "\t";
    }

    out << "\n";
  }

  out.close();

}
