// $Id$

#include "GraceIO.h"
#include "RuntimeException.h"

#include "elem.h"
#include "mesh_base.h"

// C++ includes
#include <fstream>
#include <iomanip>
#include <sstream>
#include <map>
#include <stdexcept>

using namespace std;



GraceIO::GraceIO(const MeshBase& mesh)
  : DataOutput()
{
  set_mesh(mesh);
}


void GraceIO::write_nodal_data(const std::string& fname,
    const std::vector<double>& soln,
    const std::vector<std::string>& names)
{

  if (names.size() == 0)
    return;

  const MeshBase& mesh = get_mesh();

  // This class is designed only for use with 1D meshes
  //if (mesh.mesh_dimension() > 1)
  //  return;


  // Create an output stream for script file
  std::ofstream out(fname.c_str());

  if (!out.good())
    throw std::runtime_error("Could not open " + fname);

  // The number of variables in the equation system
  const unsigned int n_vars = names.size();

  // Write header to stream
  out << "# This file was generated by TiberCAD (GraceIO.C)\n"
      << "# Stores 1D nodal data in format suitable for Grace\n"
      << "# x";
  for (unsigned int i = 0; i < names.size(); i++)
    out << "\t" << names[i];
  out << std::endl;

  // get ordered nodal data using a map
  typedef std::pair<Real, std::vector<Number> > key_value_pair;
  typedef std::map<Real, std::vector<Number> > map_type;
  typedef map_type::iterator map_iterator;

  map_type node_map;

  double po_x = mesh.point(0)(0);
  double po_y = mesh.point(0)(1);
  double po_z = mesh.point(0)(2);
  double dl = 0.0;
  
  for(unsigned int i = 0; i < mesh.n_nodes(); i++)
  {
    std::vector<double> values;

    // Get the global id of the node
    unsigned int global_id = i; //elem->node(i);

    for(unsigned int c=0; c<n_vars; c++)
    {
      values.push_back(soln[global_id*n_vars + c]);
    }

    // This is done to make the Grace plot independent 
    // from the mesh dimension

    if (mesh.mesh_dimension()==1)
    {
      double p_x = mesh.point(global_id)(0);
      node_map[p_x] = values;     
    }
    else
    {
      double p_x = mesh.point(global_id)(0);
      double p_y = mesh.point(global_id)(1);
      double p_z = mesh.point(global_id)(2);

      dl += sqrt( (p_x-po_x)*(p_x-po_x) + 
                  (p_y-po_y)*(p_y-po_y) + 
                  (p_z-po_z)*(p_z-po_z) );

      node_map[dl] = values;

      po_x = p_x;
      po_y = p_y;
      po_z = p_z;
    }
  }

  out << std::setprecision(10);

  map_iterator map_it = node_map.begin();
  const map_iterator end_map_it = node_map.end();

  for( ; map_it != end_map_it; ++map_it)
  {
    key_value_pair kvp = *map_it;
    std::vector<Number> values = kvp.second;

    out << kvp.first << "\t";

    for(unsigned int i = 0; i < values.size(); i++)
    {
      out << values[i] << "\t";
    }

    out << "\n";
  }

  out.close();
}




void GraceIO::write_elemental_data(const std::string& fname,
    const std::vector<double>& soln,
    const std::vector<std::string>& names)
{

  if (names.size() == 0)
    return;

  const MeshBase& mesh = get_mesh();

  // This class is designed only for use with 1D meshes
  if (mesh.mesh_dimension() > 1)
    return;


  // Create an output stream for script file
  std::ofstream out(fname.c_str());

  if (!out.good())
    throw std::runtime_error("Could not open " + fname);

  // The number of variables in the equation system
  const unsigned int n_vars = names.size();

  // Write header to stream
  out << "# This file was generated by TiberCAD (GraceIO.C)\n"
      << "# Stores 1D elemental data in format suitable for Grace\n"
      << "# x";
  for (unsigned int i = 0; i < names.size(); i++)
    out << "\t" << names[i];
  out << std::endl;

  // get ordered nodal data using a map
  typedef std::pair<Real, std::vector<Number> > key_value_pair;
  typedef std::map<Real, std::vector<Number> > map_type;
  typedef map_type::iterator map_iterator;

  map_type node_map;


  MeshBase::const_element_iterator       it  = mesh.active_elements_begin();
  const MeshBase::const_element_iterator end = mesh.active_elements_end();

  unsigned int elem_number = 0;
  for ( ; it != end; ++it)
  {
    const libMesh::Elem* elem = *it;

    std::vector<Number> values;

    // Get the global id of
    unsigned int global_id = elem_number * n_vars;

    for(unsigned int c = 0; c < n_vars; c++)
    {
      values.push_back(soln[global_id + c] );
    }

    node_map[elem->centroid()(0)] = values;

    elem_number++;
  }

  out << std::setprecision(10);

  map_iterator map_it = node_map.begin();
  const map_iterator end_map_it = node_map.end();

  for( ; map_it != end_map_it; ++map_it)
  {
    key_value_pair kvp = *map_it;
    std::vector<Number> values = kvp.second;

    out << kvp.first << "\t";

    for(unsigned int i = 0; i < values.size(); i++)
    {
      out << values[i] << "\t";
    }

    out << "\n";
  }

  out.close();

}


void
GraceIO::create_pieces(PieceMap& pieces)
{
  const MeshBase& mesh = get_mesh();

  MeshBase::const_element_iterator it  = mesh.active_local_elements_begin();
  const MeshBase::const_element_iterator end = mesh.active_local_elements_end();

  unsigned int nelem = mesh.n_elem();

  for ( ; it != end; ++it)
  {
    const libMesh::Elem* elem = *it;
    unsigned int id = elem->subdomain_id();

    if (! pieces.count(id))
      pieces[id].reserve(nelem);

    pieces[id].push_back(elem);
  }

  PieceMap::iterator xit(pieces.begin());
  const PieceMap::iterator xend(pieces.end());
  for ( ; xit != xend; ++xit)
  {
    (xit->second).resize((xit->second).size());
  }

}




void
GraceIO::do_write(bool force)
{
  const MeshBase& mesh = get_mesh();
  if (mesh.mesh_dimension() != 1)
  {
    ostringstream os;
    os <<"Trying to write 1D \'.dat\' file with " << mesh.mesh_dimension()
        << "D data.";
    throw RuntimeException(os.str());
  }

  string file = get_filename() + ".dat";
  ofstream of;


  PieceMap pieces;
  create_pieces(pieces);

  // the total number of data values
  unsigned int tot_values = 0;

  // first write legend
  PieceMap::iterator it(pieces.begin());
  const PieceMap::iterator end(pieces.end());

  // this is done only on rank 0
  if (mesh.comm().rank() == 0)
  {
    of.open(file.c_str());
    for ( ; it != end; ++it)
    {
      ID id = it->first;

      if (has_data(id) || force)
      {
        of << "# ASCII 1D datafile generated by TiberCAD\n# x ";

        const DataMap& data = get_zone_data(id);

        DataMap::const_iterator it(data.begin());
        const DataMap::const_iterator end(data.end());
        for ( ; it != end; ++it)
        {
          const SolutionDescriptor& descr = it->first;
          const string& name = descr.name();

          tot_values += descr.n_components();

          switch (descr.type())
          {
            case SolutionDescriptor::VECTOR:
              of << name << "_x "
              << name << "_y "
              << name << "_z ";
              break;

            case SolutionDescriptor::TENSOR:
              of << name << "_11 "
              << name << "_22 "
              << name << "_33 "
              << name << "_12 "
              << name << "_23 "
              << name << "_13 ";
              break;

            case SolutionDescriptor::NTUPLE:
              for (unsigned int i = 0; i < descr.n_components(); i++)
                of << name << "_" << i << " ";
              break;

            default:
              of << name << " ";
              break;
          }
        }

        // this assumes that all data exist on all pieces!
        break;
      }
    }

    of << "\n";
    of.flush();
    of.close();
  }

  mesh.comm().broadcast(tot_values);

  // we put all data into an ordered list to be sure that
  // x coordinate is ordered
  multimap<double, pair<ID, vector<double> > > buffer;

  for (it = pieces.begin(); it != end; ++it)
  {
    ID id = it->first;

    if (has_data(id) || force)
    {
      const DataMap& datamap = get_zone_data(id);

      const vector<const libMesh::Elem*>& elvec = it->second;

      map<const libMesh::Elem*, unsigned int> elem_indices;
      // loop over all elements and make a map with element
      // position indices
      for (unsigned int n = 0; n < elvec.size(); n++)
        elem_indices[elvec[n]] = n;

      // the node counter (regions might not be connected!)
      unsigned int node = 0;

      // loop over all elements
      for (unsigned int n = 0; n < elvec.size(); n++)
      {
        const libMesh::Elem* elem = elvec[n];

        //loop over the nodes
        for (int i = 0; i < 2; i++)
        {
          const libMesh::Elem* neighbor = elem->neighbor(i);
          ID neighbor_id = INVALID_ID;
          if (neighbor != NULL)
            neighbor_id = neighbor->subdomain_id();

          // we take only first node, unless it is the last of a connected
          // piece of the region
          if ((i == 0) || (id != neighbor_id))
          {
            double x = elem->point(i)(0);

            // add the point
            // we need the id, too, because we might have to
            // swap data on boundary points
            multimap<double, pair<ID, vector<double> > >::iterator iter;
            iter = buffer.insert(make_pair(x, make_pair(id, vector<double>(0))));
            vector<double>& vec = (iter->second).second;
            vec.reserve(tot_values);

            // insert data
            DataMap::const_iterator it(datamap.begin());
            const DataMap::const_iterator end(datamap.end());
            for ( ; it != end; ++it)
            {
              const SolutionDescriptor& descr = it->first;
              const vector<double>& data = it->second;

              unsigned int ncomp = descr.n_components();
              // the index in the element data array
              unsigned int index = ncomp * n;
              // the index in the node data array
              unsigned int n_index = ncomp * node;
              for (unsigned int nc = 0; nc < ncomp; nc++)
              {
                if (descr.location() == SolutionDescriptor::CELL)
                {
                  if (id != neighbor_id)
                    vec.push_back(data[index + nc]);
                  else if (i == 0)
                  {
                    // 1) the left element has the same region index
                    // 2) there is a left element
                    // HOWEVER: the elements might not be ordered, therefore
                    // we get the element index from the elem_indices map
                    unsigned int left_index = ncomp * elem_indices[neighbor];
                    double y1 = data[left_index + nc];
                    double y2 = data[index + nc];
                    double d1 = (x - neighbor->point(0)(0));
                    double d2 = (elem->point(1)(0) - x);
                    double val = (y1 * d2 + y2 * d1) / (d1 + d2);
                    vec.push_back(val);
                  }
                }
                else
                  vec.push_back(data[n_index + nc]);
              }
            }
            node++;
          }
        }
      }
    }
  }

  // Now all processes have their data prepared. Let's now write out in
  // ordered mode

  multimap<double, pair<ID, vector<double> > >::iterator
    bit(buffer.begin());
  const multimap<double, pair<ID, vector<double> > >::iterator
    bend(--buffer.end());

  vector<double> x0(mesh.comm().size());
  mesh.comm().allgather(bit->first, x0);

  map<double, unsigned int> ranks;
  for (unsigned int i = 0; i < x0.size(); ++i)
    ranks[x0[i]] = i;

  // the rank having the right data should write now, the others wait
  for (auto&& r_it : ranks)
  {
    if (mesh.comm().rank() == r_it.second)
    {
      of.open(file.c_str(), std::ofstream::app);

      ID oldid = INVALID_ID;
      while (bit != bend)
      {
        ID currid = (bit->second).first;
        double x = bit->first;
        const vector<double>& vals = (bit->second).second;
        double xnext = (++bit)->first;
        if ((xnext == x) && (currid != oldid))
        {
          of << xnext << " ";

          for (unsigned int i = 0; i < tot_values; i++)
            of << (bit->second).second[i] << " ";

          of << "\n";
          ++bit;
        }
        of << x << " ";

        for (unsigned int i = 0; i < tot_values; i++)
          of << vals[i] << " ";

        of << "\n";

        oldid = currid;
      }

      of << bit->first << " ";
      for (unsigned int i = 0; i < tot_values; i++)
        of << (bit->second).second[i] << " ";

      of << "\n";
      of.flush();
    }
    mesh.comm().barrier();
  }
}
