// C++ includes
#include <fstream>
#include <iostream>
//#include <stdlib.h>

// Local includes
#include "tecplot_io.h"
#include "mesh_base.h"
#include "elem.h"
//#include <stdio.h>
#include <iomanip>

#include "tecplot_IO_cell.h"
void TecplotIO_cell::write_cell_data (const std::string& fname,
				      const std::vector<Number>& soln,
				      const std::vector<std::string>& names)
{
  if (libMesh::processor_id() == 0)
    {
      if (this->binary())
	{
	  std::cerr << "ERROR : Not implemented \n" ;
	  exit(1);
	}
      //	this->write_binary (fname, &soln, &names);
      else
	this->write_ascii_cell  (fname, &soln, &names);
    }
}



void TecplotIO_cell::write_ascii_cell (const std::string& fname,
				       const std::vector<Number>* v,
				       const std::vector<std::string>* solution_names)
{
  // Should only do this on processor 0!
  assert (libMesh::processor_id() == 0);
  
  // Create an output stream
  std::ofstream out(fname.c_str());

  if (!out.good())
    {
      std::cerr << "ERROR: opening output file " << fname
		<< std::endl;
      error();
    }

  // Get a constant reference to the mesh.
  const MeshBase& mesh = MeshOutput<MeshBase>::mesh();
  
  // Write header to stream
  {
    {
      out << "# This file was generated by:\n"
	  << "#\n"
	  << "# $Id: tecplot_io_cell.C, 23/1/2006   Exp $\n"
	  << "#\n"
	  << "# For a description of the Tecplot format see the Tecplot User's guide.\n"
	  << "#\n";
    }

    out << "Variables=x,y,z";
    //  BEWARE:  z  must  be  always  present (also in 2D)
  


    if (solution_names != NULL)
      for (unsigned int n=0; n<solution_names->size(); n++)
	{
#ifdef USE_REAL_NUMBERS
	  
	  // Write variable names for real variables
	  out << "," << (*solution_names)[n];

#else
	  
	  // Write variable names for complex variables
	  out << "," << "r_"   << (*solution_names)[n]
	      << "," << "i_"   << (*solution_names)[n]
	      << "," << "a_"   << (*solution_names)[n];
	  
#endif
	}

    out << '\n';
    

    int number_of_solution_variables = solution_names->size();

    if (mesh.mesh_dimension() != 1)
      {
	// beware: deprecated tecplot syntax
	out << "Zone f=feblock, n=" << mesh.n_nodes() << ", e=" << mesh.n_active_sub_elem();
	
	if (mesh.mesh_dimension() == 2)
	  out << ", et=quadrilateral\n";
	else if (mesh.mesh_dimension() == 3)
	  out << ", et=brick\n";
	// trick: in  connectivity fictitious nodes are  added to elements, to  get  in  any case a
	// quadrilateral in  2D  or  a   brick  in 3D ->  so  this  syntax  is  consistent for any  type
	//  of  element (?)
	//
	// cells!!
	//	out << "ZONE DATAPACKING=BLOCK \n";
	//	out << "VARLOCATION=([4]=CELLCENTERED) \n";  
	//  for  cell based data ! (see tecplot manual)
	out << "VARLOCATION=([";
	// for (unsigned int j=0; j<number_of_solution_variables ; j++)
	//   {
	if (number_of_solution_variables != 1)
	  {
	out << " 4" << "-" << (3+number_of_solution_variables);
	  }
	else out << "4" ;
	out << "]=CELLCENTERED) \n";

      }
  }


  //  all values  must  be  given  for each  variable at a  time:
  //  all  values of  x,  then  all values of  y, ....


  // writes values of  variable x,  y,  z ; there should  be  always 3  coord. whatever the  simulation dim  
  unsigned int n_nodes = mesh.n_nodes();
  for (unsigned int alpha=0; alpha<3; alpha++)
    {

      for (unsigned int i=0; i<n_nodes; i++)
	{

	  double coord = mesh.point(i)(alpha);
	  out << coord << "   " ;
	  if ( (i % 4 ) == 0 ) out << "\n";
	}
      out << "\n";
    }



  // NEW :  write ELEMENT data !!!!
  const  int num_active_elem = mesh.n_active_elem(); 

  if ((v != NULL) && (solution_names != NULL))
    {
      const unsigned int n_vars = solution_names->size();

      // ..........
      if (!(v->size() == num_active_elem*n_vars))
        std::cerr << "ERROR: v->size()=" << v->size()
                  << ", mesh.n_active_elem()=" << mesh.n_active_elem()
                  << ", n_vars=" << n_vars
                  << ", mesh.n_active_elem()*n_vars=" << mesh.n_active_elem()*n_vars
                  << "\n";
      
      assert (v->size() == mesh.n_active_elem()*n_vars);

      for (unsigned int c=0; c<n_vars; c++)
        {
#ifdef USE_REAL_NUMBERS	      
	  // Write real data
	  //    out << (*v)[i*n_vars + c] << " ";
	 
	  
          for (unsigned int n=0; n<num_active_elem; n++)
	    {
	      out << std::setprecision(10) << (*v)[n*n_vars + c] << " ";
	      if ( (n % 4 ) == 0 ) out << "\n";
	    }
	  
          out << "\n\n";


#else
	  //
	  // Write complex data  ????????
	  //
	  std::cerr << "ERROR : Not implemented \n" ;
	  exit(1);

	  //   out << (*v)[i*n_vars + c].real() << " "
	  // 	      << (*v)[i*n_vars + c].imag() << " "
	  // 	      << std::abs((*v)[i*n_vars + c]) << " ";

#endif
	}	  
    }

  // Write a new line after the data for this node
  out << '\n';	  
  //}


  MeshBase::const_element_iterator       it  = mesh.active_elements_begin();
  const MeshBase::const_element_iterator end = mesh.active_elements_end(); 

  for ( ; it != end; ++it)
    (*it)->write_connectivity(out, TECPLOT);
}






//   for (unsigned int i=0; i<mesh.n_nodes(); i++)
//     {
//       // Print the point without a newline
//       mesh.point(i).write_unformatted(out, false);

//       if ((v != NULL) && (solution_names != NULL))
// 	{
// 	  const unsigned int n_vars = solution_names->size();


// 	  for (unsigned int c=0; c<n_vars; c++)
// 	    {
// #ifdef USE_REAL_NUMBERS	      
// 	      // Write real data
// 	      out << (*v)[i*n_vars + c] << " ";

// #else
// 	      // Write complex data
// 	      out << (*v)[i*n_vars + c].real() << " "
// 		  << (*v)[i*n_vars + c].imag() << " "
// 		  << std::abs((*v)[i*n_vars + c]) << " ";

// #endif
// 	    }	  
// 	}

//       // Write a new line after the data for this node
//       out << '\n';	  
//     }

// //   const_active_elem_iterator       it (mesh.elements_begin());
// //   const const_active_elem_iterator end(mesh.elements_end());

//   MeshBase::const_element_iterator       it  = mesh.active_elements_begin();
//   const MeshBase::const_element_iterator end = mesh.active_elements_end(); 

//   for ( ; it != end; ++it)
//     (*it)->write_connectivity(out, TECPLOT);
// }


