Module interpolation
{

  sources = (Interpolation.C)

  #installpath = @ARCH/modules/@MODULE

  Dependency strangelib
  {
    include = /path/to/include
    libs = mylib                  # -> -lmylib
    libpath = /path/to/lib        # -> -L/path/to/lib
    [installpath = where/to/put/it]
  }

  # the /hdf5/lib/ path has to be added 
  # to the environment variable LD_LIBRARY_PATH
  # otherwise the hdf5 library will not be found at runtime
  Dependency libhdf5
  {
    includes = /home/fsantoni/software/hdf5/include/
    libraries = (hdf5, hdf5_hl)
    libpath = /home/fsantoni/software/hdf5/lib/
    install = false
  }

}

